// @generated by tools/codegen/gen_gaos.py from google-genai 2.28.0. DO NOT EDIT.
//
// SPDX-FileCopyrightText: 2025 Google LLC
// SPDX-FileCopyrightText: 2026 Daisuke ITO
// SPDX-License-Identifier: Apache-2.0
//
// Derived from the Google Gen AI Python SDK (google-genai 2.28.0),
// https://github.com/googleapis/python-genai
// Copyright 2025 Google LLC, licensed under the Apache License, Version 2.0.
//
// Modified: mechanically derived from the Python SDK's internal `_gaos` sub-SDK by gen_gaos.py:
// model fields, string enums and unions were reflected into Rust types, and HTTP
// operations were extracted from the resource classes. Doc comments reproduce the
// upstream Python docstrings.
//
// See the NOTICE file at the repository root for the full attribution.
//
// Edit tools/codegen/gen_gaos.py (or tools/codegen/gaos_overrides.toml) and re-run
// `python tools/codegen/generate.py --only gaos` instead.

//! The `_gaos` sub-SDK of google-genai: Interactions, agents, environments, triggers,
//! webhooks, voices and credentials. Generated by `tools/codegen/gen_gaos.py`; the public
//! modules (`crate::agents`, ...) re-export from `exports`.

#![allow(
    clippy::pedantic,
    clippy::large_enum_variant,
    clippy::enum_variant_names,
    dead_code,
    rustdoc::bare_urls,
    reason = "mechanically generated port of the google-genai `_gaos` sub-SDK; pedantic-tier style lints, size-based enum lints and bare-URL doc warnings do not apply to a generated public API surface whose doc comments are verbatim Python docstrings"
)]

pub mod models;
pub mod resources;
pub mod types;

/// Wire helpers shared by the generated operations.
pub(crate) mod wire {
    use std::{collections::HashMap, fmt::Display};

    use bytes::Bytes;
    use serde::de::DeserializeOwned;
    use serde_json::{Value, json};

    use crate::{errors::Result, types::HttpOptions};

    /// Percent-encodes one path parameter. RFC 3986 unreserved characters and `/`
    /// pass through: the Python SDK substitutes path parameters verbatim, so a
    /// nested resource name or file path (`projects/p/triggers/t`, `src/main.py`)
    /// keeps its slashes on the wire. Reserved characters such as `?`, `#` and
    /// `%` are escaped (Python lets them truncate the URL).
    pub(crate) fn path_segment(segment: &str) -> String {
        segment
            .bytes()
            .map(|byte| match byte {
                b'A'..=b'Z' | b'a'..=b'z' | b'0'..=b'9' | b'-' | b'.' | b'_' | b'~' | b'/' => {
                    char::from(byte).to_string()
                }
                other => format!("%{other:02X}"),
            })
            .collect()
    }

    /// Accumulates `form`-style (exploded) query parameters.
    #[derive(Debug, Default)]
    pub(crate) struct Query {
        pairs: Vec<(String, String)>,
    }

    impl Query {
        /// Adds `name=value` when `value` is set.
        pub(crate) fn push<T: Display>(&mut self, name: &str, value: Option<&T>) {
            if let Some(value) = value {
                self.pairs.push((name.to_owned(), value.to_string()));
            }
        }

        /// Adds one `name=value` pair per element (exploded array).
        pub(crate) fn push_all<T: Display>(&mut self, name: &str, values: Option<&[T]>) {
            for value in values.unwrap_or_default() {
                self.pairs.push((name.to_owned(), value.to_string()));
            }
        }

        /// Replaces every value of `name` with `value`.
        pub(crate) fn set(&mut self, name: &str, value: &str) {
            self.pairs.retain(|(existing, _)| existing != name);
            self.pairs.push((name.to_owned(), value.to_owned()));
        }

        /// The encoded query string, or `None` when empty.
        pub(crate) fn finish(self) -> Option<String> {
            if self.pairs.is_empty() {
                return None;
            }
            let mut serializer = url::form_urlencoded::Serializer::new(String::new());
            serializer.extend_pairs(&self.pairs);
            Some(serializer.finish())
        }
    }

    /// Decodes a JSON response body; an empty body decodes as `{}`.
    pub(crate) fn parse<T: DeserializeOwned>(body: &Bytes) -> Result<T> {
        if body.is_empty() {
            return Ok(serde_json::from_value(json!({}))?);
        }
        Ok(serde_json::from_slice(body)?)
    }

    /// Sets `"stream": true` on a JSON object body.
    pub(crate) fn with_stream_flag(mut body: Value) -> Value {
        if let Value::Object(map) = &mut body {
            map.insert("stream".to_owned(), Value::Bool(true));
        }
        body
    }

    /// The per-call options of a streaming request: `base` plus an
    /// `Accept: text/event-stream` header asking for a server-sent-event response.
    pub(crate) fn stream_http_options(base: Option<&HttpOptions>) -> HttpOptions {
        let mut options = base.cloned().unwrap_or_default();
        options
            .headers
            .get_or_insert_with(HashMap::new)
            .insert("Accept".to_owned(), "text/event-stream".to_owned());
        options
    }
}

/// Allowed top-level keys of an `Interactions.create` request body: the union of the
/// model and agent shapes (upstream `_CREATE_BODY_KEYS`).
pub(crate) const CREATE_BODY_KEYS: &[&str] = &[
    "agent",
    "agent_config",
    "background",
    "cached_content",
    "continuation_token",
    "environment",
    "generation_config",
    "input",
    "labels",
    "model",
    "previous_interaction_id",
    "response_format",
    "response_mime_type",
    "response_modalities",
    "safety_settings",
    "service_tier",
    "store",
    "stream",
    "system_instruction",
    "tools",
    "webhook_config",
];

/// Per-module re-exports mirroring the `__all__` of the upstream public modules.
pub mod exports {
    /// Re-exports for `crate::agents`.
    pub mod agents {
        pub use crate::gaos::models::ListAgentsRequest as AgentListParams;
        pub use crate::gaos::resources::agents::Agents;
        pub use crate::gaos::types::agents::Agent as AgentCreateParams;
        pub use crate::gaos::types::agents::Agent as AgentParam;
        pub use crate::gaos::types::agents::Agent;
        pub use crate::gaos::types::agents::AgentListResponse;
        pub use crate::gaos::types::agents::AgentTool;
        pub use crate::gaos::types::agents::BaseEnvironment;
        pub use crate::gaos::types::interactions::AntigravityAgentConfig as AgentConfig;
        pub use crate::gaos::types::interactions::AntigravityAgentConfig as AgentConfigParam;
        pub use crate::gaos::types::interactions::Empty as AgentDeleteResponse;
    }
    /// Re-exports for `crate::credentials`.
    pub mod credentials {
        pub use crate::gaos::models::ListCredentialsRequest as CredentialListParams;
        pub use crate::gaos::models::UpdateCredentialRequest;
        pub use crate::gaos::resources::credentials::Credentials;
        pub use crate::gaos::types::credentials::Credential;
        pub use crate::gaos::types::credentials::CredentialCreateParams;
        pub use crate::gaos::types::credentials::CredentialListResponse;
        pub use crate::gaos::types::credentials::CredentialUpdate;
        pub use crate::gaos::types::credentials::EnvironmentVariableConfig as EnvironmentVariableConfigParam;
        pub use crate::gaos::types::credentials::EnvironmentVariableConfig;
        pub use crate::gaos::types::credentials::EnvironmentVariableConfigInjectionLocation as EnvironmentVariableConfigInjectionLocationParam;
        pub use crate::gaos::types::credentials::EnvironmentVariableConfigInjectionLocation as EnvironmentVariableUpdateConfigInjectionLocation;
        pub use crate::gaos::types::credentials::EnvironmentVariableConfigInjectionLocation as EnvironmentVariableUpdateConfigInjectionLocationParam;
        pub use crate::gaos::types::credentials::EnvironmentVariableConfigInjectionLocation;
        pub use crate::gaos::types::credentials::EnvironmentVariableUpdateConfig as EnvironmentVariableUpdateConfigParam;
        pub use crate::gaos::types::credentials::EnvironmentVariableUpdateConfig;
        pub use crate::gaos::types::credentials::HTTPBearerConfig as HTTPBearerConfigParam;
        pub use crate::gaos::types::credentials::HTTPBearerConfig;
        pub use crate::gaos::types::credentials::HTTPBearerUpdateConfig as HTTPBearerUpdateConfigParam;
        pub use crate::gaos::types::credentials::HTTPBearerUpdateConfig;
        pub use crate::gaos::types::credentials::InjectionLocationEnum;
        pub use crate::gaos::types::credentials::OAuth2Config as OAuth2ConfigParam;
        pub use crate::gaos::types::credentials::OAuth2Config;
        pub use crate::gaos::types::credentials::OAuth2UpdateConfig as OAuth2UpdateConfigParam;
        pub use crate::gaos::types::credentials::OAuth2UpdateConfig;
        pub use crate::gaos::types::interactions::Empty as CredentialDeleteResponse;
    }
    /// Re-exports for `crate::environments`.
    pub mod environments {
        pub use crate::gaos::models::GetEnvironmentFilesRequest;
        pub use crate::gaos::models::ListEnvironmentsRequest as EnvironmentListParams;
        pub use crate::gaos::resources::environments::Environments;
        pub use crate::gaos::types::environments::CreateEnvironmentRequest as CreateEnvironmentRequestParam;
        pub use crate::gaos::types::environments::CreateEnvironmentRequest as EnvironmentCreateParams;
        pub use crate::gaos::types::environments::CreateEnvironmentRequest;
        pub use crate::gaos::types::environments::CreateEnvironmentRequestNetworkEnum as EnvironmentNetworkEnum;
        pub use crate::gaos::types::environments::CreateEnvironmentRequestNetworkEnum;
        pub use crate::gaos::types::environments::CreateEnvironmentRequestNetworkUnion as EnvironmentNetworkUnion;
        pub use crate::gaos::types::environments::CreateEnvironmentRequestNetworkUnion;
        pub use crate::gaos::types::environments::Environment;
        pub use crate::gaos::types::environments::EnvironmentFile;
        pub use crate::gaos::types::environments::GetEnvironmentFilesResponse;
        pub use crate::gaos::types::environments::ListEnvironmentsResponse as EnvironmentListResponse;
        pub use crate::gaos::types::environments::ListEnvironmentsResponse;
        pub use crate::gaos::types::environments::Status as EnvironmentStatus;
        pub use crate::gaos::types::environments::Status;
        pub use crate::gaos::types::environments::Type as EnvironmentFileType;
        pub use crate::gaos::types::environments::Type;
        pub use crate::gaos::types::interactions::Empty as EnvironmentDeleteResponse;
    }
    /// Re-exports for `crate::interactions`.
    pub mod interactions {
        pub use crate::gaos::models::GetInteractionByIDRequest;
        pub use crate::gaos::models::ListAgentsRequest as AgentListParams;
        pub use crate::gaos::models::ListWebhooksRequest as WebhookListParams;
        pub use crate::gaos::resources::interactions::Interactions;
        pub use crate::gaos::types::agents::Agent as AgentCreateParams;
        pub use crate::gaos::types::agents::Agent;
        pub use crate::gaos::types::agents::AgentListResponse;
        pub use crate::gaos::types::agents::BaseEnvironment as CreateAgentInteractionEnvironment;
        pub use crate::gaos::types::agents::BaseEnvironment as CreateModelInteractionEnvironment;
        pub use crate::gaos::types::agents::BaseEnvironment as InteractionEnvironment;
        pub use crate::gaos::types::environments::CreateEnvironmentRequest as CreateEnvironmentRequestParam;
        pub use crate::gaos::types::environments::CreateEnvironmentRequest;
        pub use crate::gaos::types::environments::CreateEnvironmentRequestNetworkEnum as Disabled;
        pub use crate::gaos::types::environments::CreateEnvironmentRequestNetworkEnum as EnvironmentNetworkEnum;
        pub use crate::gaos::types::environments::CreateEnvironmentRequestNetworkEnum as NetworkEnum;
        pub use crate::gaos::types::environments::CreateEnvironmentRequestNetworkEnum;
        pub use crate::gaos::types::environments::CreateEnvironmentRequestNetworkUnion as EnvironmentNetworkUnion;
        pub use crate::gaos::types::environments::CreateEnvironmentRequestNetworkUnion as Network;
        pub use crate::gaos::types::environments::CreateEnvironmentRequestNetworkUnion;
        pub use crate::gaos::types::environments::Environment as EnvironmentTypedDict;
        pub use crate::gaos::types::environments::EnvironmentFile as EnvironmentFileTypedDict;
        pub use crate::gaos::types::environments::EnvironmentFile;
        pub use crate::gaos::types::environments::GetEnvironmentFilesResponse as GetEnvironmentFilesResponseTypedDict;
        pub use crate::gaos::types::environments::GetEnvironmentFilesResponse;
        pub use crate::gaos::types::environments::ListEnvironmentsResponse as ListEnvironmentsResponseTypedDict;
        pub use crate::gaos::types::environments::ListEnvironmentsResponse;
        pub use crate::gaos::types::environments::Type;
        pub use crate::gaos::types::interactions::AgentOption;
        pub use crate::gaos::types::interactions::AllowedTools as AllowedToolsParam;
        pub use crate::gaos::types::interactions::AllowedTools;
        pub use crate::gaos::types::interactions::Allowlist as AllowlistParam;
        pub use crate::gaos::types::interactions::Allowlist;
        pub use crate::gaos::types::interactions::AllowlistEntry as AllowlistEntryParam;
        pub use crate::gaos::types::interactions::AllowlistEntry;
        pub use crate::gaos::types::interactions::Annotation;
        pub use crate::gaos::types::interactions::AntigravityAgentConfig as AntigravityAgentConfigParam;
        pub use crate::gaos::types::interactions::AntigravityAgentConfig;
        pub use crate::gaos::types::interactions::ArgumentsDelta as ArgumentsDeltaTypedDict;
        pub use crate::gaos::types::interactions::ArgumentsDelta;
        pub use crate::gaos::types::interactions::AudioContent as AudioContentParam;
        pub use crate::gaos::types::interactions::AudioContent;
        pub use crate::gaos::types::interactions::AudioContentMimeType as AudioDeltaMimeType;
        pub use crate::gaos::types::interactions::AudioContentMimeType;
        pub use crate::gaos::types::interactions::AudioDelta as AudioDeltaTypedDict;
        pub use crate::gaos::types::interactions::AudioDelta;
        pub use crate::gaos::types::interactions::AudioResponseFormat as AudioResponseFormatParam;
        pub use crate::gaos::types::interactions::AudioResponseFormat;
        pub use crate::gaos::types::interactions::AudioResponseFormatDelivery as ImageResponseFormatDelivery;
        pub use crate::gaos::types::interactions::AudioResponseFormatDelivery as VideoResponseFormatDelivery;
        pub use crate::gaos::types::interactions::AudioResponseFormatDelivery;
        pub use crate::gaos::types::interactions::AudioResponseFormatMimeType;
        pub use crate::gaos::types::interactions::CodeExecution as CodeExecutionParam;
        pub use crate::gaos::types::interactions::CodeExecution;
        pub use crate::gaos::types::interactions::CodeExecutionCallArguments as CodeExecutionCallArgumentsParam;
        pub use crate::gaos::types::interactions::CodeExecutionCallArguments;
        pub use crate::gaos::types::interactions::CodeExecutionCallDelta as CodeExecutionCallDeltaTypedDict;
        pub use crate::gaos::types::interactions::CodeExecutionCallDelta;
        pub use crate::gaos::types::interactions::CodeExecutionCallStep as CodeExecutionCallStepParam;
        pub use crate::gaos::types::interactions::CodeExecutionCallStep;
        pub use crate::gaos::types::interactions::CodeExecutionResultDelta as CodeExecutionResultDeltaTypedDict;
        pub use crate::gaos::types::interactions::CodeExecutionResultDelta;
        pub use crate::gaos::types::interactions::CodeExecutionResultStep as CodeExecutionResultStepParam;
        pub use crate::gaos::types::interactions::CodeExecutionResultStep;
        pub use crate::gaos::types::interactions::CodeMenderAgentConfig as CodeMenderAgentConfigParam;
        pub use crate::gaos::types::interactions::CodeMenderAgentConfig;
        pub use crate::gaos::types::interactions::ComputerUse as ComputerUseParam;
        pub use crate::gaos::types::interactions::ComputerUse;
        pub use crate::gaos::types::interactions::Content;
        pub use crate::gaos::types::interactions::CreateAgentInteraction as CreateAgentInteractionParam;
        pub use crate::gaos::types::interactions::CreateAgentInteraction;
        pub use crate::gaos::types::interactions::CreateAgentInteractionAgentConfig;
        pub use crate::gaos::types::interactions::CreateAgentInteractionResponseFormat as CreateModelInteractionResponseFormat;
        pub use crate::gaos::types::interactions::CreateAgentInteractionResponseFormat as InteractionResponseFormat;
        pub use crate::gaos::types::interactions::CreateAgentInteractionResponseFormat;
        pub use crate::gaos::types::interactions::CreateInteractionRequestBody;
        pub use crate::gaos::types::interactions::CreateModelInteraction as CreateModelInteractionParam;
        pub use crate::gaos::types::interactions::CreateModelInteraction;
        pub use crate::gaos::types::interactions::DeepResearchAgentConfig as DeepResearchAgentConfigParam;
        pub use crate::gaos::types::interactions::DeepResearchAgentConfig;
        pub use crate::gaos::types::interactions::DisabledSafetyPolicy;
        pub use crate::gaos::types::interactions::DocumentContent as DocumentContentParam;
        pub use crate::gaos::types::interactions::DocumentContent;
        pub use crate::gaos::types::interactions::DocumentContentMimeType as DocumentDeltaMimeType;
        pub use crate::gaos::types::interactions::DocumentContentMimeType;
        pub use crate::gaos::types::interactions::DocumentDelta as DocumentDeltaTypedDict;
        pub use crate::gaos::types::interactions::DocumentDelta;
        pub use crate::gaos::types::interactions::DynamicAgentConfig as DynamicAgentConfigParam;
        pub use crate::gaos::types::interactions::DynamicAgentConfig;
        pub use crate::gaos::types::interactions::Empty as AgentDeleteResponse;
        pub use crate::gaos::types::interactions::Empty as EmptyTypedDict;
        pub use crate::gaos::types::interactions::Empty as InteractionDeleteResponse;
        pub use crate::gaos::types::interactions::Empty as WebhookDeleteResponse;
        pub use crate::gaos::types::interactions::Empty;
        pub use crate::gaos::types::interactions::Env;
        pub use crate::gaos::types::interactions::EnvVar as EnvVarParam;
        pub use crate::gaos::types::interactions::EnvVar;
        pub use crate::gaos::types::interactions::Environment as EnvironmentParam;
        pub use crate::gaos::types::interactions::Environment;
        pub use crate::gaos::types::interactions::EnvironmentEnum;
        pub use crate::gaos::types::interactions::EnvironmentNetworkEgressAllowlist;
        pub use crate::gaos::types::interactions::Error as ErrorTypedDict;
        pub use crate::gaos::types::interactions::Error;
        pub use crate::gaos::types::interactions::ErrorEvent as ErrorEventTypedDict;
        pub use crate::gaos::types::interactions::ErrorEvent;
        pub use crate::gaos::types::interactions::ExaAISearchConfig as ExaAISearchConfigParam;
        pub use crate::gaos::types::interactions::ExaAISearchConfig;
        pub use crate::gaos::types::interactions::FileCitation as FileCitationParam;
        pub use crate::gaos::types::interactions::FileCitation;
        pub use crate::gaos::types::interactions::FileContent as FileContentParam;
        pub use crate::gaos::types::interactions::FileContent;
        pub use crate::gaos::types::interactions::FileSearch as FileSearchParam;
        pub use crate::gaos::types::interactions::FileSearch;
        pub use crate::gaos::types::interactions::FileSearchCallDelta as FileSearchCallDeltaTypedDict;
        pub use crate::gaos::types::interactions::FileSearchCallDelta;
        pub use crate::gaos::types::interactions::FileSearchCallStep as FileSearchCallStepParam;
        pub use crate::gaos::types::interactions::FileSearchCallStep;
        pub use crate::gaos::types::interactions::FileSearchResult as FileSearchResultTypedDict;
        pub use crate::gaos::types::interactions::FileSearchResult;
        pub use crate::gaos::types::interactions::FileSearchResultDelta as FileSearchResultDeltaTypedDict;
        pub use crate::gaos::types::interactions::FileSearchResultDelta;
        pub use crate::gaos::types::interactions::FileSearchResultStep as FileSearchResultStepParam;
        pub use crate::gaos::types::interactions::FileSearchResultStep;
        pub use crate::gaos::types::interactions::Filter as FilterParam;
        pub use crate::gaos::types::interactions::Filter;
        pub use crate::gaos::types::interactions::FindRequest as FindRequestParam;
        pub use crate::gaos::types::interactions::FindRequest;
        pub use crate::gaos::types::interactions::FixRequest as FixRequestParam;
        pub use crate::gaos::types::interactions::FixRequest;
        pub use crate::gaos::types::interactions::Function as FunctionParam;
        pub use crate::gaos::types::interactions::Function;
        pub use crate::gaos::types::interactions::FunctionCallStep as FunctionCallStepParam;
        pub use crate::gaos::types::interactions::FunctionCallStep;
        pub use crate::gaos::types::interactions::FunctionResultDelta as FunctionResultDeltaTypedDict;
        pub use crate::gaos::types::interactions::FunctionResultDelta;
        pub use crate::gaos::types::interactions::FunctionResultDeltaResult as FunctionResultDeltaResultTypedDict;
        pub use crate::gaos::types::interactions::FunctionResultDeltaResult;
        pub use crate::gaos::types::interactions::FunctionResultDeltaResultUnion;
        pub use crate::gaos::types::interactions::FunctionResultStep as FunctionResultStepParam;
        pub use crate::gaos::types::interactions::FunctionResultStep;
        pub use crate::gaos::types::interactions::FunctionResultStepResult as FunctionResultStepResultParam;
        pub use crate::gaos::types::interactions::FunctionResultStepResult;
        pub use crate::gaos::types::interactions::FunctionResultStepResultUnion;
        pub use crate::gaos::types::interactions::FunctionResultSubcontent as ThoughtSummaryContent;
        pub use crate::gaos::types::interactions::FunctionResultSubcontent;
        pub use crate::gaos::types::interactions::GenerationConfig as GenerationConfigParam;
        pub use crate::gaos::types::interactions::GenerationConfig;
        pub use crate::gaos::types::interactions::GoogleMaps as GoogleMapsParam;
        pub use crate::gaos::types::interactions::GoogleMaps;
        pub use crate::gaos::types::interactions::GoogleMapsCallArguments as GoogleMapsCallArgumentsParam;
        pub use crate::gaos::types::interactions::GoogleMapsCallArguments;
        pub use crate::gaos::types::interactions::GoogleMapsCallDelta as GoogleMapsCallDeltaTypedDict;
        pub use crate::gaos::types::interactions::GoogleMapsCallDelta;
        pub use crate::gaos::types::interactions::GoogleMapsCallStep as GoogleMapsCallStepParam;
        pub use crate::gaos::types::interactions::GoogleMapsCallStep;
        pub use crate::gaos::types::interactions::GoogleMapsResult as GoogleMapsResultParam;
        pub use crate::gaos::types::interactions::GoogleMapsResult;
        pub use crate::gaos::types::interactions::GoogleMapsResultDelta as GoogleMapsResultDeltaTypedDict;
        pub use crate::gaos::types::interactions::GoogleMapsResultDelta;
        pub use crate::gaos::types::interactions::GoogleMapsResultPlaces as GoogleMapsResultPlacesParam;
        pub use crate::gaos::types::interactions::GoogleMapsResultPlaces;
        pub use crate::gaos::types::interactions::GoogleMapsResultStep as GoogleMapsResultStepParam;
        pub use crate::gaos::types::interactions::GoogleMapsResultStep;
        pub use crate::gaos::types::interactions::GoogleSearch as GoogleSearchParam;
        pub use crate::gaos::types::interactions::GoogleSearch;
        pub use crate::gaos::types::interactions::GoogleSearchCallArguments as GoogleSearchCallArgumentsParam;
        pub use crate::gaos::types::interactions::GoogleSearchCallArguments;
        pub use crate::gaos::types::interactions::GoogleSearchCallDelta as GoogleSearchCallDeltaTypedDict;
        pub use crate::gaos::types::interactions::GoogleSearchCallDelta;
        pub use crate::gaos::types::interactions::GoogleSearchCallStep as GoogleSearchCallStepParam;
        pub use crate::gaos::types::interactions::GoogleSearchCallStep;
        pub use crate::gaos::types::interactions::GoogleSearchResult as GoogleSearchResultParam;
        pub use crate::gaos::types::interactions::GoogleSearchResult;
        pub use crate::gaos::types::interactions::GoogleSearchResultDelta as GoogleSearchResultDeltaTypedDict;
        pub use crate::gaos::types::interactions::GoogleSearchResultDelta;
        pub use crate::gaos::types::interactions::GoogleSearchResultStep as GoogleSearchResultStepParam;
        pub use crate::gaos::types::interactions::GoogleSearchResultStep;
        pub use crate::gaos::types::interactions::GoogleSearchSearchType as GoogleSearchCallStepSearchType;
        pub use crate::gaos::types::interactions::GoogleSearchSearchType;
        pub use crate::gaos::types::interactions::GroundingToolCount as GroundingToolCountTypedDict;
        pub use crate::gaos::types::interactions::GroundingToolCount;
        pub use crate::gaos::types::interactions::GroundingToolCountType;
        pub use crate::gaos::types::interactions::HarmCategory;
        pub use crate::gaos::types::interactions::HybridSearch as HybridSearchParam;
        pub use crate::gaos::types::interactions::HybridSearch;
        pub use crate::gaos::types::interactions::ImageConfig as ImageConfigParam;
        pub use crate::gaos::types::interactions::ImageConfig;
        pub use crate::gaos::types::interactions::ImageConfigAspectRatio as ImageResponseFormatAspectRatio;
        pub use crate::gaos::types::interactions::ImageConfigAspectRatio;
        pub use crate::gaos::types::interactions::ImageConfigImageSize as ImageResponseFormatImageSize;
        pub use crate::gaos::types::interactions::ImageConfigImageSize;
        pub use crate::gaos::types::interactions::ImageContent as ImageContentParam;
        pub use crate::gaos::types::interactions::ImageContent;
        pub use crate::gaos::types::interactions::ImageContentMimeType as ImageDeltaMimeType;
        pub use crate::gaos::types::interactions::ImageContentMimeType;
        pub use crate::gaos::types::interactions::ImageDelta as ImageDeltaTypedDict;
        pub use crate::gaos::types::interactions::ImageDelta;
        pub use crate::gaos::types::interactions::ImageResponseFormat as ImageResponseFormatParam;
        pub use crate::gaos::types::interactions::ImageResponseFormat;
        pub use crate::gaos::types::interactions::ImageResponseFormatMimeType;
        pub use crate::gaos::types::interactions::Interaction as InteractionTypedDict;
        pub use crate::gaos::types::interactions::Interaction;
        pub use crate::gaos::types::interactions::InteractionAgentConfig;
        pub use crate::gaos::types::interactions::InteractionCompletedEvent as InteractionCompletedEventTypedDict;
        pub use crate::gaos::types::interactions::InteractionCompletedEvent;
        pub use crate::gaos::types::interactions::InteractionCreatedEvent as InteractionCreatedEventTypedDict;
        pub use crate::gaos::types::interactions::InteractionCreatedEvent;
        pub use crate::gaos::types::interactions::InteractionSSEEvent;
        pub use crate::gaos::types::interactions::InteractionSSEStreamEvent as InteractionSSEStreamEventTypedDict;
        pub use crate::gaos::types::interactions::InteractionSSEStreamEvent;
        pub use crate::gaos::types::interactions::InteractionSseEventInteraction as InteractionSseEventInteractionTypedDict;
        pub use crate::gaos::types::interactions::InteractionSseEventInteraction;
        pub use crate::gaos::types::interactions::InteractionSseEventInteractionStatus;
        pub use crate::gaos::types::interactions::InteractionStatus as InteractionStatusUpdateStatus;
        pub use crate::gaos::types::interactions::InteractionStatus;
        pub use crate::gaos::types::interactions::InteractionStatusUpdate as InteractionStatusUpdateTypedDict;
        pub use crate::gaos::types::interactions::InteractionStatusUpdate;
        pub use crate::gaos::types::interactions::InteractionsInput;
        pub use crate::gaos::types::interactions::Language;
        pub use crate::gaos::types::interactions::MCPServer as MCPServerParam;
        pub use crate::gaos::types::interactions::MCPServer;
        pub use crate::gaos::types::interactions::MCPServerToolCallDelta as MCPServerToolCallDeltaTypedDict;
        pub use crate::gaos::types::interactions::MCPServerToolCallDelta;
        pub use crate::gaos::types::interactions::MCPServerToolCallStep as MCPServerToolCallStepParam;
        pub use crate::gaos::types::interactions::MCPServerToolCallStep;
        pub use crate::gaos::types::interactions::MCPServerToolResultDelta as MCPServerToolResultDeltaTypedDict;
        pub use crate::gaos::types::interactions::MCPServerToolResultDelta;
        pub use crate::gaos::types::interactions::MCPServerToolResultDeltaResult as MCPServerToolResultDeltaResultTypedDict;
        pub use crate::gaos::types::interactions::MCPServerToolResultDeltaResult;
        pub use crate::gaos::types::interactions::MCPServerToolResultDeltaResultUnion;
        pub use crate::gaos::types::interactions::MCPServerToolResultStep as MCPServerToolResultStepParam;
        pub use crate::gaos::types::interactions::MCPServerToolResultStep;
        pub use crate::gaos::types::interactions::MCPServerToolResultStepResult as MCPServerToolResultStepResultParam;
        pub use crate::gaos::types::interactions::MCPServerToolResultStepResult;
        pub use crate::gaos::types::interactions::MCPServerToolResultStepResultUnion;
        pub use crate::gaos::types::interactions::MediaResolution;
        pub use crate::gaos::types::interactions::Method;
        pub use crate::gaos::types::interactions::ModalityTokens as ModalityTokensTypedDict;
        pub use crate::gaos::types::interactions::ModalityTokens;
        pub use crate::gaos::types::interactions::Mode;
        pub use crate::gaos::types::interactions::Model as ModelParam;
        pub use crate::gaos::types::interactions::Model;
        pub use crate::gaos::types::interactions::ModelOutputStep as ModelOutputStepParam;
        pub use crate::gaos::types::interactions::ModelOutputStep;
        pub use crate::gaos::types::interactions::ParallelAISearchConfig as ParallelAISearchConfigParam;
        pub use crate::gaos::types::interactions::ParallelAISearchConfig;
        pub use crate::gaos::types::interactions::PlaceCitation as PlaceCitationParam;
        pub use crate::gaos::types::interactions::PlaceCitation;
        pub use crate::gaos::types::interactions::Processing;
        pub use crate::gaos::types::interactions::ProcessingCallDelta as ProcessingCallDeltaTypedDict;
        pub use crate::gaos::types::interactions::ProcessingCallDelta;
        pub use crate::gaos::types::interactions::ProcessingCallStep as ProcessingCallStepParam;
        pub use crate::gaos::types::interactions::ProcessingCallStep;
        pub use crate::gaos::types::interactions::ProcessingEnum;
        pub use crate::gaos::types::interactions::ProcessingResultDelta as ProcessingResultDeltaTypedDict;
        pub use crate::gaos::types::interactions::ProcessingResultDelta;
        pub use crate::gaos::types::interactions::ProcessingResultStep as ProcessingResultStepParam;
        pub use crate::gaos::types::interactions::ProcessingResultStep;
        pub use crate::gaos::types::interactions::RagResource as RagResourceParam;
        pub use crate::gaos::types::interactions::RagResource;
        pub use crate::gaos::types::interactions::RagRetrievalConfig as RagRetrievalConfigParam;
        pub use crate::gaos::types::interactions::RagRetrievalConfig;
        pub use crate::gaos::types::interactions::RagStoreConfig as RagStoreConfigParam;
        pub use crate::gaos::types::interactions::RagStoreConfig;
        pub use crate::gaos::types::interactions::RankService as RankServiceParam;
        pub use crate::gaos::types::interactions::RankService;
        pub use crate::gaos::types::interactions::Ranking as RankingParam;
        pub use crate::gaos::types::interactions::Ranking;
        pub use crate::gaos::types::interactions::Resolution;
        pub use crate::gaos::types::interactions::ResponseFormat;
        pub use crate::gaos::types::interactions::ResponseModality;
        pub use crate::gaos::types::interactions::Retrieval as RetrievalParam;
        pub use crate::gaos::types::interactions::Retrieval;
        pub use crate::gaos::types::interactions::RetrievalCallArguments as RetrievalCallArgumentsParam;
        pub use crate::gaos::types::interactions::RetrievalCallArguments;
        pub use crate::gaos::types::interactions::RetrievalCallDelta as RetrievalCallDeltaTypedDict;
        pub use crate::gaos::types::interactions::RetrievalCallDelta;
        pub use crate::gaos::types::interactions::RetrievalCallStep as RetrievalCallStepParam;
        pub use crate::gaos::types::interactions::RetrievalCallStep;
        pub use crate::gaos::types::interactions::RetrievalResultDelta as RetrievalResultDeltaTypedDict;
        pub use crate::gaos::types::interactions::RetrievalResultDelta;
        pub use crate::gaos::types::interactions::RetrievalResultStep as RetrievalResultStepParam;
        pub use crate::gaos::types::interactions::RetrievalResultStep;
        pub use crate::gaos::types::interactions::RetrievalRetrievalType as RetrievalCallDeltaRetrievalType;
        pub use crate::gaos::types::interactions::RetrievalRetrievalType as RetrievalCallStepRetrievalType;
        pub use crate::gaos::types::interactions::RetrievalRetrievalType;
        pub use crate::gaos::types::interactions::ReviewSnippet as ReviewSnippetParam;
        pub use crate::gaos::types::interactions::ReviewSnippet;
        pub use crate::gaos::types::interactions::SafetySetting as SafetySettingParam;
        pub use crate::gaos::types::interactions::SafetySetting;
        pub use crate::gaos::types::interactions::ServiceTier;
        pub use crate::gaos::types::interactions::SessionConfig as SessionConfigParam;
        pub use crate::gaos::types::interactions::SessionConfig;
        pub use crate::gaos::types::interactions::SmartTranscriptionMode as SmartTranscriptionModeParam;
        pub use crate::gaos::types::interactions::SmartTranscriptionMode;
        pub use crate::gaos::types::interactions::Source as SourceParam;
        pub use crate::gaos::types::interactions::Source;
        pub use crate::gaos::types::interactions::SourceType;
        pub use crate::gaos::types::interactions::SpeakerConfig as SpeakerConfigParam;
        pub use crate::gaos::types::interactions::SpeakerConfig;
        pub use crate::gaos::types::interactions::SpeechAnnotation as SpeechAnnotationParam;
        pub use crate::gaos::types::interactions::SpeechAnnotation;
        pub use crate::gaos::types::interactions::SpeechConfig as SpeechConfigParam;
        pub use crate::gaos::types::interactions::SpeechConfig;
        pub use crate::gaos::types::interactions::SpeechConfigUnion;
        pub use crate::gaos::types::interactions::StaticMediaProcessing as MediaProcessing;
        pub use crate::gaos::types::interactions::StaticMediaProcessing as MediaProcessingParam;
        pub use crate::gaos::types::interactions::StaticMediaProcessing as StaticMediaProcessingParam;
        pub use crate::gaos::types::interactions::StaticMediaProcessing;
        pub use crate::gaos::types::interactions::Status as StatusParam;
        pub use crate::gaos::types::interactions::Status;
        pub use crate::gaos::types::interactions::Step;
        pub use crate::gaos::types::interactions::StepDelta as StepDeltaTypedDict;
        pub use crate::gaos::types::interactions::StepDelta;
        pub use crate::gaos::types::interactions::StepDeltaData;
        pub use crate::gaos::types::interactions::StepDeltaMetadata as StepDeltaMetadataTypedDict;
        pub use crate::gaos::types::interactions::StepDeltaMetadata;
        pub use crate::gaos::types::interactions::StepStart as StepStartTypedDict;
        pub use crate::gaos::types::interactions::StepStart;
        pub use crate::gaos::types::interactions::StepStop as StepStopTypedDict;
        pub use crate::gaos::types::interactions::StepStop;
        pub use crate::gaos::types::interactions::Task;
        pub use crate::gaos::types::interactions::TextAnnotationDelta as TextAnnotationDeltaTypedDict;
        pub use crate::gaos::types::interactions::TextAnnotationDelta;
        pub use crate::gaos::types::interactions::TextContent as TextContentParam;
        pub use crate::gaos::types::interactions::TextContent;
        pub use crate::gaos::types::interactions::TextDelta as TextDeltaTypedDict;
        pub use crate::gaos::types::interactions::TextDelta;
        pub use crate::gaos::types::interactions::TextResponseFormat as TextResponseFormatParam;
        pub use crate::gaos::types::interactions::TextResponseFormat;
        pub use crate::gaos::types::interactions::TextResponseFormatMimeType;
        pub use crate::gaos::types::interactions::ThinkingLevel;
        pub use crate::gaos::types::interactions::ThinkingSummaries;
        pub use crate::gaos::types::interactions::ThoughtSignatureDelta as ThoughtSignatureDeltaTypedDict;
        pub use crate::gaos::types::interactions::ThoughtSignatureDelta;
        pub use crate::gaos::types::interactions::ThoughtStep as ThoughtStepParam;
        pub use crate::gaos::types::interactions::ThoughtStep;
        pub use crate::gaos::types::interactions::ThoughtSummaryDelta as ThoughtSummaryDeltaTypedDict;
        pub use crate::gaos::types::interactions::ThoughtSummaryDelta;
        pub use crate::gaos::types::interactions::Threshold;
        pub use crate::gaos::types::interactions::Tool;
        pub use crate::gaos::types::interactions::ToolChoice;
        pub use crate::gaos::types::interactions::ToolChoiceConfig as ToolChoiceConfigParam;
        pub use crate::gaos::types::interactions::ToolChoiceConfig;
        pub use crate::gaos::types::interactions::ToolChoiceType;
        pub use crate::gaos::types::interactions::TranscriptionConfig as TranscriptionConfigParam;
        pub use crate::gaos::types::interactions::TranscriptionConfig;
        pub use crate::gaos::types::interactions::TranscriptionConfigMode;
        pub use crate::gaos::types::interactions::TranscriptionConfigModeEnum;
        pub use crate::gaos::types::interactions::TranscriptionMode;
        pub use crate::gaos::types::interactions::Transform as TransformParam;
        pub use crate::gaos::types::interactions::Transform;
        pub use crate::gaos::types::interactions::URLCitation as URLCitationParam;
        pub use crate::gaos::types::interactions::URLCitation;
        pub use crate::gaos::types::interactions::URLContext as URLContextParam;
        pub use crate::gaos::types::interactions::URLContext;
        pub use crate::gaos::types::interactions::URLContextCallArguments as URLContextCallArgumentsParam;
        pub use crate::gaos::types::interactions::URLContextCallArguments;
        pub use crate::gaos::types::interactions::URLContextCallDelta as URLContextCallDeltaTypedDict;
        pub use crate::gaos::types::interactions::URLContextCallDelta;
        pub use crate::gaos::types::interactions::URLContextCallStep as URLContextCallStepParam;
        pub use crate::gaos::types::interactions::URLContextCallStep;
        pub use crate::gaos::types::interactions::URLContextResult as URLContextResultParam;
        pub use crate::gaos::types::interactions::URLContextResult;
        pub use crate::gaos::types::interactions::URLContextResultDelta as URLContextResultDeltaTypedDict;
        pub use crate::gaos::types::interactions::URLContextResultDelta;
        pub use crate::gaos::types::interactions::URLContextResultStatus;
        pub use crate::gaos::types::interactions::URLContextResultStep as URLContextResultStepParam;
        pub use crate::gaos::types::interactions::URLContextResultStep;
        pub use crate::gaos::types::interactions::Usage as UsageTypedDict;
        pub use crate::gaos::types::interactions::Usage;
        pub use crate::gaos::types::interactions::UserInputStep as UserInputStepParam;
        pub use crate::gaos::types::interactions::UserInputStep;
        pub use crate::gaos::types::interactions::VerbatimTranscriptionMode as VerbatimTranscriptionModeParam;
        pub use crate::gaos::types::interactions::VerbatimTranscriptionMode;
        pub use crate::gaos::types::interactions::VertexAISearchConfig as VertexAISearchConfigParam;
        pub use crate::gaos::types::interactions::VertexAISearchConfig;
        pub use crate::gaos::types::interactions::VideoConfig as VideoConfigParam;
        pub use crate::gaos::types::interactions::VideoConfig;
        pub use crate::gaos::types::interactions::VideoContent as VideoContentParam;
        pub use crate::gaos::types::interactions::VideoContent;
        pub use crate::gaos::types::interactions::VideoContentMimeType;
        pub use crate::gaos::types::interactions::VideoDelta as VideoDeltaTypedDict;
        pub use crate::gaos::types::interactions::VideoDelta;
        pub use crate::gaos::types::interactions::VideoDeltaMimeType;
        pub use crate::gaos::types::interactions::VideoResponseFormat as VideoResponseFormatParam;
        pub use crate::gaos::types::interactions::VideoResponseFormat;
        pub use crate::gaos::types::interactions::VideoResponseFormatAspectRatio;
        pub use crate::gaos::types::interactions::Visualization;
        pub use crate::gaos::types::interactions::WebhookConfig as WebhookConfigParam;
        pub use crate::gaos::types::interactions::WebhookConfig;
        pub use crate::gaos::types::interactions::WordInfo as WordInfoParam;
        pub use crate::gaos::types::interactions::WordInfo;
        pub use crate::gaos::types::triggers::ListTriggerExecutionsResponse as ListTriggerExecutionsResponseTypedDict;
        pub use crate::gaos::types::triggers::ListTriggerExecutionsResponse;
        pub use crate::gaos::types::triggers::ListTriggersResponse as ListTriggersResponseTypedDict;
        pub use crate::gaos::types::triggers::ListTriggersResponse;
        pub use crate::gaos::types::triggers::Trigger as TriggerTypedDict;
        pub use crate::gaos::types::triggers::Trigger;
        pub use crate::gaos::types::triggers::TriggerCreateParams as TriggerCreateParamsParam;
        pub use crate::gaos::types::triggers::TriggerCreateParams;
        pub use crate::gaos::types::triggers::TriggerExecution as TriggerExecutionTypedDict;
        pub use crate::gaos::types::triggers::TriggerExecution;
        pub use crate::gaos::types::triggers::TriggerExecutionStatus;
        pub use crate::gaos::types::triggers::TriggerStatus as TriggerUpdateStatus;
        pub use crate::gaos::types::triggers::TriggerStatus;
        pub use crate::gaos::types::triggers::TriggerUpdate as TriggerUpdateParam;
        pub use crate::gaos::types::triggers::TriggerUpdate;
        pub use crate::gaos::types::webhooks::PingWebhookRequest as WebhookPingParams;
        pub use crate::gaos::types::webhooks::RotateSigningSecretRequest as WebhookRotateSigningSecretParams;
        pub use crate::gaos::types::webhooks::SigningSecret;
        pub use crate::gaos::types::webhooks::Webhook;
        pub use crate::gaos::types::webhooks::WebhookInput as WebhookCreateParams;
        pub use crate::gaos::types::webhooks::WebhookListResponse;
        pub use crate::gaos::types::webhooks::WebhookPingResponse;
        pub use crate::gaos::types::webhooks::WebhookUpdate as WebhookUpdateParams;
    }
    /// Re-exports for `crate::triggers`.
    pub mod triggers {
        pub use crate::gaos::models::ListTriggerExecutionsRequest as TriggerListExecutionsParams;
        pub use crate::gaos::models::ListTriggersRequest as TriggerListParams;
        pub use crate::gaos::resources::triggers::Triggers;
        pub use crate::gaos::types::interactions::Empty as TriggerDeleteResponse;
        pub use crate::gaos::types::triggers::ListTriggerExecutionsResponse as TriggerListExecutionsResponse;
        pub use crate::gaos::types::triggers::ListTriggerExecutionsResponse;
        pub use crate::gaos::types::triggers::ListTriggersResponse as TriggerListResponse;
        pub use crate::gaos::types::triggers::ListTriggersResponse;
        pub use crate::gaos::types::triggers::Trigger;
        pub use crate::gaos::types::triggers::TriggerCreateParams as TriggerCreateParamsParam;
        pub use crate::gaos::types::triggers::TriggerCreateParams;
        pub use crate::gaos::types::triggers::TriggerExecution;
        pub use crate::gaos::types::triggers::TriggerExecutionStatus;
        pub use crate::gaos::types::triggers::TriggerStatus as TriggerUpdateStatus;
        pub use crate::gaos::types::triggers::TriggerStatus;
        pub use crate::gaos::types::triggers::TriggerUpdate as TriggerUpdateParam;
        pub use crate::gaos::types::triggers::TriggerUpdate as TriggerUpdateParams;
        pub use crate::gaos::types::triggers::TriggerUpdate;
    }
    /// Re-exports for `crate::voices`.
    pub mod voices {
        pub use crate::gaos::models::ListVoicesRequest as VoiceListParams;
        pub use crate::gaos::resources::voices::Voices;
        pub use crate::gaos::types::voices::CreateVoiceRequest as VoiceCreateParams;
        pub use crate::gaos::types::voices::DeleteVoiceResponse as VoiceDeleteResponse;
        pub use crate::gaos::types::voices::ListVoicesResponse as VoiceListResponse;
        pub use crate::gaos::types::voices::VoiceOutput as Voice;
    }
    /// Re-exports for `crate::webhooks`.
    pub mod webhooks {
        pub use crate::gaos::models::ListWebhooksRequest as WebhookListParams;
        pub use crate::gaos::models::UpdateWebhookRequest;
        pub use crate::gaos::resources::webhooks::Webhooks;
        pub use crate::gaos::types::interactions::Empty as WebhookDeleteResponse;
        pub use crate::gaos::types::webhooks::PingWebhookRequest as PingWebhookRequestParam;
        pub use crate::gaos::types::webhooks::PingWebhookRequest as WebhookPingParams;
        pub use crate::gaos::types::webhooks::PingWebhookRequest;
        pub use crate::gaos::types::webhooks::RevocationBehavior;
        pub use crate::gaos::types::webhooks::RotateSigningSecretRequest as RotateSigningSecretRequestParam;
        pub use crate::gaos::types::webhooks::RotateSigningSecretRequest as WebhookRotateSigningSecretParams;
        pub use crate::gaos::types::webhooks::RotateSigningSecretRequest;
        pub use crate::gaos::types::webhooks::SigningSecret;
        pub use crate::gaos::types::webhooks::Webhook;
        pub use crate::gaos::types::webhooks::WebhookInput as WebhookCreateParams;
        pub use crate::gaos::types::webhooks::WebhookInput as WebhookInputParam;
        pub use crate::gaos::types::webhooks::WebhookInput;
        pub use crate::gaos::types::webhooks::WebhookListResponse;
        pub use crate::gaos::types::webhooks::WebhookPingResponse;
        pub use crate::gaos::types::webhooks::WebhookRotateSigningSecretResponse;
        pub use crate::gaos::types::webhooks::WebhookState as WebhookUpdateState;
        pub use crate::gaos::types::webhooks::WebhookState;
        pub use crate::gaos::types::webhooks::WebhookSubscribedEvent as WebhookUpdateSubscribedEvent;
        pub use crate::gaos::types::webhooks::WebhookSubscribedEvent;
        pub use crate::gaos::types::webhooks::WebhookUpdate as WebhookUpdateParam;
        pub use crate::gaos::types::webhooks::WebhookUpdate as WebhookUpdateParams;
        pub use crate::gaos::types::webhooks::WebhookUpdate;
    }
}
