// @generated by tools/codegen/gen_gaos.py from google-genai 2.28.0. DO NOT EDIT.
//
// SPDX-FileCopyrightText: 2025 Google LLC
// SPDX-FileCopyrightText: 2026 Daisuke ITO
// SPDX-License-Identifier: Apache-2.0
//
// Derived from the Google Gen AI Python SDK (google-genai 2.28.0),
// https://github.com/googleapis/python-genai
// Copyright 2025 Google LLC, licensed under the Apache License, Version 2.0.
//
// Modified: mechanically derived from the Python SDK's internal `_gaos` sub-SDK by gen_gaos.py:
// model fields, string enums and unions were reflected into Rust types, and HTTP
// operations were extracted from the resource classes. Doc comments reproduce the
// upstream Python docstrings.
//
// See the NOTICE file at the repository root for the full attribution.
//
// Edit tools/codegen/gen_gaos.py (or tools/codegen/gaos_overrides.toml) and re-run
// `python tools/codegen/generate.py --only gaos` instead.

//! Query-parameter structs of the `_gaos` operations (one per upstream
//! `models.<Operation>Request` that carries query parameters). Path
//! parameters and the request body are separate method arguments.

#![allow(
    clippy::pedantic,
    clippy::large_enum_variant,
    clippy::enum_variant_names,
    dead_code,
    rustdoc::bare_urls,
    reason = "mechanically generated port of the google-genai `_gaos` sub-SDK; pedantic-tier style lints, size-based enum lints and bare-URL doc warnings do not apply to a generated public API surface whose doc comments are verbatim Python docstrings"
)]

/// Query parameters of `environments.files.list` (upstream `GetEnvironmentFilesRequest`).
#[derive(Debug, Clone, PartialEq, Default)]
pub struct GetEnvironmentFilesRequest {
    /// `page_size`.
    pub page_size: Option<i64>,
    /// `page_token`.
    pub page_token: Option<String>,
    /// `recursive`.
    pub recursive: Option<bool>,
}

/// Query parameters of `interactions.get` (upstream `GetInteractionByIDRequest`).
#[derive(Debug, Clone, PartialEq, Default)]
pub struct GetInteractionByIDRequest {
    /// `include_input`.
    pub include_input: Option<bool>,
    /// `last_event_id`.
    pub last_event_id: Option<String>,
    /// `stream`.
    pub stream: Option<bool>,
}

/// Query parameters of `agents.list` (upstream `ListAgentsRequest`).
#[derive(Debug, Clone, PartialEq, Default)]
pub struct ListAgentsRequest {
    /// `page_size`.
    pub page_size: Option<i64>,
    /// `page_token`.
    pub page_token: Option<String>,
    /// `parent`.
    pub parent: Option<String>,
}

/// Query parameters of `credentials.list` (upstream `ListCredentialsRequest`).
#[derive(Debug, Clone, PartialEq, Default)]
pub struct ListCredentialsRequest {
    /// `page_size`.
    pub page_size: Option<i64>,
    /// `page_token`.
    pub page_token: Option<String>,
}

/// Query parameters of `environments.list_environments` (upstream `ListEnvironmentsRequest`).
#[derive(Debug, Clone, PartialEq, Default)]
pub struct ListEnvironmentsRequest {
    /// `page_size`.
    pub page_size: Option<i64>,
    /// `page_token`.
    pub page_token: Option<String>,
}

/// Query parameters of `triggers.list_executions` (upstream `ListTriggerExecutionsRequest`).
#[derive(Debug, Clone, PartialEq, Default)]
pub struct ListTriggerExecutionsRequest {
    /// `page_size`.
    pub page_size: Option<i64>,
    /// `page_token`.
    pub page_token: Option<String>,
}

/// Query parameters of `triggers.list` (upstream `ListTriggersRequest`).
#[derive(Debug, Clone, PartialEq, Default)]
pub struct ListTriggersRequest {
    /// `filter_`.
    pub filter: Option<String>,
    /// `page_size`.
    pub page_size: Option<i64>,
    /// `page_token`.
    pub page_token: Option<String>,
}

/// Query parameters of `voices.list` (upstream `ListVoicesRequest`).
#[derive(Debug, Clone, PartialEq, Default)]
pub struct ListVoicesRequest {
    /// `accent`.
    pub accent: Option<Vec<String>>,
    /// `contexts`.
    pub contexts: Option<Vec<String>>,
    /// `gender`.
    pub gender: Option<Vec<String>>,
    /// `language_code`.
    pub language_code: Option<Vec<String>>,
    /// `page_size`.
    pub page_size: Option<i64>,
    /// `page_token`.
    pub page_token: Option<String>,
    /// `persona`.
    pub persona: Option<Vec<String>>,
    /// `pitch`.
    pub pitch: Option<Vec<String>>,
    /// `region_code`.
    pub region_code: Option<Vec<String>>,
    /// `search`.
    pub search: Option<String>,
    /// `type`.
    pub r#type: Option<Vec<String>>,
}

/// Query parameters of `webhooks.list` (upstream `ListWebhooksRequest`).
#[derive(Debug, Clone, PartialEq, Default)]
pub struct ListWebhooksRequest {
    /// `page_size`.
    pub page_size: Option<i64>,
    /// `page_token`.
    pub page_token: Option<String>,
}

/// Query parameters of `credentials.update` (upstream `UpdateCredentialRequest`).
#[derive(Debug, Clone, PartialEq, Default)]
pub struct UpdateCredentialRequest {
    /// `update_mask`.
    pub update_mask: Option<String>,
}

/// Query parameters of `webhooks.update` (upstream `UpdateWebhookRequest`).
#[derive(Debug, Clone, PartialEq, Default)]
pub struct UpdateWebhookRequest {
    /// `update_mask`.
    pub update_mask: Option<String>,
}
