"""Single source of truth for the upstream attribution stamped into every
generated file.

The generated Rust modules, `docs/parity.md`, and the converter fixtures are
derived works of the Google Gen AI Python SDK: the converter functions are a
1:1 mechanical transpilation of its `_to_mldev` / `_from_mldev` helpers, and
the doc comments on the generated types reproduce its Python docstrings
verbatim. Section 4(b) and 4(c) of the Apache License, Version 2.0 therefore
require every one of those files to carry the upstream copyright notice and a
statement of what was changed.

Keeping that wording in one place matters for the same reason `upstream.py`
keeps the pinned version in one place: five generators each assembling their
own attribution string would drift, and a drifted notice is worse than none --
it asserts something about provenance that is no longer true.

## What lives where

- `rust_attribution()` -- the `//`-comment block for generated Rust sources.
- `html_attribution()` -- the same content for HTML comments (`docs/parity.md`
  and its Japanese twin).
- `fixtures_readme()` -- the whole `tests/fixtures/converters/README.md`. JSON
  cannot carry comments and the fixtures are golden-compared byte for byte, so
  the attribution for those 197 files is stated once for the directory instead.

Each generator keeps its own `// @generated by ... DO NOT EDIT.` first line and
its own "edit the generator instead" guidance; this module supplies only the
attribution block that sits between them.

The upstream version is always passed in by the caller (which gets it from
`upstream.assert_supported_version()`), never hard-coded here -- a header
claiming a version the interpreter did not actually generate from is the exact
failure `upstream.py` exists to prevent.
"""

from __future__ import annotations

# --- the two copyright holders --------------------------------------------
#
# `PROJECT_*` describes this port; `UPSTREAM_*` describes the work it is
# derived from. Both appear in every generated file: the upstream notice
# because Apache-2.0 section 4(c) requires retaining it, ours because the
# translation itself is a copyrightable contribution.

UPSTREAM_NAME = "google-genai"
UPSTREAM_URL = "https://github.com/googleapis/python-genai"
UPSTREAM_COPYRIGHT = "2025 Google LLC"

PROJECT_NAME = "gemini-genai"
PROJECT_COPYRIGHT = "2026 Daisuke ITO"

LICENSE_ID = "Apache-2.0"
LICENSE_NAME = "Apache License, Version 2.0"

# Default statement of change for files that are a direct Python-to-Rust
# transpilation. Generators whose output is derived less directly (for example
# `gen_blocking.py`, which works from `methods.toml`) pass their own.
_DEFAULT_MODIFIED = (
    "mechanically translated from Python to Rust by {generator}.\n"
    "Doc comments reproduce the upstream Python docstrings verbatim."
)


def _lines(generator: str, upstream_version: str, modified: str | None) -> list[str]:
    """Returns the attribution as bare text lines, without comment syntax.

    Both `rust_attribution` and `html_attribution` render these; keeping the
    content in one place is what stops the two comment styles from drifting.
    """
    statement = (modified or _DEFAULT_MODIFIED).format(generator=generator)
    first, *rest = statement.split("\n")
    return [
        "",
        f"SPDX-FileCopyrightText: {UPSTREAM_COPYRIGHT}",
        f"SPDX-FileCopyrightText: {PROJECT_COPYRIGHT}",
        f"SPDX-License-Identifier: {LICENSE_ID}",
        "",
        f"Derived from the Google Gen AI Python SDK ({UPSTREAM_NAME} {upstream_version}),",
        UPSTREAM_URL,
        f"Copyright {UPSTREAM_COPYRIGHT}, licensed under the {LICENSE_NAME}.",
        "",
        f"Modified: {first}",
        *rest,
        "",
        "See the NOTICE file at the repository root for the full attribution.",
        "",
    ]


def rust_attribution(
    generator: str,
    upstream_version: str,
    modified: str | None = None,
) -> str:
    """Returns the `//`-comment attribution block for a generated Rust file.

    Sits between the generator's `// @generated ...` first line and its
    "edit the generator instead" guidance. Ends with a newline, so callers
    concatenate without adding one.
    """
    return "".join(
        f"//{' ' + line if line else ''}\n" for line in _lines(generator, upstream_version, modified)
    )


def html_attribution(
    generator: str,
    upstream_version: str,
    indent: str = "     ",
    modified: str | None = None,
) -> str:
    """Returns the attribution block for use inside an HTML comment.

    `indent` is the prefix aligning continuation lines under the opening
    `<!-- `; the caller owns the `<!--` and `-->` delimiters.
    """
    return "".join(
        (f"{indent}{line}\n" if line else "\n")
        for line in _lines(generator, upstream_version, modified)
    )


def fixtures_readme(generator: str, upstream_version: str) -> str:
    """Returns the whole `tests/fixtures/converters/README.md`.

    The fixtures are JSON, which has no comment syntax, and they are compared
    byte for byte by `tests/converters_golden.rs` -- adding an attribution key
    to each file would pollute the very values under test. Stating the
    attribution once for the directory keeps the fixtures untouched.
    """
    return f"""<!-- @generated by tools/codegen/{generator} from {UPSTREAM_NAME} {upstream_version}. DO NOT EDIT.
     Edit tools/codegen/{generator} (or tools/codegen/fixtures_cases.py) and re-run
     `python tools/codegen/generate.py --only fixtures` instead. -->

# Converter golden fixtures

SPDX-FileCopyrightText: {UPSTREAM_COPYRIGHT}
SPDX-FileCopyrightText: {PROJECT_COPYRIGHT}
SPDX-License-Identifier: {LICENSE_ID}

Every `**/*.json` file under this directory records the input and output of a
`_to_mldev` / `_from_mldev` converter as the Google Gen AI Python SDK
({UPSTREAM_NAME} {upstream_version}, <{UPSTREAM_URL}>,
Copyright {UPSTREAM_COPYRIGHT}, {LICENSE_NAME}) actually computes it. They are
derived from that work.

Modified: the upstream Python converters were executed and their inputs and
outputs serialised to JSON, so that `tests/converters_golden.rs` can assert the
Rust port produces byte-identical results. No upstream source code is
reproduced here.

JSON cannot carry comments, and `tests/converters_golden.rs` compares these
files byte for byte -- embedding an attribution key in each one would pollute
the values under test. The attribution is therefore stated once, here, for the
whole directory. The fixture files themselves are exactly what the generator
emitted.

Regenerate with `python tools/codegen/generate.py --only fixtures`.

See the NOTICE file at the repository root for the full attribution.
"""
