#!/usr/bin/env python3
"""Generates the `_gaos` surface (Interactions, agents, environments, triggers,
webhooks, voices, credentials) from the installed `google-genai` package.

Inputs
    - reflection over every pydantic model under `google.genai._gaos.types`
      and `google.genai._gaos.models` (field list, aliases, discriminated and
      open unions, string enums written as `Literal[...]`);
    - the AST of `_gaos/<resource>.py` (HTTP verb, path template, operation id,
      stream capability, response type) cross-checked against the request
      model of the same operation (path / query / body field classification);
    - `tools/codegen/gaos_overrides.toml` (renames and the recorded list of
      fields that cannot be mapped).

Outputs (all start with the `@generated` header)
    - `src/gaos/{mod,types,models}.rs`
    - `src/gaos/resources/{agents,credentials,environments,interactions,
      triggers,voices,webhooks}.rs` and `resources/mod.rs`
    - `tests/fixtures/gaos/*.json` (+ README carrying the attribution),
      `tests/gaos/generated_ops.rs`
    - `tools/codegen/methods_gaos.toml` (read by `gen_blocking.py` and
      `gen_parity.py`)

See specs/008-python-genai-rust-conformance/contracts/gaos-generation.md.
DO NOT hand-edit the generated output; edit this script or
`gaos_overrides.toml` and re-run `generate.py --only gaos` instead.
"""

from __future__ import annotations

import ast
import dataclasses
import datetime
import enum
import functools
import importlib
import inspect
import json
import pathlib
import pkgutil
import re
import sys
import types as pytypes
import typing

import pydantic
import typing_extensions
from pydantic.fields import FieldInfo

import google.genai
from google.genai import _gaos

import attribution
import gen_types
import upstream

try:
    import tomllib
except ModuleNotFoundError:  # pragma: no cover - Python < 3.11
    import tomli as tomllib  # type: ignore[no-redef]

GENAI_VERSION = upstream.assert_supported_version()

REPO_ROOT = pathlib.Path(__file__).resolve().parents[2]
CODEGEN_DIR = pathlib.Path(__file__).resolve().parent
GAOS_SRC_DIR = pathlib.Path(_gaos.__file__).resolve().parent
OUT_SRC = REPO_ROOT / "src" / "gaos"
OUT_RESOURCES = OUT_SRC / "resources"
OUT_FIXTURES = REPO_ROOT / "tests" / "fixtures" / "gaos"
OUT_TESTS = REPO_ROOT / "tests" / "gaos"
OVERRIDES_TOML = CODEGEN_DIR / "gaos_overrides.toml"
METHODS_GAOS_TOML = CODEGEN_DIR / "methods_gaos.toml"

TYPES_PKG = "google.genai._gaos.types"
MODELS_PKG = "google.genai._gaos.models"

# Upper bound on fields that fall back to `serde_json::Value`
# (contracts/gaos-generation.md; T061).
UNMAPPED_LIMIT = 60

# The seven public resources: Python module (public re-export module),
# (source file under `_gaos/`, sync class name, method-name prefix) tuples.
# `environments` also owns the nested `files` sub-SDK.
RESOURCES: dict[str, list[tuple[str, str, str]]] = {
    "agents": [("agents.py", "Agents", "")],
    "credentials": [("credentials.py", "Credentials", "")],
    "environments": [("environments.py", "Environments", ""), ("files.py", "Files", "files_")],
    "interactions": [("interactions.py", "Interactions", "")],
    "triggers": [("triggers.py", "Triggers", "")],
    "voices": [("voices.py", "Voices", "")],
    "webhooks": [("webhooks.py", "Webhooks", "")],
}

# Methods of the sync classes that are accessors, not API operations.
NON_OPERATION_METHODS = {"with_raw_response", "with_streaming_response", "__init__", "_init_sdks"}

# Rust keywords that cannot be raw identifiers.
RUST_UNRAWABLE = {"self", "Self", "super", "crate", "extern"}

NONE_TYPE = type(None)
ALIAS_TYPES: tuple[type, ...] = tuple(
    {getattr(typing, "TypeAliasType", None), getattr(typing_extensions, "TypeAliasType", None)} - {None}
)

# --- header -----------------------------------------------------------------

_MODIFIED = (
    "mechanically derived from the Python SDK's internal `_gaos` sub-SDK by {generator}:\n"
    "model fields, string enums and unions were reflected into Rust types, and HTTP\n"
    "operations were extracted from the resource classes. Doc comments reproduce the\n"
    "upstream Python docstrings."
)


def header(rust: bool = True) -> str:
    del rust
    return (
        f"// @generated by tools/codegen/gen_gaos.py from google-genai {GENAI_VERSION}. DO NOT EDIT.\n"
        + attribution.rust_attribution("gen_gaos.py", GENAI_VERSION, modified=_MODIFIED)
        + "// Edit tools/codegen/gen_gaos.py (or tools/codegen/gaos_overrides.toml) and re-run\n"
        "// `python tools/codegen/generate.py --only gaos` instead.\n\n"
    )


ALLOW_ATTR = (
    "#![allow(\n"
    "    clippy::pedantic,\n"
    "    clippy::large_enum_variant,\n"
    "    clippy::enum_variant_names,\n"
    "    dead_code,\n"
    "    rustdoc::bare_urls,\n"
    '    reason = "mechanically generated port of the google-genai `_gaos` sub-SDK; pedantic-tier style lints, '
    'size-based enum lints and bare-URL doc warnings do not apply to a generated public API surface whose doc '
    'comments are verbatim Python docstrings"\n'
    ")]\n\n"
)

# --- small helpers ----------------------------------------------------------


def pascal(text: str) -> str:
    parts = [p for p in re.split(r"[^0-9A-Za-z]+", text) if p]
    return "".join(p[:1].upper() + p[1:] for p in parts)


def snake(text: str) -> str:
    text = re.sub(r"(?<=[a-z0-9])(?=[A-Z])", "_", text)
    text = re.sub(r"(?<=[A-Z])(?=[A-Z][a-z])", "_", text)
    return text.lower()


def rust_ident(name: str) -> str:
    name = name.rstrip("_") or name
    if name in RUST_UNRAWABLE:
        return f"{name}_"
    if name in RUST_KEYWORDS:
        return f"r#{name}"
    return name


RUST_PRELUDE_NAMES = {"Option", "Result", "Vec", "String", "Box", "Default", "Some", "None", "Ok", "Err", "Self"}

RUST_KEYWORDS = {
    "as", "async", "await", "break", "const", "continue", "dyn", "else", "enum", "false", "fn", "for", "if",
    "impl", "in", "let", "loop", "match", "mod", "move", "mut", "pub", "ref", "return", "static", "struct",
    "trait", "true", "type", "unsafe", "use", "where", "while", "abstract", "become", "box", "do", "final",
    "macro", "override", "priv", "try", "typeof", "unsized", "virtual", "yield", "gen",
}


def doc_lines(text: str | None, indent: str = "") -> list[str]:
    """Rust `///` lines for a Python docstring.

    Escapes what rustdoc would otherwise interpret (brackets as intra-doc
    links, `<` as HTML, bare fences as doctests) while leaving inline code
    spans untouched.
    """
    if not text:
        return []
    out: list[str] = []
    in_fence = False
    for raw in text.strip().splitlines():
        line = raw.strip()
        if line.startswith("```"):
            if in_fence:
                in_fence = False
            else:
                in_fence = True
                if line == "```":
                    line = "```text"
            out.append(f"{indent}/// {line}")
            continue
        if in_fence:
            out.append(f"{indent}/// {line}" if line else f"{indent}///")
            continue
        pieces = re.split(r"(`[^`]*`)", line)
        escaped = "".join(
            p if p.startswith("`") and p.endswith("`") and len(p) > 1 else _escape_prose(p) for p in pieces
        )
        out.append(f"{indent}/// {escaped}" if escaped else f"{indent}///")
    if in_fence:
        out.append(f"{indent}/// ```")
    return out


def _escape_prose(text: str) -> str:
    return text.replace("\\", "\\\\").replace("[", r"\[").replace("]", r"\]").replace("<", r"\<")


def first_doc(text: str | None, fallback: str, indent: str = "") -> list[str]:
    return doc_lines(text, indent) or [f"{indent}/// {fallback}"]


# --- reflection model -------------------------------------------------------

Ref = tuple  # ('str',) ('int',) ('float',) ('bool',) ('value',) ('def', key) ('list', ref) ('map', ref)


@dataclasses.dataclass
class Field:
    py_name: str
    wire: str
    ident: str
    ref: Ref
    doc: str | None
    const: str | None = None
    boxed: bool = False
    int_as_string: bool = False


@dataclasses.dataclass
class Variant:
    ident: str
    ref: Ref
    tags: list[str]
    boxed: bool = False


@dataclasses.dataclass
class Def:
    key: tuple
    kind: str  # struct | enum | tagged | untagged
    sub: str
    name: str
    doc: str | None
    module: str = ""
    main_class: str = ""
    fields: list[Field] = dataclasses.field(default_factory=list)
    values: list[str] = dataclasses.field(default_factory=list)
    variants: list[Variant] = dataclasses.field(default_factory=list)
    disc: str = ""
    open: bool = False
    hint: str = ""


@dataclasses.dataclass
class UnionMeta:
    open: bool = False
    disc: str | None = None
    variants: dict[str, typing.Any] | None = None
    unknown: type | None = None


class Registry:
    """All reflected Rust types, keyed by canonical signature."""

    def __init__(self) -> None:
        self.defs: dict[tuple, Def] = {}
        self.alias_hints: dict[tuple, list[tuple[str, str, str, str | None, str]]] = {}
        self.by_modname: dict[tuple[str, str], Ref] = {}
        self.unmapped: list[tuple[str, str]] = []
        self.class_docs: dict[tuple[str, str], dict[str, str]] = {}
        self.alias_docs: dict[tuple[str, str], str] = {}
        self.main_class_of: dict[str, str] = {}
        self.overrides = load_overrides()

    # -- sources ------------------------------------------------------------

    def load_module_docs(self, module: pytypes.ModuleType) -> None:
        path = pathlib.Path(module.__file__ or "")
        tree = ast.parse(path.read_text(encoding="utf-8"))
        for stmt in tree.body:
            if isinstance(stmt, ast.ClassDef):
                docs: dict[str, str] = {}
                for cur, nxt in zip(stmt.body, stmt.body[1:] + [None]):
                    if isinstance(cur, ast.AnnAssign) and isinstance(cur.target, ast.Name) and _is_str_expr(nxt):
                        docs[cur.target.id] = inspect.cleandoc(nxt.value.value)
                self.class_docs[(module.__name__, stmt.name)] = docs
        for cur, nxt in zip(tree.body, tree.body[1:] + [None]):
            target = None
            if isinstance(cur, ast.Assign) and len(cur.targets) == 1 and isinstance(cur.targets[0], ast.Name):
                target = cur.targets[0].id
            elif isinstance(cur, ast.AnnAssign) and isinstance(cur.target, ast.Name):
                target = cur.target.id
            if target and _is_str_expr(nxt):
                self.alias_docs[(module.__name__, target)] = inspect.cleandoc(nxt.value.value)


def _serializes_int_as_string(meta: object) -> bool:
    """True for `PlainSerializer(serialize_int(True))`: Python emits int64 as a JSON string."""
    func = getattr(meta, "func", None)
    closure = getattr(func, "__closure__", None) or ()
    return (
        isinstance(meta, pydantic.functional_serializers.PlainSerializer)
        and getattr(func, "__qualname__", "").startswith("serialize_int")
        and any(cell.cell_contents is True for cell in closure)
    )


def _is_str_expr(node: ast.AST | None) -> bool:
    return (
        isinstance(node, ast.Expr)
        and isinstance(node.value, ast.Constant)
        and isinstance(node.value.value, str)
    )


def load_overrides() -> dict[str, typing.Any]:
    if not OVERRIDES_TOML.exists():
        return {}
    return tomllib.loads(OVERRIDES_TOML.read_text(encoding="utf-8"))


# --- canonical signatures ---------------------------------------------------


def is_alias_type(obj: object) -> bool:
    return bool(ALIAS_TYPES) and isinstance(obj, ALIAS_TYPES)


def is_union(origin: object) -> bool:
    return origin is typing.Union or origin is pytypes.UnionType


def is_basemodel_class(obj: object) -> bool:
    return inspect.isclass(obj) and issubclass(obj, pydantic.BaseModel) and obj is not pydantic.BaseModel


def is_unrecognized(obj: object) -> bool:
    return inspect.isclass(obj) and obj.__name__ in {"UnrecognizedStr", "UnrecognizedInt"}


def strip(annotation: object, meta: list) -> tuple[object, list, str | None]:
    """Peels `Annotated[...]` and `TypeAliasType` layers; returns the alias name last seen."""
    alias_name: str | None = None
    while True:
        if typing.get_origin(annotation) is typing.Annotated:
            args = typing.get_args(annotation)
            annotation = args[0]
            meta = [*meta, *args[1:]]
        elif is_alias_type(annotation):
            alias_name = annotation.__name__  # type: ignore[attr-defined]
            annotation = annotation.__value__  # type: ignore[attr-defined]
        else:
            return annotation, meta, alias_name


def union_meta(meta: list) -> UnionMeta:
    info = UnionMeta()
    for item in meta:
        if isinstance(item, pydantic.functional_validators.BeforeValidator):
            func = item.func
            if isinstance(func, functools.partial) and getattr(func.func, "__name__", "") == "parse_open_union":
                info.open = True
                info.disc = func.keywords["disc_key"]
                info.variants = func.keywords["variants"]
                info.unknown = func.keywords["unknown_cls"]
        elif isinstance(item, FieldInfo) and item.discriminator is not None:
            info.disc = _disc_name(item.discriminator)
    return info


def _disc_name(disc: object) -> str:
    return disc if isinstance(disc, str) else getattr(disc, "discriminator", str(disc))


def literal_values(annotation: object) -> list | None:
    """Values of an enum-shaped annotation (`Literal`s, optionally joined with `UnrecognizedStr`)."""
    origin = typing.get_origin(annotation)
    if origin is typing.Literal:
        return list(typing.get_args(annotation))
    if is_union(origin):
        values: list = []
        saw_literal = False
        for member in typing.get_args(annotation):
            member, _, _ = strip(member, [])
            if member is NONE_TYPE or is_unrecognized(member):
                continue
            if typing.get_origin(member) is typing.Literal:
                saw_literal = True
                values.extend(typing.get_args(member))
            else:
                return None
        return values if saw_literal else None
    return None


def canon(annotation: object, meta: list | None = None) -> tuple:
    """Hashable structural signature of an annotation (None-members dropped)."""
    annotation, meta, _ = strip(annotation, list(meta or []))
    origin = typing.get_origin(annotation)
    values = literal_values(annotation)
    if values is not None:
        return ("enum", tuple(values))
    if is_union(origin):
        info = union_meta(meta)
        members = [m for m in typing.get_args(annotation) if m is not NONE_TYPE]
        if info.open and info.unknown is not None:
            members = [m for m in members if m is not info.unknown]
        if len(members) == 1:
            return canon(members[0], meta)
        return ("union", tuple(canon(m) for m in members), info.disc, info.open)
    if origin is list:
        return ("list", canon(typing.get_args(annotation)[0]))
    if origin is dict:
        return ("map", canon(typing.get_args(annotation)[1]))
    if is_basemodel_class(annotation):
        return ("class", annotation)
    if annotation is typing.Any:
        return ("value",)
    if inspect.isclass(annotation):
        if annotation is datetime.datetime:
            return ("str",)
        if is_unrecognized(annotation):
            return ("str",)
        for base, tag in ((bool, "bool"), (int, "int"), (float, "float"), (str, "str"), (bytes, "str")):
            if issubclass(annotation, base):
                return (tag,)
    return ("other", repr(annotation))


# --- type registry population -----------------------------------------------


def types_modules() -> list[pytypes.ModuleType]:
    pkg = importlib.import_module(TYPES_PKG)
    mods = []
    for info in pkgutil.walk_packages(pkg.__path__, pkg.__name__ + "."):
        if info.ispkg:
            continue
        mods.append(importlib.import_module(info.name))
    return sorted(mods, key=lambda m: m.__name__)


def sub_of(modname: str) -> str | None:
    parts = modname.split(".")
    return parts[4] if len(parts) > 5 and modname.startswith(TYPES_PKG + ".") else None


class Builder:
    def __init__(self) -> None:
        self.reg = Registry()
        self.unmapped: list[tuple[str, str]] = []
        self.pending_classes: list[type] = []

    # -- discovery ----------------------------------------------------------

    def scan(self) -> None:
        mods = types_modules()
        for mod in mods:
            self.reg.load_module_docs(mod)
        for mod in mods:
            sub = sub_of(mod.__name__)
            if sub is None:
                continue
            main = None
            for name, obj in vars(mod).items():
                if is_basemodel_class(obj) and obj.__module__ == mod.__name__ and not name.startswith("Unknown"):
                    if main is None or name.lower() == mod.__name__.rsplit(".", 1)[-1].lower():
                        main = name
            self.reg.main_class_of[mod.__name__] = main or ""
            tree = ast.parse(pathlib.Path(mod.__file__).read_text(encoding="utf-8"))
            for stmt in tree.body:
                target = None
                if isinstance(stmt, ast.Assign) and len(stmt.targets) == 1 and isinstance(stmt.targets[0], ast.Name):
                    target = stmt.targets[0].id
                elif isinstance(stmt, ast.AnnAssign) and isinstance(stmt.target, ast.Name):
                    target = stmt.target.id
                if not target or target.startswith("_") or target in {"__all__"}:
                    continue
                if target.endswith(("Param", "TypedDict")):
                    continue
                obj = getattr(mod, target, None)
                if obj is None:
                    continue
                sig = canon(obj)
                if sig[0] in {"enum", "union"}:
                    doc = self.reg.alias_docs.get((mod.__name__, target))
                    self.reg.alias_hints.setdefault(sig, []).append((sub, target, mod.__name__, doc, main or ""))
            for name, obj in sorted(vars(mod).items()):
                if (
                    is_basemodel_class(obj)
                    and obj.__module__ == mod.__name__
                    and not name.startswith("Unknown")
                ):
                    self.pending_classes.append(obj)
                    self.reg.by_modname[(mod.__name__, name)] = ("def", ("class", obj))

    # -- conversion ---------------------------------------------------------

    def ensure_class(self, cls: type) -> Ref:
        key = ("class", cls)
        if key not in self.reg.defs:
            sub = sub_of(cls.__module__)
            if sub is None:
                return ("value",)
            doc = inspect.getdoc(cls)
            d = Def(key=key, kind="struct", sub=sub, name=cls.__name__, doc=doc, module=cls.__module__)
            self.reg.defs[key] = d
            self.fill_struct(d, cls)
        return ("def", key)

    def fill_struct(self, d: Def, cls: type) -> None:
        docs = self.reg.class_docs.get((cls.__module__, cls.__name__), {})
        for fname, finfo in cls.model_fields.items():
            ctx = (d.sub, d.name, fname)
            const = None
            ann, meta, _ = strip(finfo.annotation, list(finfo.metadata))
            if finfo.discriminator is not None:
                meta.append(finfo)
            if typing.get_origin(ann) is typing.Literal and len(typing.get_args(ann)) == 1:
                value = typing.get_args(ann)[0]
                if not finfo.is_required() and finfo.default == value and isinstance(value, str):
                    const = value
            ref = ("str",) if const else self.conv(finfo.annotation, meta, ctx, module=cls.__module__)
            wire = finfo.alias or fname
            int_as_string = any(_serializes_int_as_string(m) for m in finfo.metadata)
            d.fields.append(
                Field(
                    py_name=fname,
                    wire=wire,
                    ident=rust_ident(fname),
                    ref=ref,
                    doc=docs.get(fname),
                    const=const,
                    int_as_string=int_as_string,
                )
            )

    def mark_unmapped(self, ctx: tuple, what: str) -> Ref:
        sub, struct, field = ctx
        self.unmapped.append((f"{sub}.{struct}.{field}", what))
        return ("value",)

    def conv(self, annotation: object, meta: list, ctx: tuple, module: str = "") -> Ref:
        annotation, meta, alias_name = strip(annotation, list(meta))
        origin = typing.get_origin(annotation)
        if is_union(origin):
            present = [m for m in typing.get_args(annotation) if m is not NONE_TYPE]
            if len(present) == 1:
                return self.conv(present[0], meta, ctx, module)
        sig = canon(annotation, meta)
        kind = sig[0]
        if kind in {"str", "int", "float", "bool", "value"}:
            return (kind,)
        if kind == "enum":
            return self.ensure_enum(sig, ctx, alias_name)
        if kind == "list":
            args = typing.get_args(annotation)
            return ("list", self.conv(args[0], [], ctx, module))
        if kind == "map":
            args = typing.get_args(annotation)
            return ("map", self.conv(args[1], [], ctx, module))
        if kind == "class":
            return self.ensure_class(annotation)  # type: ignore[arg-type]
        if kind == "union":
            return self.ensure_union(annotation, meta, sig, ctx, alias_name)
        if is_union(origin):
            members = [m for m in typing.get_args(annotation) if m is not NONE_TYPE]
            return self.conv(members[0], meta, ctx, module)
        return self.mark_unmapped(ctx, f"unsupported annotation {annotation!r}")

    def name_for(self, sig: tuple, ctx: tuple, alias_name: str | None) -> tuple[str, str | None, str, str]:
        """Returns (name, doc, sub, main_class_prefix)."""
        hints = self.reg.alias_hints.get(sig)
        sub = ctx[0]
        if hints:
            hsub, hname, hmod, hdoc, hmain = hints[0]
            return hname, hdoc, hsub, hmain
        base = alias_name or f"{ctx[1]}{pascal(ctx[2])}"
        return base, None, sub, ctx[1]

    def ensure_enum(self, sig: tuple, ctx: tuple, alias_name: str | None) -> Ref:
        if sig in self.reg.defs:
            return ("def", sig)
        values = list(sig[1])
        if not all(isinstance(v, str) for v in values):
            return self.mark_unmapped(ctx, "non-string literal enum")
        name, doc, sub, main = self.name_for(sig, ctx, alias_name)
        d = Def(key=sig, kind="enum", sub=sub, name=name, doc=doc, main_class=main, values=values,
                hint=f"{ctx[1]}.{ctx[2]}")
        self.reg.defs[sig] = d
        return ("def", sig)

    def ensure_union(self, annotation: object, meta: list, sig: tuple, ctx: tuple, alias_name: str | None) -> Ref:
        if sig in self.reg.defs:
            return ("def", sig)
        info = union_meta(meta)
        members = [m for m in typing.get_args(annotation) if m is not NONE_TYPE]
        if info.open and info.unknown is not None:
            members = [m for m in members if m is not info.unknown]
        stripped = [strip(m, [])[0] for m in members]
        name, doc, sub, main = self.name_for(sig, ctx, alias_name)
        d = Def(key=sig, kind="untagged", sub=sub, name=name, doc=doc, main_class=main, disc=info.disc or "",
                open=info.open, hint=f"{ctx[1]}.{ctx[2]}")
        self.reg.defs[sig] = d
        tagged = info.disc is not None and all(is_basemodel_class(m) for m in stripped)
        if tagged:
            tag_map: dict[type, list[str]] = {}
            if info.open and info.variants is not None:
                for tag, cls in info.variants.items():
                    tag_map.setdefault(cls, []).append(tag)
            else:
                for cls in stripped:
                    fld = cls.model_fields.get(info.disc)  # type: ignore[arg-type]
                    default = getattr(fld, "default", None)
                    if isinstance(default, str):
                        tag_map.setdefault(cls, []).append(default)
            if all(cls in tag_map for cls in stripped):
                d.kind = "tagged"
                for cls in stripped:
                    ref = self.ensure_class(cls)
                    d.variants.append(Variant(ident=cls.__name__, ref=ref, tags=tag_map[cls]))
                return ("def", sig)
        # untagged: one variant per member type
        seen: dict[str, int] = {}
        for member in members:
            ref = self.conv(member, [], ctx)
            ident = self.variant_ident(ref)
            seen[ident] = seen.get(ident, 0) + 1
            if seen[ident] > 1:
                ident = f"{ident}{seen[ident]}"
            d.variants.append(Variant(ident=ident, ref=ref, tags=[]))
        if any(v.ref == ("value",) for v in d.variants):
            del self.reg.defs[sig]
            return self.mark_unmapped(ctx, "union with an unmappable member")
        return ("def", sig)

    def variant_ident(self, ref: Ref) -> str:
        tag = ref[0]
        if tag == "def":
            return self.reg.defs[ref[1]].name if ref[1] in self.reg.defs else "Item"
        return {"str": "Text", "int": "Integer", "float": "Float", "bool": "Boolean", "list": "List",
                "map": "Map", "value": "Value"}[tag]

    # -- finishing ----------------------------------------------------------

    def build(self) -> None:
        self.scan()
        for cls in self.pending_classes:
            self.ensure_class(cls)
        self.finalize_names()
        self.box_cycles()

    def finalize_names(self) -> None:
        defs = list(self.reg.defs.values())
        renames = self.reg.overrides.get("rename", {})
        for d in defs:
            d.name = renames.get(f"{d.sub}.{d.name}", d.name)
        counts: dict[tuple[str, str], int] = {}
        for d in defs:
            counts[(d.sub, d.name)] = counts.get((d.sub, d.name), 0) + 1
        for d in defs:
            if d.kind != "struct" and counts[(d.sub, d.name)] > 1 and d.main_class:
                d.name = f"{d.main_class}{d.name}"
        counts = {}
        for d in defs:
            counts[(d.sub, d.name)] = counts.get((d.sub, d.name), 0) + 1
        for d in sorted(defs, key=lambda x: (x.sub, x.name, x.hint)):
            if counts[(d.sub, d.name)] > 1:
                idx = counts[(d.sub, d.name)]
                counts[(d.sub, d.name)] -= 1
                d.name = f"{d.name}{idx}" if idx > 1 else d.name
        taken: set[tuple[str, str]] = set()
        shadowing = {d.name for d in defs} & RUST_PRELUDE_NAMES
        if shadowing:
            sys.exit(f"gen_gaos.py: generated type names shadow Rust prelude items: {sorted(shadowing)}")
        for d in sorted(defs, key=lambda x: (x.sub, x.name, x.hint)):
            if (d.sub, d.name) in taken:
                sys.exit(f"gen_gaos.py: unresolved Rust name collision {d.sub}.{d.name}")
            taken.add((d.sub, d.name))

    def direct_edges(self, d: Def) -> list[tuple[object, tuple]]:
        edges: list[tuple[object, tuple]] = []
        items: list[object] = list(d.fields) if d.kind == "struct" else list(d.variants)
        for item in items:
            ref = item.ref  # type: ignore[attr-defined]
            if ref[0] == "def" and ref[1] in self.reg.defs:
                edges.append((item, ref[1]))
        return edges

    def box_cycles(self) -> None:
        graph = {k: [t for _, t in self.direct_edges(d)] for k, d in self.reg.defs.items()}

        def reaches(start: tuple, goal: tuple) -> bool:
            seen: set[tuple] = set()
            stack = [start]
            while stack:
                node = stack.pop()
                if node == goal:
                    return True
                if node in seen:
                    continue
                seen.add(node)
                stack.extend(graph.get(node, []))
            return False

        for key, d in self.reg.defs.items():
            for item, target in self.direct_edges(d):
                if target == key or reaches(target, key):
                    item.boxed = True  # type: ignore[attr-defined]


# --- rendering: types -------------------------------------------------------


class Renderer:
    def __init__(self, reg: Registry) -> None:
        self.reg = reg

    def rust_type(self, ref: Ref, from_sub: str | None, boxed: bool = False, absolute: bool = False) -> str:
        tag = ref[0]
        if tag == "str":
            return "String"
        if tag == "int":
            return "i64"
        if tag == "float":
            return "f64"
        if tag == "bool":
            return "bool"
        if tag == "value":
            return "serde_json::Value"
        if tag == "list":
            return f"Vec<{self.rust_type(ref[1], from_sub, False, absolute)}>"
        if tag == "map":
            return f"std::collections::HashMap<String, {self.rust_type(ref[1], from_sub, False, absolute)}>"
        d = self.reg.defs[ref[1]]
        path = self.def_path(d, from_sub, absolute)
        return f"Box<{path}>" if boxed else path

    def def_path(self, d: Def, from_sub: str | None, absolute: bool = False) -> str:
        if absolute or from_sub is None:
            return f"crate::gaos::types::{d.sub}::{d.name}"
        if d.sub == from_sub:
            return d.name
        return f"super::{d.sub}::{d.name}"

    # -- struct -------------------------------------------------------------

    def render_struct(self, d: Def) -> str:
        has_const = any(f.const for f in d.fields)
        lines: list[str] = []
        lines += first_doc(d.doc, f"`{d.name}`.")
        lines.append("#[serde_with::serde_as]")
        derives = "Debug, Clone, PartialEq, " + ("" if has_const else "Default, ") + "serde::Serialize, serde::Deserialize"
        lines.append(f"#[derive({derives})]")
        lines.append(f"pub struct {d.name} {{")
        extra: list[str] = []
        for f in d.fields:
            if f.const:
                lines += [f"    /// Fixed discriminator; always `{f.const}`."]
                fn = f"default_{snake(d.name)}_{snake(f.py_name.rstrip('_'))}"
                lines.append(f'    #[serde(default = "{fn}"' + self._rename(f) + ")]")
                lines.append(f"    pub {f.ident}: String,")
                extra.append(f"fn {fn}() -> String {{\n    \"{f.const}\".to_owned()\n}}")
                continue
            lines += first_doc(f.doc, f"`{d.name}.{f.py_name}`.", "    ")
            attrs = '    #[serde(default, skip_serializing_if = "Option::is_none"' + self._rename(f) + ")]"
            lines.append(attrs)
            rt = self.rust_type(f.ref, d.sub, f.boxed)
            if rt == "i64" and f.int_as_string:
                # Python serializes this int64 as a JSON string; either form is accepted on input.
                lines.append(
                    '    #[serde_as(as = "Option<serde_with::PickFirst<(serde_with::DisplayFromStr, _)>>")]'
                )
            elif rt == "i64":
                lines.append(
                    '    #[serde_as(as = "Option<serde_with::PickFirst<(_, serde_with::DisplayFromStr)>>")]'
                )
            elif rt == "Vec<i64>":
                lines.append(
                    '    #[serde_as(as = "Option<Vec<serde_with::PickFirst<(_, serde_with::DisplayFromStr)>>>")]'
                )
            lines.append(f"    pub {f.ident}: Option<{rt}>,")
        lines.append("}")
        out = "\n".join(lines)
        if has_const:
            out += f"\n\nimpl Default for {d.name} {{\n    fn default() -> Self {{\n        Self {{\n"
            for f in d.fields:
                if f.const:
                    fn = f"default_{snake(d.name)}_{snake(f.py_name.rstrip('_'))}"
                    out += f"            {f.ident}: {fn}(),\n"
                else:
                    out += f"            {f.ident}: None,\n"
            out += "        }\n    }\n}"
        for e in extra:
            out += "\n\n" + e
        return out

    @staticmethod
    def _rename(f: Field) -> str:
        bare = f.ident.removeprefix("r#")
        return f', rename = "{f.wire}"' if f.wire != bare else ""

    # -- enums --------------------------------------------------------------

    def enum_variants(self, values: list[str]) -> list[tuple[str, str]]:
        out: list[tuple[str, str]] = []
        used: dict[str, int] = {}
        for value in values:
            ident = pascal(re.sub(r"[^0-9A-Za-z]+", "_", value)) or "Empty"
            if ident[0].isdigit():
                ident = f"V{ident}"
            used[ident] = used.get(ident, 0) + 1
            if used[ident] > 1:
                ident = f"{ident}{used[ident]}"
            out.append((ident, value))
        return out

    def render_enum(self, d: Def) -> str:
        variants = self.enum_variants(d.values)
        name = d.name
        lines: list[str] = []
        lines += first_doc(d.doc, f"`{name}`.")
        lines.append("#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]")
        lines.append('#[serde(from = "String", into = "String")]')
        lines.append(f"pub enum {name} {{")
        for ident, value in variants:
            lines.append(f"    /// `{value}`.")
            lines.append(f"    {ident},")
        lines.append("    /// A value not known when this crate was generated.")
        lines.append("    Unknown(String),")
        lines.append("}")
        lines.append("")
        lines.append(f"impl {name} {{")
        lines.append("    /// The exact wire string for this value.")
        lines.append("    #[must_use]")
        lines.append("    pub fn as_str(&self) -> &str {")
        lines.append("        match self {")
        for ident, value in variants:
            lines.append(f'            Self::{ident} => "{value}",')
        lines.append("            Self::Unknown(value) => value,")
        lines.append("        }")
        lines.append("    }")
        lines.append("}")
        lines.append("")
        lines.append(f"impl std::fmt::Display for {name} {{")
        lines.append("    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {")
        lines.append("        f.write_str(self.as_str())")
        lines.append("    }")
        lines.append("}")
        lines.append("")
        lines.append(f"impl From<String> for {name} {{")
        lines.append("    fn from(value: String) -> Self {")
        lines.append("        match value.as_str() {")
        for ident, value in variants:
            lines.append(f'            "{value}" => Self::{ident},')
        lines.append("            _ => Self::Unknown(value),")
        lines.append("        }")
        lines.append("    }")
        lines.append("}")
        lines.append("")
        lines.append(f"impl From<{name}> for String {{")
        lines.append(f"    fn from(value: {name}) -> Self {{")
        lines.append("        value.as_str().to_owned()")
        lines.append("    }")
        lines.append("}")
        return "\n".join(lines)

    # -- unions -------------------------------------------------------------

    def render_tagged(self, d: Def) -> str:
        name = d.name
        lines: list[str] = []
        lines += first_doc(d.doc, f"`{name}`, discriminated by `{d.disc}`.")
        lines.append("#[derive(Debug, Clone, PartialEq)]")
        lines.append(f"pub enum {name} {{")
        for v in d.variants:
            lines.append(f"    /// `{'` / `'.join(v.tags)}`.")
            lines.append(f"    {v.ident}({self.rust_type(v.ref, d.sub, v.boxed)}),")
        if d.open:
            lines.append("    /// A variant not known when this crate was generated; the raw payload.")
            lines.append("    Unknown(serde_json::Value),")
        lines.append("}")
        lines.append("")
        lines.append(f"impl serde::Serialize for {name} {{")
        lines.append("    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {")
        lines.append("        match self {")
        for v in d.variants:
            lines.append(f"            Self::{v.ident}(inner) => inner.serialize(serializer),")
        if d.open:
            lines.append("            Self::Unknown(raw) => raw.serialize(serializer),")
        lines.append("        }")
        lines.append("    }")
        lines.append("}")
        lines.append("")
        lines.append(f"impl<'de> serde::Deserialize<'de> for {name} {{")
        lines.append(
            "    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {"
        )
        lines.append("        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;")
        lines.append(f'        let tag = value.get("{d.disc}").and_then(serde_json::Value::as_str);')
        lines.append("        match tag {")
        for v in d.variants:
            pat = " | ".join(f'"{t}"' for t in v.tags)
            lines.append(f"            Some({pat}) => serde_json::from_value(value)")
            if v.boxed:
                lines.append("                .map(Box::new)")
            lines.append(f"                .map(Self::{v.ident})")
            lines.append("                .map_err(serde::de::Error::custom),")
        if d.open:
            lines.append("            _ => Ok(Self::Unknown(value)),")
        else:
            lines.append("            other => Err(serde::de::Error::custom(format!(")
            lines.append(f'                "unknown `{d.disc}` value {{other:?}} for {name}"')
            lines.append("            ))),")
        lines.append("        }")
        lines.append("    }")
        lines.append("}")
        return "\n".join(lines)

    def render_untagged(self, d: Def) -> str:
        lines: list[str] = []
        lines += first_doc(d.doc, f"`{d.name}`: one of several shapes, tried in order.")
        lines.append("#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]")
        lines.append("#[serde(untagged)]")
        lines.append(f"pub enum {d.name} {{")
        for v in d.variants:
            lines.append(f"    /// The `{v.ident}` shape.")
            lines.append(f"    {v.ident}({self.rust_type(v.ref, d.sub, v.boxed)}),")
        lines.append("}")
        return "\n".join(lines)

    def render_def(self, d: Def) -> str:
        return {
            "struct": self.render_struct,
            "enum": self.render_enum,
            "tagged": self.render_tagged,
            "untagged": self.render_untagged,
        }[d.kind](d)


def render_types_rs(reg: Registry) -> str:
    r = Renderer(reg)
    by_sub: dict[str, list[Def]] = {}
    for d in reg.defs.values():
        by_sub.setdefault(d.sub, []).append(d)
    parts = [
        header(),
        f"//! Types of the `_gaos` sub-SDK ({len(reg.defs)} items), one module per upstream\n"
        "//! sub-package. Field names are the wire (snake_case) names.\n\n",
        ALLOW_ATTR,
    ]
    for sub in sorted(by_sub):
        parts.append(f"/// Types from `google.genai._gaos.types.{sub}`.\npub mod {sub} {{\n")
        for d in sorted(by_sub[sub], key=lambda x: x.name):
            body = r.render_def(d)
            parts.append("\n".join(("    " + ln if ln else ln) for ln in body.splitlines()))
            parts.append("\n\n")
        parts.append("}\n\n")
    return "".join(parts)


# --- operations -------------------------------------------------------------


@dataclasses.dataclass
class Param:
    py_name: str
    wire: str
    ident: str
    ref: Ref
    doc: str | None
    required: bool


@dataclasses.dataclass
class Operation:
    resource: str
    struct: str
    py_class: str
    name: str
    python: str
    verb: str
    template: str
    opid: str
    doc: str
    path_params: list[Param]
    query_params: list[Param]
    body: Param | None
    body_optional: bool
    response: Ref | None
    stream: bool
    request_class: str
    stream_response: Ref | None = None
    sample_response: object | None = None
    sample_body: object | None = None


def _const_str(node: ast.AST | None) -> str | None:
    if isinstance(node, ast.Constant) and isinstance(node.value, str):
        return node.value
    return None


def parse_resources(builder: Builder) -> list[Operation]:
    ops: list[Operation] = []
    types_pkg = importlib.import_module(TYPES_PKG)
    models_pkg = importlib.import_module(MODELS_PKG)
    namespace = {sub: getattr(types_pkg, sub) for sub in RESOURCES}
    for resource, classes in RESOURCES.items():
        for filename, class_name, prefix in classes:
            tree = ast.parse((GAOS_SRC_DIR / filename).read_text(encoding="utf-8"))
            cls_node = next(c for c in tree.body if isinstance(c, ast.ClassDef) and c.name == class_name)
            impls: dict[str, ast.FunctionDef] = {}
            for fn in cls_node.body:
                if isinstance(fn, ast.FunctionDef) and fn.name not in NON_OPERATION_METHODS:
                    if any(ast.unparse(d) == "overload" for d in fn.decorator_list):
                        continue
                    impls[fn.name] = fn
            for fname, fn in impls.items():
                ops.append(extract_operation(builder, resource, class_name, prefix, fname, fn, namespace, models_pkg))
    return ops


def extract_operation(
    builder: Builder,
    resource: str,
    class_name: str,
    prefix: str,
    fname: str,
    fn: ast.FunctionDef,
    namespace: dict,
    models_pkg: pytypes.ModuleType,
) -> Operation:
    verb = template = opid = None
    accept = ""
    response_expr = None
    for node in ast.walk(fn):
        if isinstance(node, ast.Call):
            callee = ast.unparse(node.func)
            if callee == "self._build_request":
                kw = {k.arg: k.value for k in node.keywords}
                verb = _const_str(kw.get("method"))
                template = _const_str(kw.get("path"))
                accept = ast.unparse(kw["accept_header_value"]) if "accept_header_value" in kw else ""
            elif callee == "HookContext":
                kw = {k.arg: k.value for k in node.keywords}
                opid = _const_str(kw.get("operation_id"))
            elif callee == "unmarshal_json_response" and response_expr is None:
                first = ast.unparse(node.args[0])
                if not first.startswith("errors."):
                    response_expr = first
    if not (verb and template and opid):
        sys.exit(f"gen_gaos.py: cannot extract {resource}.{fname}: verb/path/operation id missing")

    opid = opid[:1].upper() + opid[1:]
    req_module = importlib.import_module(f"{MODELS_PKG}.{opid.lower()}")
    req_cls = next(
        obj
        for name, obj in vars(req_module).items()
        if inspect.isclass(obj) and name.lower() == f"{opid}Request".lower()
    )
    path_params: list[Param] = []
    query_params: list[Param] = []
    body: Param | None = None
    body_optional = False
    docs = builder.reg.class_docs.get((req_module.__name__, req_cls.__name__), {})
    placeholders = re.findall(r"\{(\w+)\}", template)
    by_alias: dict[str, Param] = {}
    for pname, finfo in req_cls.model_fields.items():
        md = next((m for m in finfo.metadata if type(m).__name__ == "FieldMetadata"), None)
        if md is None or pname == "api_version":
            continue
        ctx = (resource, req_cls.__name__, pname)
        meta = list(finfo.metadata)
        if finfo.discriminator is not None:
            meta.append(finfo)
        ref = builder.conv(finfo.annotation, meta, ctx, req_module.__name__)
        param = Param(
            py_name=pname,
            wire=finfo.alias or pname,
            ident=rust_ident(pname),
            ref=ref,
            doc=docs.get(pname),
            required=finfo.is_required(),
        )
        if md.path is not None:
            by_alias[param.wire] = param
        elif md.query is not None:
            query_params.append(param)
        elif md.request is not None:
            body = param
            body_optional = not finfo.is_required()
    path_params = [by_alias[p] for p in placeholders if p != "api_version"]
    for p in placeholders:
        if p != "api_version" and p not in by_alias:
            sys.exit(f"gen_gaos.py: {resource}.{fname}: path placeholder {p} has no request field")

    response: Ref | None = None
    if response_expr:
        obj = eval(response_expr, {}, namespace)  # noqa: S307 - dotted names from upstream source
        response = builder.conv(obj, [], (resource, opid, "response"))

    stream_response: Ref | None = None
    if "text/event-stream" in accept:
        item = re.search(r"Stream\[([\w\.]+)\]", ast.unparse(fn.returns))
        if item is None:
            sys.exit(f"gen_gaos.py: {resource}.{fname}: stream operation without Stream[...] return type")
        stream_response = builder.conv(eval(item.group(1), {}, namespace), [], (resource, opid, "event"))  # noqa: S307

    doc = ast.get_docstring(fn) or ""
    doc = re.split(r"^:param ", doc, maxsplit=1, flags=re.M)[0].strip()
    return Operation(
        resource=resource,
        struct=class_name,
        py_class=class_name,
        name=f"{prefix}{fname}",
        python=f"{resource}.{prefix.rstrip('_') + '.' if prefix else ''}{fname}",
        verb=verb,
        template=template,
        opid=opid,
        doc=doc,
        path_params=path_params,
        query_params=query_params,
        body=body,
        body_optional=body_optional,
        response=response,
        stream="text/event-stream" in accept,
        request_class=req_cls.__name__,
        stream_response=stream_response,
    )


# --- rendering: models.rs ---------------------------------------------------


def render_models_rs(reg: Registry, ops: list[Operation]) -> tuple[str, dict[str, str]]:
    r = Renderer(reg)
    parts = [
        header(),
        "//! Query-parameter structs of the `_gaos` operations (one per upstream\n"
        "//! `models.<Operation>Request` that carries query parameters). Path\n"
        "//! parameters and the request body are separate method arguments.\n\n",
        ALLOW_ATTR,
    ]
    names: dict[str, str] = {}
    for op in sorted(ops, key=lambda o: o.request_class):
        if not op.query_params:
            continue
        names[op.opid] = op.request_class
        parts.append(
            f"/// Query parameters of `{op.python}` (upstream `{op.request_class}`).\n"
            "#[derive(Debug, Clone, PartialEq, Default)]\n"
            f"pub struct {op.request_class} {{\n"
        )
        for p in op.query_params:
            parts.append("\n".join(first_doc(p.doc, f"`{p.py_name}`.", "    ")) + "\n")
            parts.append(f"    pub {p.ident}: Option<{r.rust_type(p.ref, None)}>,\n")
        parts.append("}\n\n")
    return "".join(parts), names


# --- rendering: resources ---------------------------------------------------


def query_push(p: Param, reg: Registry) -> str:
    wire = p.wire
    ident = p.ident
    if p.ref[0] == "list":
        return f'query.push_all("{wire}", params.{ident}.as_deref());'
    return f'query.push("{wire}", params.{ident}.as_ref());'


def arg_ident(p: Param) -> str:
    return p.ident


# Facade-level request normalisation the Python SDK applies before sending
# (`_normalize_create_body`); the hand-written helpers live in the public modules.
BODY_HOOKS = {
    ("interactions", "create"): "crate::interactions::normalize_create_body",
    ("triggers", "create"): "crate::triggers::normalize_trigger_create_body",
}


def render_resource(reg: Registry, resource: str, ops: list[Operation], models_names: dict[str, str]) -> str:
    r = Renderer(reg)
    struct = ops[0].struct if resource != "environments" else "Environments"
    uses_stream = any(o.stream for o in ops)
    parts = [
        header(),
        f"//! `client.{resource}()`: the `_gaos` `{resource}` operations. Generated from\n"
        f"//! `google/genai/_gaos/{resource}.py`.\n\n",
        ALLOW_ATTR,
        "use reqwest::Method;\n",
    ]
    if uses_stream:
        parts.append("use futures_core::Stream;\nuse futures_util::StreamExt;\n")
    errors_import = "{Error, Result}" if uses_stream else "Result"
    parts.append(f"\nuse crate::{{\n    client::Client,\n    errors::{errors_import},\n    gaos::wire,\n    types::HttpOptions,\n}};\n\n")
    parts.append(
        f"/// Handle for the `{resource}` operations (`client.{resource}()`).\n"
        "#[derive(Debug, Clone)]\n"
        f"pub struct {struct} {{\n    pub(crate) client: Client,\n    pub(crate) http_options: Option<HttpOptions>,\n}}\n\n"
        f"impl {struct} {{\n"
        "    pub(crate) fn new(client: Client) -> Self {\n        Self {\n            client,\n            http_options: None,\n        }\n    }\n\n"
        "    /// Returns a handle whose calls use `options` instead of the client's `HttpOptions`:\n"
        "    /// extra `headers`, a per-call `api_version`, `timeout`, `extra_body` or `retry_options`\n"
        "    /// (the upstream per-call `extra_headers` / `api_version` / `timeout` arguments).\n"
        "    #[must_use]\n"
        "    pub fn with_http_options(mut self, options: HttpOptions) -> Self {\n"
        "        self.http_options = Some(options);\n        self\n    }\n\n"
    )
    for op in ops:
        parts.append(render_operation(r, op, models_names))
    parts.append("}\n")
    return "".join(parts)


def op_signature_args(r: Renderer, op: Operation, models_names: dict[str, str]) -> list[tuple[str, str]]:
    args: list[tuple[str, str]] = []
    for p in op.path_params:
        args.append((p.ident, "&str"))
    if op.body is not None:
        body_ty = r.rust_type(op.body.ref, None, absolute=True)
        args.append(("body", f"Option<&{body_ty}>" if op.body_optional else f"&{body_ty}"))
    if op.query_params:
        args.append(("params", f"&crate::gaos::models::{models_names[op.opid]}"))
    return args


def render_operation(r: Renderer, op: Operation, models_names: dict[str, str]) -> str:
    out: list[str] = []
    variants = [(op.name, False)]
    if op.stream:
        variants = [(op.name, False), (f"{op.name}_stream", True)]
    for name, streaming in variants:
        args = op_signature_args(r, op, models_names)
        arg_src = "".join(f", {n}: {t}" for n, t in args)
        resp_ty = "()" if op.response is None else r.rust_type(op.response, None, absolute=True)
        if streaming:
            item_ty = r.rust_type(op.stream_response, None, absolute=True)  # type: ignore[arg-type]
            ret = f"Result<impl Stream<Item = Result<{item_ty}>> + Send + Unpin + use<>>"
        else:
            ret = f"Result<{resp_ty}>"
        doc = doc_lines(op.doc) or [f"/// `{op.python}`."]
        if streaming:
            doc.append("///")
            doc.append(f"/// Streaming variant of [`Self::{op.name}`]: requests `text/event-stream` and yields each event.")
        doc += [
            "///",
            f"/// `{op.verb} {op.template}`.",
            "///",
            "/// # Errors",
            "/// Returns [`Error::Api`](crate::errors::Error::Api) for a non-2xx response,",
            "/// [`Error::Http`](crate::errors::Error::Http) for transport failures, and",
            "/// [`Error::Json`](crate::errors::Error::Json) if the request cannot be serialized or the response cannot be decoded.",
        ]
        out.extend("    " + ln for ln in doc)
        out.append(f"    pub async fn {name}(&self{arg_src}) -> {ret} {{")
        out.append(render_body(r, op, streaming, item_ty if streaming else resp_ty))
        out.append("    }\n")
    return "\n".join(out) + "\n"


def render_body(r: Renderer, op: Operation, streaming: bool, resp_ty: str) -> str:
    tmpl = op.template
    assert tmpl.startswith("/{api_version}/"), tmpl
    rel = tmpl.removeprefix("/{api_version}/")
    fmt = re.sub(r"\{(\w+)\}", "{}", rel)
    lines: list[str] = []
    placeholders = [p for p in re.findall(r"\{(\w+)\}", rel)]
    by_wire = {p.wire: p for p in op.path_params}
    if placeholders:
        fmt_args = ", ".join(f"wire::path_segment({by_wire[ph].ident})" for ph in placeholders)
        lines.append(f'        let url_path = format!("{fmt}", {fmt_args});')
    else:
        lines.append(f'        let url_path = "{rel}";')
    path_arg = "&url_path" if placeholders else "url_path"
    stream_flag = any(p.py_name == "stream" for p in op.query_params)
    if op.query_params:
        lines.append("        let mut query = wire::Query::default();")
        for p in op.query_params:
            if p.py_name != "stream":
                lines.append("        " + query_push(p, r.reg))
        if stream_flag:
            # `stream` is a query flag on this operation; the facade always sends it
            # (`true` for the stream variant, `false` otherwise, like the Python SDK).
            lines.append(f'        query.set("stream", "{"true" if streaming else "false"}");')
        lines.append("        let query = query.finish();")
    else:
        lines.append("        let query: Option<String> = None;")
    if op.body is not None:
        if op.body_optional:
            lines.append("        let body = body.map(serde_json::to_value).transpose()?;")
        else:
            lines.append("        let body = serde_json::to_value(body)?;")
        hook = BODY_HOOKS.get((op.resource, op.name))
        if hook is not None:
            lines.append(f"        let body = {hook}(body)?;")
        if streaming and op.body is not None:
            if op.body_optional:
                lines.append("        let body = body.map(wire::with_stream_flag);")
            else:
                lines.append("        let body = wire::with_stream_flag(body);")
        body_arg = "body" if op.body_optional else "Some(body)"
    else:
        body_arg = "None"
    method = f"Method::{op.verb}"
    if streaming:
        lines.append("        let http_options = wire::stream_http_options(self.http_options.as_ref());")
        lines.append("        let events = self")
        lines.append("            .client")
        lines.append("            .http()")
        lines.append(f"            .request_stream({method}, {path_arg}, query.as_deref(), {body_arg}, Some(&http_options))")
        lines.append("            .await?;")
        lines.append(
            f"        Ok(events.map(|event| event.and_then(|value| serde_json::from_value::<{resp_ty}>(value).map_err(Error::from))))"
        )
    else:
        lines.append("        let response = self")
        lines.append("            .client")
        lines.append("            .http()")
        lines.append(f"            .request({method}, {path_arg}, query.as_deref(), {body_arg}, self.http_options.as_ref())")
        lines.append("            .await?;")
        if op.response is None:
            lines.append("        let _ = response;")
            lines.append("        Ok(())")
        else:
            lines.append("        wire::parse(&response.body)")
    return "\n".join(lines)


# --- rendering: mod.rs ------------------------------------------------------

WIRE_RS = '''/// Wire helpers shared by the generated operations.
pub(crate) mod wire {
    use std::{collections::HashMap, fmt::Display};

    use bytes::Bytes;
    use serde::de::DeserializeOwned;
    use serde_json::{Value, json};

    use crate::{errors::Result, types::HttpOptions};

    /// Percent-encodes one path parameter. RFC 3986 unreserved characters and `/`
    /// pass through: the Python SDK substitutes path parameters verbatim, so a
    /// nested resource name or file path (`projects/p/triggers/t`, `src/main.py`)
    /// keeps its slashes on the wire. Reserved characters such as `?`, `#` and
    /// `%` are escaped (Python lets them truncate the URL).
    pub(crate) fn path_segment(segment: &str) -> String {
        segment
            .bytes()
            .map(|byte| match byte {
                b'A'..=b'Z' | b'a'..=b'z' | b'0'..=b'9' | b'-' | b'.' | b'_' | b'~' | b'/' => {
                    char::from(byte).to_string()
                }
                other => format!("%{other:02X}"),
            })
            .collect()
    }

    /// Accumulates `form`-style (exploded) query parameters.
    #[derive(Debug, Default)]
    pub(crate) struct Query {
        pairs: Vec<(String, String)>,
    }

    impl Query {
        /// Adds `name=value` when `value` is set.
        pub(crate) fn push<T: Display>(&mut self, name: &str, value: Option<&T>) {
            if let Some(value) = value {
                self.pairs.push((name.to_owned(), value.to_string()));
            }
        }

        /// Adds one `name=value` pair per element (exploded array).
        pub(crate) fn push_all<T: Display>(&mut self, name: &str, values: Option<&[T]>) {
            for value in values.unwrap_or_default() {
                self.pairs.push((name.to_owned(), value.to_string()));
            }
        }

        /// Replaces every value of `name` with `value`.
        pub(crate) fn set(&mut self, name: &str, value: &str) {
            self.pairs.retain(|(existing, _)| existing != name);
            self.pairs.push((name.to_owned(), value.to_owned()));
        }

        /// The encoded query string, or `None` when empty.
        pub(crate) fn finish(self) -> Option<String> {
            if self.pairs.is_empty() {
                return None;
            }
            let mut serializer = url::form_urlencoded::Serializer::new(String::new());
            serializer.extend_pairs(&self.pairs);
            Some(serializer.finish())
        }
    }

    /// Decodes a JSON response body; an empty body decodes as `{}`.
    pub(crate) fn parse<T: DeserializeOwned>(body: &Bytes) -> Result<T> {
        if body.is_empty() {
            return Ok(serde_json::from_value(json!({}))?);
        }
        Ok(serde_json::from_slice(body)?)
    }

    /// Sets `"stream": true` on a JSON object body.
    pub(crate) fn with_stream_flag(mut body: Value) -> Value {
        if let Value::Object(map) = &mut body {
            map.insert("stream".to_owned(), Value::Bool(true));
        }
        body
    }

    /// The per-call options of a streaming request: `base` plus an
    /// `Accept: text/event-stream` header asking for a server-sent-event response.
    pub(crate) fn stream_http_options(base: Option<&HttpOptions>) -> HttpOptions {
        let mut options = base.cloned().unwrap_or_default();
        options
            .headers
            .get_or_insert_with(HashMap::new)
            .insert("Accept".to_owned(), "text/event-stream".to_owned());
        options
    }
}
'''


def public_exports(reg: Registry, models_names: dict[str, str], ops: list[Operation]) -> dict[str, list[tuple[str, str, str]]]:
    """Per public module: list of (rust_path, rust_alias_or_empty, python_name) re-exports.

    Mirrors each upstream public module's `__all__`; Python-only shapes
    (`*Param` TypedDicts without a Rust twin) are skipped and counted.
    """
    r = Renderer(reg)
    exports: dict[str, list[tuple[str, str, str]]] = {}
    skipped: list[str] = []
    models_by_class = {v: k for k, v in models_names.items()}
    for resource in RESOURCES:
        mod = importlib.import_module(f"google.genai.{resource}")
        entries: list[tuple[str, str, str]] = []
        seen_alias: set[str] = set()
        for name in mod.__all__:
            obj = getattr(mod, name)
            rust_path = resolve_export(reg, obj, models_names)
            if rust_path is None:
                skipped.append(f"{resource}.{name}")
                continue
            base = rust_path.rsplit("::", 1)[-1]
            alias = "" if base == name else name
            if (alias or base) in seen_alias:
                continue
            seen_alias.add(alias or base)
            entries.append((rust_path, alias, name))
        exports[resource] = entries
    del models_by_class
    return exports


def resolve_export(reg: Registry, obj: object, models_names: dict[str, str]) -> str | None:
    r = Renderer(reg)
    if is_basemodel_class(obj):
        key = ("class", obj)
        if key in reg.defs:
            return r.def_path(reg.defs[key], None, True)
        return None
    if inspect.isclass(obj) and (obj.__name__.endswith("Param") or obj.__name__.endswith("TypedDict")):
        stem = re.sub(r"(Param|TypedDict)$", "", obj.__name__)
        modname = obj.__module__
        if modname.startswith(MODELS_PKG + "."):
            if stem in models_names.values():
                return f"crate::gaos::models::{stem}"
            return None
        ref = reg.by_modname.get((modname, stem))
        if ref and ref[0] == "def" and ref[1] in reg.defs:
            return r.def_path(reg.defs[ref[1]], None, True)
        return None
    sig = canon(obj)
    if sig in reg.defs:
        return r.def_path(reg.defs[sig], None, True)
    if sig[0] == "class" and ("class", sig[1]) in reg.defs:
        return r.def_path(reg.defs[("class", sig[1])], None, True)
    name = getattr(obj, "__name__", None)
    if is_alias_type(obj) or name:
        # An alias to a TypedDict-style `*Param` union has no Rust twin.
        return None
    return None


def add_signature_exports(
    reg: Registry,
    exports: dict[str, list[tuple[str, str, str]]],
    ops: list[Operation],
    models_names: dict[str, str],
) -> None:
    """Exports every type a resource method takes or returns that the upstream `__all__` omits.

    Python callers pass such values as keyword arguments or dicts and never name the
    type (`CreateInteractionRequestBody`, the update bodies, query-parameter models);
    Rust callers must name it, so it is re-exported under its own name.
    """
    by_resource: dict[str, list[Operation]] = {}
    for op in ops:
        by_resource.setdefault(op.resource, []).append(op)
    for resource, resource_ops in by_resource.items():
        text = render_resource(reg, resource, resource_ops, models_names)
        entries = exports[resource]
        known_paths = {path for path, _alias, _py in entries}
        known_names = {alias or path.rsplit("::", 1)[-1] for path, alias, _py in entries}
        known_names.add(next(iter({o.struct if resource != "environments" else "Environments" for o in resource_ops})))
        for path in sorted(set(re.findall(r"crate::gaos::(?:types|models)::[\w:]+", text))):
            name = path.rsplit("::", 1)[-1]
            if path in known_paths:
                continue
            if name in known_names:
                sys.exit(f"gen_gaos.py: cannot export {path} from crate::{resource}: the name {name} is taken")
            entries.append((path, "", name))
            known_names.add(name)


def render_create_body_keys(reg: Registry) -> str:
    """Wire names of the `Interactions.create` body keys (upstream `_CREATE_BODY_KEYS`)."""
    keys = sorted(
        {f.wire for d in reg.defs.values() if d.kind == "struct" and d.name in {"CreateModelInteraction", "CreateAgentInteraction"} for f in d.fields}
    )
    assert keys, "CreateModelInteraction / CreateAgentInteraction not found"
    body = "".join(f'    "{k}",\n' for k in keys)
    return (
        "\n/// Allowed top-level keys of an `Interactions.create` request body: the union of the\n"
        "/// model and agent shapes (upstream `_CREATE_BODY_KEYS`).\n"
        f"pub(crate) const CREATE_BODY_KEYS: &[&str] = &[\n{body}];\n"
    )


def render_mod_rs(reg: Registry, exports: dict[str, list[tuple[str, str, str]]], ops: list[Operation]) -> str:
    parts = [
        header(),
        "//! The `_gaos` sub-SDK of google-genai: Interactions, agents, environments, triggers,\n"
        "//! webhooks, voices and credentials. Generated by `tools/codegen/gen_gaos.py`; the public\n"
        "//! modules (`crate::agents`, ...) re-export from `exports`.\n\n",
        ALLOW_ATTR,
        "pub mod models;\npub mod resources;\npub mod types;\n\n",
        WIRE_RS,
        render_create_body_keys(reg),
        "\n/// Per-module re-exports mirroring the `__all__` of the upstream public modules.\n",
        "pub mod exports {\n",
    ]
    handle_by_resource: dict[str, str] = {}
    for op in ops:
        handle_by_resource.setdefault(op.resource, op.struct if op.resource != "environments" else "Environments")
    for resource in sorted(exports):
        parts.append(f"    /// Re-exports for `crate::{resource}`.\n    pub mod {resource} {{\n")
        handle = handle_by_resource[resource]
        parts.append(f"        pub use crate::gaos::resources::{resource}::{handle};\n")
        for rust_path, alias, _py in sorted(exports[resource], key=lambda e: (e[1] or e[0], e[0])):
            suffix = f" as {alias}" if alias else ""
            parts.append(f"        pub use {rust_path}{suffix};\n")
        parts.append("    }\n")
    parts.append("}\n")
    return "".join(parts)


# --- fixtures and tests -----------------------------------------------------


class Sampler:
    """Builds deterministic sample JSON for a pydantic class (depth-limited)."""

    MAX_DEPTH = 3

    def sample_class(self, cls: type, depth: int = 0) -> dict:
        out: dict = {}
        for name, finfo in cls.model_fields.items():
            ann, meta, _ = strip(finfo.annotation, list(finfo.metadata))
            if finfo.discriminator is not None:
                meta.append(finfo)
            value = self.sample_value(ann, meta, name, depth, finfo)
            if value is not None:
                out[finfo.alias or name] = value
        return out

    def sample_value(self, ann: object, meta: list, field: str, depth: int, finfo: FieldInfo | None = None):
        ann, meta, _ = strip(ann, meta)
        if is_union(typing.get_origin(ann)):
            present = [m for m in typing.get_args(ann) if m is not NONE_TYPE]
            if len(present) == 1:
                return self.sample_value(present[0], meta, field, depth, finfo)
        sig = canon(ann, meta)
        kind = sig[0]
        if kind == "str":
            if ann is datetime.datetime:
                return "2026-01-01T00:00:00Z"
            return f"sample-{field}"
        if kind == "int":
            return 1
        if kind == "float":
            return 1.5
        if kind == "bool":
            return True
        if kind == "value":
            return {"key": "value"}
        if kind == "enum":
            return sig[1][0] if sig[1] else None
        if kind == "list":
            inner = typing.get_args(ann)[0]
            item = self.sample_value(inner, [], field, depth + 1)
            return [item] if item is not None else []
        if kind == "map":
            inner = typing.get_args(ann)[1]
            item = self.sample_value(inner, [], field, depth + 1)
            return {"key": item} if item is not None else {}
        if kind == "class":
            if depth >= self.MAX_DEPTH:
                return None
            return self.sample_class(ann, depth + 1)  # type: ignore[arg-type]
        if kind == "union":
            info = union_meta(meta)
            members = [m for m in typing.get_args(ann) if m is not NONE_TYPE]
            if info.open and info.unknown is not None:
                members = [m for m in members if m is not info.unknown]
            return self.sample_value(members[0], [], field, depth)
        return None


def dump_sample(cls: type, raw: dict) -> dict:
    """Round-trips `raw` through the upstream model so the fixture is exactly what Python emits."""
    try:
        model = cls.model_validate(raw)
        return model.model_dump(mode="json", by_alias=True, exclude_none=True)
    except Exception:  # noqa: BLE001 - fall back to the raw sample
        return raw


def pick_class(ann: object) -> type | None:
    ann, meta, _ = strip(ann, [])
    sig = canon(ann, meta)
    if sig[0] == "class":
        return sig[1]
    if sig[0] == "union":
        members = [m for m in typing.get_args(ann) if m is not NONE_TYPE]
        info = union_meta(meta)
        if info.open and info.unknown is not None:
            members = [m for m in members if m is not info.unknown]
        return pick_class(members[0])
    return None


def sample_for_op(op: Operation, builder: Builder) -> None:
    sampler = Sampler()
    try:
        _sample_for_op(op, builder, sampler)
    finally:
        # The HTTP layer sends no body for `{}` (as Python does), so there is nothing to match on.
        if op.sample_body == {}:
            op.sample_body = None


def _sample_for_op(op: Operation, builder: Builder, sampler: Sampler) -> None:
    if op.response is not None and op.response[0] == "def":
        d = builder.reg.defs[op.response[1]]
        if d.kind == "struct":
            cls = d.key[1]
            op.sample_response = dump_sample(cls, sampler.sample_class(cls))
    if op.body is not None and op.body.ref[0] == "def":
        d = builder.reg.defs[op.body.ref[1]]
        if d.kind == "struct":
            cls = d.key[1]
            op.sample_body = dump_sample(cls, sampler.sample_class(cls))
        elif d.kind in {"tagged", "untagged"} and d.variants and d.variants[0].ref[0] == "def":
            vd = builder.reg.defs[d.variants[0].ref[1]]
            if vd.kind == "struct":
                cls = vd.key[1]
                op.sample_body = dump_sample(cls, sampler.sample_class(cls))


def fixture_name(op: Operation, suffix: str = "") -> str:
    return f"{op.resource}_{snake(op.name)}{suffix}"


def write_json(path: pathlib.Path, value: object) -> None:
    path.write_text(json.dumps(value, indent=2, sort_keys=True, ensure_ascii=False) + "\n", encoding="utf-8")


def stream_event_sample(op: Operation, builder: Builder) -> object | None:
    """First variant of the stream item union, sampled."""
    if op.stream_response is None or op.stream_response[0] != "def":
        return None
    d = builder.reg.defs[op.stream_response[1]]
    if d.kind == "tagged":
        # The crate's SSE decoder turns `{"error": ...}` payloads into `Error::Api`, so the
        # sample must be a non-error variant.
        for variant in d.variants:
            vd = builder.reg.defs[variant.ref[1]] if variant.ref[0] == "def" else None
            if vd is not None and vd.kind == "struct" and "Error" not in vd.name:
                cls = vd.key[1]
                return dump_sample(cls, Sampler().sample_class(cls))
    if d.kind == "struct":
        return dump_sample(d.key[1], Sampler().sample_class(d.key[1]))
    return None


def render_ops_test(ops: list[Operation], builder: Builder, models_names: dict[str, str]) -> str:
    parts = [
        header(),
        "//! One wiremock test per `_gaos` operation: HTTP verb, path, request body (golden\n"
        "//! fixture) and typed response decoding. Generated from the upstream resource\n"
        "//! classes; fixtures live in `tests/fixtures/gaos/`.\n\n",
        "#![allow(\n"
        "    clippy::pedantic,\n"
        "    clippy::unwrap_used,\n"
        "    clippy::expect_used,\n"
        '    reason = "generated integration tests; failures should panic with the fixture name"\n'
        ")]\n\n",
        "use serde_json::Value;\n"
        "use wiremock::{\n    Mock, MockServer, ResponseTemplate,\n    matchers::{body_json, method, path},\n};\n\n"
        "use crate::common::test_client;\n\n"
        "fn fixture(name: &str) -> Value {\n"
        "    let path = format!(\"{}/tests/fixtures/gaos/{name}.json\", env!(\"CARGO_MANIFEST_DIR\"));\n"
        "    let text = std::fs::read_to_string(&path).expect(\"fixture is readable\");\n"
        "    serde_json::from_str(&text).expect(\"fixture is JSON\")\n"
        "}\n\n",
    ]
    for op in ops:
        for streaming in ([False, True] if op.stream else [False]):
            name = f"{op.name}_stream" if streaming else op.name
            lines: list[str] = []
            test_name = f"{op.resource}_{snake(name)}_sends_{op.verb.lower()}_and_decodes_response"
            tmpl = op.template.removeprefix("/{api_version}")
            url = re.sub(r"\{(\w+)\}", lambda m: f"test-{m.group(1)}", tmpl)
            url = "/v1beta" + url
            call_args = [f'"test-{p.wire}"' for p in op.path_params]
            lines.append("#[tokio::test]")
            lines.append(f"async fn {test_name}() {{")
            lines.append("    let server = MockServer::start().await;")
            mock = f'    let mock = Mock::given(method("{op.verb}")).and(path("{url}"))'
            if op.body is not None and op.sample_body is not None:
                lines.append(f'    let request_body = fixture("{fixture_name(op, "_request")}");')
                mock += ".and(body_json(" + ("wire_stream_body(&request_body)" if streaming else "request_body.clone()") + "))"
            if streaming:
                event = stream_event_sample(op, builder)
                lines.append(f'    let event = fixture("{fixture_name(op, "_event")}");')
                mock += (
                    ".respond_with(ResponseTemplate::new(200)"
                    '.insert_header("content-type", "text/event-stream")'
                    '.set_body_string(format!("data: {event}\\n\\n")))'
                )
                del event
            elif op.response is None:
                mock += ".respond_with(ResponseTemplate::new(200))"
            elif op.sample_response is not None:
                lines.append(f'    let expected = fixture("{fixture_name(op)}");')
                mock += ".respond_with(ResponseTemplate::new(200).set_body_json(&expected))"
            else:
                mock += ".respond_with(ResponseTemplate::new(200).set_body_json(serde_json::json!({})))"
            lines.append(mock + ";")
            lines.append("    mock.expect(1).mount(&server).await;")
            lines.append("    let client = test_client(server.uri());")
            call_parts = list(call_args)
            if op.body is not None:
                if op.sample_body is not None:
                    inner = "serde_json::from_value(request_body.clone()).expect(\"request fixture decodes\")"
                    call_parts.append(f"Some(&{inner})" if op.body_optional else f"&{inner}")
                else:
                    call_parts.append("None" if op.body_optional else "&serde_json::from_value(serde_json::json!({})).expect(\"empty body\")")
            if op.query_params:
                call_parts.append("&Default::default()")
            call = f"client.{op.resource}().{name}({', '.join(call_parts)})"
            if streaming:
                lines.append(f"    let mut events = {call}.await.expect(\"stream opens\");")
                lines.append("    let first = futures_util::StreamExt::next(&mut events)")
                lines.append("        .await")
                lines.append("        .expect(\"one event\")")
                lines.append("        .expect(\"event decodes\");")
                lines.append("    assert_eq!(serde_json::to_value(&first).expect(\"event serializes\"), event);")
            elif op.response is None:
                lines.append(f"    {call}.await.expect(\"call succeeds\");")
            else:
                lines.append(f"    let response = {call}.await.expect(\"call succeeds\");")
                if op.sample_response is not None:
                    lines.append(
                        "    assert_eq!(serde_json::to_value(&response).expect(\"response serializes\"), expected);"
                    )
                else:
                    lines.append("    let _ = response;")
            lines.append("}\n")
            parts.append("\n".join(lines) + "\n")
    out = "".join(parts)
    if "wire_stream_body" in out:
        out = out.replace(
            "fn fixture(name: &str)",
            "fn wire_stream_body(body: &Value) -> Value {\n"
            "    let mut body = body.clone();\n"
            "    body[\"stream\"] = Value::Bool(true);\n"
            "    body\n"
            "}\n\n"
            "fn fixture(name: &str)",
            1,
        )
    return out


# --- methods_gaos.toml ------------------------------------------------------


def toml_str(text: str) -> str:
    return json.dumps(text, ensure_ascii=False)


def render_methods_toml(ops: list[Operation], reg: Registry, models_names: dict[str, str]) -> str:
    r = Renderer(reg)
    lines = [
        "# @generated by tools/codegen/gen_gaos.py. DO NOT EDIT.",
        "# Method inventory of the `_gaos` surface; read by gen_blocking.py and gen_parity.py",
        "# alongside methods.toml (see that file's header for the field meanings).",
        "",
    ]
    seen_modules: set[str] = set()
    for op in ops:
        if op.resource in seen_modules:
            continue
        seen_modules.add(op.resource)
        struct = op.struct if op.resource != "environments" else "Environments"
        lines += [
            "[[client_module]]",
            f'name = "{op.resource}"',
            f'owner = "crate::gaos::resources::{op.resource}::{struct}"',
            f'struct = "{struct}"',
            "",
        ]
    for op in ops:
        struct = op.struct if op.resource != "environments" else "Environments"
        owner = f"crate::gaos::resources::{op.resource}::{struct}"
        args = [f"{n}: {t}" for n, t in op_signature_args(r, op, models_names)]
        ret = "()" if op.response is None else r.rust_type(op.response, None, absolute=True)
        path = op.template.removeprefix("/{api_version}/")
        for streaming in ([False, True] if op.stream else [False]):
            name = f"{op.name}_stream" if streaming else op.name
            lines += [
                "[[method]]",
                f'module = "{op.resource}"',
                f'owner = "{owner}"',
                f'name = "{name}"',
                f'python = "{op.python}"',
                "args = [" + ", ".join(toml_str(a) for a in args) + "]",
                "ret = "
                + toml_str(
                    r.rust_type(op.stream_response, None, absolute=True) if streaming else ret  # type: ignore[arg-type]
                ),
                f'kind = "{"stream" if streaming else "unary"}"',
                f'path = "{path}"',
                f'http = "{op.verb}"',
                "",
            ]
    return "\n".join(lines)


# --- README for fixtures ----------------------------------------------------


def fixtures_readme() -> str:
    return f"""<!-- @generated by tools/codegen/gen_gaos.py from google-genai {GENAI_VERSION}. DO NOT EDIT.
     Edit tools/codegen/gen_gaos.py and re-run
     `python tools/codegen/generate.py --only gaos` instead.
{attribution.html_attribution("gen_gaos.py", GENAI_VERSION, modified=_MODIFIED)}-->

# `_gaos` golden fixtures

Every `*.json` file here is a sample request body, response body or stream event of one
`_gaos` operation, built from the upstream pydantic models
({attribution.UPSTREAM_NAME} {GENAI_VERSION}, <{attribution.UPSTREAM_URL}>,
Copyright {attribution.UPSTREAM_COPYRIGHT}, {attribution.LICENSE_NAME}) and round-tripped
through them (`model_validate` then `model_dump`) so the bytes are what the Python SDK emits.
`tests/gaos/generated_ops.rs` replays them against wiremock.

JSON has no comment syntax, so the attribution is stated once here for the directory.
Regenerate with `python tools/codegen/generate.py --only gaos`.
"""


# --- driver -----------------------------------------------------------------


def write_text(path: pathlib.Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def check_unmapped(builder: Builder) -> int:
    recorded = builder.reg.overrides.get("unmapped", {})
    found = {key: reason for key, reason in builder.unmapped}
    missing = sorted(set(found) - set(recorded))
    stale = sorted(set(recorded) - set(found))
    if missing or stale:
        print("gen_gaos.py: gaos_overrides.toml [unmapped] is out of date.", file=sys.stderr)
        for key in missing:
            print(f'  missing: [unmapped."{key}"]  # {found[key]}', file=sys.stderr)
        for key in stale:
            print(f"  stale:   {key}", file=sys.stderr)
        sys.exit(1)
    recorded_count = builder.reg.overrides.get("unmapped_count")
    if recorded_count != len(found):
        sys.exit(
            f"gen_gaos.py: gaos_overrides.toml records unmapped_count = {recorded_count}, "
            f"but {len(found)} fields are unmapped"
        )
    if len(found) > UNMAPPED_LIMIT:
        sys.exit(f"gen_gaos.py: {len(found)} unmapped fields exceed the limit of {UNMAPPED_LIMIT}")
    return len(found)


def main() -> None:
    builder = Builder()
    builder.build()
    ops = parse_resources(builder)
    # Operation parsing may register further types (inline enums in query params).
    builder.finalize_names()
    builder.box_cycles()
    reg = builder.reg
    unmapped_count = check_unmapped(builder)

    for op in ops:
        sample_for_op(op, builder)

    models_rs, models_names = render_models_rs(reg, ops)
    exports = public_exports(reg, models_names, ops)
    add_signature_exports(reg, exports, ops, models_names)

    write_text(OUT_SRC / "types.rs", render_types_rs(reg))
    write_text(OUT_SRC / "models.rs", models_rs)
    write_text(OUT_SRC / "mod.rs", render_mod_rs(reg, exports, ops))

    by_resource: dict[str, list[Operation]] = {}
    for op in ops:
        by_resource.setdefault(op.resource, []).append(op)
    resources_mod = [header(), "//! Resource handles of the `_gaos` sub-SDK, one module per resource.\n\n", ALLOW_ATTR]
    for resource in sorted(by_resource):
        resources_mod.append(f"pub mod {resource};\n")
        write_text(OUT_RESOURCES / f"{resource}.rs", render_resource(reg, resource, by_resource[resource], models_names))
    write_text(OUT_RESOURCES / "mod.rs", "".join(resources_mod))

    # fixtures
    OUT_FIXTURES.mkdir(parents=True, exist_ok=True)
    for old in OUT_FIXTURES.glob("*.json"):
        old.unlink()
    for op in ops:
        if op.sample_response is not None:
            write_json(OUT_FIXTURES / f"{fixture_name(op)}.json", op.sample_response)
        if op.sample_body is not None:
            write_json(OUT_FIXTURES / f"{fixture_name(op, '_request')}.json", op.sample_body)
        if op.stream:
            event = stream_event_sample(op, builder)
            if event is not None:
                write_json(OUT_FIXTURES / f"{fixture_name(op, '_event')}.json", event)
    write_text(OUT_FIXTURES / "README.md", fixtures_readme())
    write_text(OUT_TESTS / "generated_ops.rs", render_ops_test(ops, builder, models_names))
    write_text(METHODS_GAOS_TOML, render_methods_toml(ops, reg, models_names))

    n_struct = sum(1 for d in reg.defs.values() if d.kind == "struct")
    print(
        f"gen_gaos.py: {len(reg.defs)} types ({n_struct} structs), {len(ops)} operations, "
        f"{unmapped_count} unmapped fields (google-genai {GENAI_VERSION})",
        file=sys.stderr,
    )


if __name__ == "__main__":
    main()
