#!/usr/bin/env python3
"""Transpiles google-genai's `_X_to_mldev`/`_X_from_mldev` converter
functions into Rust, by walking their Python AST.

Scope: only functions named `_<Name>_to_mldev` / `_<Name>_from_mldev`
(Gemini Developer API request/response shaping) are transpiled; `_to_vertex`
/ `_from_vertex` functions are out of scope (Vertex AI is a later feature).
`api_client` arguments are dropped everywhere they appear (as a function
parameter or a call argument): the Python versions only use it to forward
to `t.t_xxx(api_client, ...)` / `base_t.t_xxx(api_client, ...)` for
Vertex-vs-mldev branching, and this crate's `crate::transformers::t_*` are
mldev-only.

See specs/001-port-genai-rust/contracts/codegen.md "gen_converters.py" and
research.md R-05. DO NOT hand-edit the generated output; edit this script
(or add a `tools/codegen/converter_overrides/<fn>.rs` file for a function
this script cannot transpile) and re-run
`python tools/codegen/generate.py --only converters`.
"""

from __future__ import annotations

import ast
import pathlib
import re
import sys

REPO_ROOT = pathlib.Path(__file__).resolve().parents[2]
OUT_DIR = REPO_ROOT / "src" / "converters" / "generated"
OVERRIDES_DIR = pathlib.Path(__file__).resolve().parent / "converter_overrides"

# module name (used for the Rust output file) -> Python source file.
TARGET_FILES = {
    "models": "models.py",
    "chats": "chats.py",
    "caches": "caches.py",
    "files": "files.py",
    "tunings": "tunings.py",
    "batches": "batches.py",
    "operations": "operations.py",
    "file_search_stores": "file_search_stores.py",
    "documents": "documents.py",
    "operations_converters": "_operations_converters.py",
    "tokens_converters": "_tokens_converters.py",
    "live_converters": "_live_converters.py",
}

GENAI_VERSION = "2.19.0"

TRANSFORMER_MODULE_ALIASES = {"t", "base_t"}


def header(doc: str) -> str:
    return (
        f"// @generated by tools/codegen/gen_converters.py from google-genai {GENAI_VERSION}. DO NOT EDIT.\n"
        "// Edit tools/codegen/gen_converters.py (or add a converter_overrides/<fn>.rs\n"
        "// file) and re-run `python tools/codegen/generate.py --only converters` instead.\n"
        f"{doc}"
        "#![allow(clippy::all, clippy::pedantic, missing_docs, non_snake_case, dead_code, unused_imports, unused_variables, unused_mut, reason = \"1:1 generated port of google-genai's _to_mldev/_from_mldev converters; several are Vertex-AI-only and unused by this Gemini Developer API port, and pedantic-tier style lints don't apply to mechanically transpiled code\")]\n\n"
        "use serde_json::{Map, Value};\n\n"
        "use crate::converters::{getv, setv, vertex_only_error};\n"
        "use crate::error::Result;\n"
        "use crate::transformers as t;\n\n"
    )


FUNC_NAME_RE = re.compile(r"^_[A-Za-z0-9]+_(to|from)_mldev$")


class Unsupported(Exception):
    def __init__(self, func_name: str, node: ast.AST, reason: str) -> None:
        line = getattr(node, "lineno", "?")
        super().__init__(f"{func_name} (line {line}): {reason}")


def to_snake(name: str) -> str:
    name = name.lstrip("_")
    out = []
    for i, ch in enumerate(name):
        if ch.isupper() and i > 0 and (name[i - 1].islower() or name[i - 1].isdigit()):
            out.append("_")
        out.append(ch.lower())
    return "".join(out)


def unparse_string_list(node: ast.AST, func_name: str) -> list[str]:
    if not isinstance(node, ast.List):
        raise Unsupported(func_name, node, "expected a list literal of string keys")
    keys = []
    for elt in node.elts:
        if not isinstance(elt, ast.Constant) or not isinstance(elt.value, str):
            raise Unsupported(func_name, node, "expected string literal keys")
        keys.append(elt.value)
    return keys


def rust_key_slice(keys: list[str]) -> str:
    items = ", ".join(f'"{k}"' for k in keys)
    return f"&[{items}]"


def is_call_to(node: ast.AST, name: str) -> bool:
    return isinstance(node, ast.Call) and isinstance(node.func, ast.Name) and node.func.id == name


def is_getv_call(node: ast.AST) -> bool:
    return is_call_to(node, "getv")


def is_transformer_call(node: ast.AST) -> bool:
    return (
        isinstance(node, ast.Call)
        and isinstance(node.func, ast.Attribute)
        and isinstance(node.func.value, ast.Name)
        and node.func.value.id in TRANSFORMER_MODULE_ALIASES
    )


def is_nested_converter_call(node: ast.AST) -> bool:
    return isinstance(node, ast.Call) and isinstance(node.func, ast.Name) and node.func.id.startswith("_")


def drop_leading_api_client(args: list[ast.expr]) -> list[ast.expr]:
    if args and isinstance(args[0], ast.Name) and args[0].id == "api_client":
        return args[1:]
    return args


class FunctionTranspiler:
    def __init__(self, func_name: str, has_root_param: bool, known_functions: dict[str, str]) -> None:
        self.func_name = func_name
        self.has_root_param = has_root_param
        self.known_functions = known_functions

    def qualified_callee(self, python_name: str, node: ast.AST) -> str:
        rust_name = to_snake(python_name)
        module = self.known_functions.get(rust_name)
        if module is None:
            raise Unsupported(self.func_name, node, f"call to unknown converter function `{python_name}`")
        return f"crate::converters::generated::{module}::{rust_name}"

    def target_expr(self, target_name: str) -> str:
        if target_name == "to_object":
            return "Some(&mut to_object)"
        if target_name == "parent_object":
            return "parent_object.as_deref_mut()"
        raise Unsupported(self.func_name, ast.Constant(value=None), f"unknown setv target `{target_name}`")

    def transpile_data_arg(self, node: ast.AST) -> str:
        """Transpiles the first argument of a `getv(...)` call, which is
        always one of `from_object`, `to_object`, `parent_object`, or
        `root_object` (a Python identifier)."""
        if not isinstance(node, ast.Name):
            raise Unsupported(self.func_name, node, "getv's data argument must be a bare identifier")
        if node.id == "from_object":
            return "Some(from_object)"
        if node.id == "to_object":
            return "Some(&to_object)"
        if node.id == "parent_object":
            return "parent_object.as_deref()"
        if node.id == "root_object":
            return "root_object"
        raise Unsupported(self.func_name, node, f"unexpected getv data argument `{node.id}`")

    def transpile_expr(self, node: ast.AST) -> str:
        if is_getv_call(node):
            call = node
            assert isinstance(call, ast.Call)
            data_expr = self.transpile_data_arg(call.args[0])
            keys = unparse_string_list(call.args[1], self.func_name)
            return f"getv({data_expr}, {rust_key_slice(keys)}).unwrap_or(Value::Null)"

        if isinstance(node, ast.Constant):
            if isinstance(node.value, str):
                return f'Value::String("{node.value}".to_owned())'
            if isinstance(node.value, bool):
                return f"Value::Bool({str(node.value).lower()})"
            if node.value is None:
                return "Value::Null"
            raise Unsupported(self.func_name, node, f"unsupported constant {node.value!r}")

        if isinstance(node, ast.ListComp):
            return self.transpile_list_comp(node)

        if is_transformer_call(node) or is_nested_converter_call(node):
            assert isinstance(node, ast.Call)
            return self.transpile_call_expr(node)

        raise Unsupported(self.func_name, node, f"unsupported expression: {ast.dump(node)}")

    def transpile_call_expr(self, node: ast.Call) -> str:
        if is_transformer_call(node):
            func = node.func
            assert isinstance(func, ast.Attribute)
            args = drop_leading_api_client(list(node.args))
            rust_args = ", ".join(self.transpile_value_producing_expr(a) for a in args)
            return f"t::{to_snake(func.attr)}({rust_args})?"

        if is_nested_converter_call(node):
            return self.transpile_nested_converter_call(node)

        raise Unsupported(self.func_name, node, f"unsupported call: {ast.dump(node.func)}")

    def transpile_value_producing_expr(self, node: ast.AST) -> str:
        """Transpiles an expression that must produce a plain (non-Result)
        Rust `Value`, e.g. an argument to a `t::t_xxx` transformer or a
        list comprehension's iterable."""
        if is_getv_call(node) or is_transformer_call(node) or is_nested_converter_call(node):
            return self.transpile_expr(node)
        if isinstance(node, ast.Constant) and isinstance(node.value, str):
            return f'Value::String("{node.value}".to_owned())'
        if isinstance(node, ast.Name) and node.id == "item":
            # Only valid inside a list-comprehension body (see
            # transpile_list_comp), where `item` is the Rust for-loop's
            # bound `Value`.
            return "item.clone()"
        raise Unsupported(self.func_name, node, f"unsupported value-producing expression: {ast.dump(node)}")

    def transpile_nested_converter_call(self, node: ast.Call) -> str:
        assert isinstance(node.func, ast.Name)
        callee = self.qualified_callee(node.func.id, node)
        args = drop_leading_api_client(list(node.args))
        if len(args) not in (1, 2, 3):
            raise Unsupported(self.func_name, node, f"nested converter call with {len(args)} args")

        item_expr = self.transpile_value_producing_expr(args[0])
        parent_expr = "None"
        if len(args) >= 2:
            parent_arg = args[1]
            if isinstance(parent_arg, ast.Name) and parent_arg.id in ("to_object", "parent_object"):
                parent_expr = self.target_expr(parent_arg.id)
            elif isinstance(parent_arg, ast.Constant) and parent_arg.value is None:
                parent_expr = "None"
            else:
                raise Unsupported(self.func_name, node, "nested call's parent argument must be to_object/parent_object/None")
        root_expr = "None"
        if len(args) == 3:
            root_arg = args[2]
            if isinstance(root_arg, ast.Name) and root_arg.id == "root_object":
                root_expr = "root_object"
            else:
                raise Unsupported(self.func_name, node, "nested call's root argument must be root_object")

        return f"{callee}(&({item_expr}), {parent_expr}, {root_expr})?"

    def transpile_list_comp(self, node: ast.ListComp) -> str:
        if len(node.generators) != 1 or node.generators[0].ifs:
            raise Unsupported(self.func_name, node, "only single-clause `for item in ITER` comprehensions are supported")
        gen = node.generators[0]
        if not (isinstance(gen.target, ast.Name) and gen.target.id == "item"):
            raise Unsupported(self.func_name, node, "comprehension loop variable must be named `item`")

        iter_expr = self.transpile_value_producing_expr(gen.iter)

        elt = node.elt
        if isinstance(elt, ast.Name) and elt.id == "item":
            # `[item for item in EXPR]` -- a no-op re-collection.
            return iter_expr

        if is_nested_converter_call(elt):
            assert isinstance(elt, ast.Call) and isinstance(elt.func, ast.Name)
            callee = self.qualified_callee(elt.func.id, elt)
            args = drop_leading_api_client(list(elt.args))
            first_arg = args[0]
            if isinstance(first_arg, ast.Name) and first_arg.id == "item":
                item_expr = "item.clone()"
            elif is_transformer_call(first_arg):
                # e.g. `_Tool_to_mldev(t.t_tool(api_client, item), ...)`:
                # the loop item is pre-transformed before being converted.
                item_expr = self.transpile_value_producing_expr(first_arg)
            else:
                raise Unsupported(self.func_name, node, "comprehension call's first argument must be `item` (optionally transformer-wrapped)")
            parent_expr = "None"
            if len(args) >= 2:
                parent_arg = args[1]
                if isinstance(parent_arg, ast.Name) and parent_arg.id in ("to_object", "parent_object"):
                    parent_expr = self.target_expr(parent_arg.id)
            root_expr = "None"
            if len(args) == 3 and isinstance(args[2], ast.Name) and args[2].id == "root_object":
                root_expr = "root_object"
            return (
                "{ let mut __out: Vec<Value> = Vec::new(); "
                f"for item in ({iter_expr}).as_array().cloned().unwrap_or_default() {{ "
                f"__out.push({callee}(&({item_expr}), {parent_expr}, {root_expr})?); "
                "} Value::Array(__out) }"
            )

        raise Unsupported(self.func_name, node, f"unsupported comprehension element: {ast.dump(elt)}")

    def transpile_stmt(self, node: ast.stmt) -> list[str]:
        if isinstance(node, ast.If):
            return self.transpile_if(node)
        if isinstance(node, ast.Return):
            return []  # `return to_object` is implicit; emitted once at the end.
        if isinstance(node, ast.Assign) and self.is_to_object_init(node):
            return []  # `to_object: dict[str, Any] = {}` is implicit.
        if isinstance(node, ast.AnnAssign) and self.is_to_object_init(node):
            return []
        if isinstance(node, ast.Expr) and isinstance(node.value, ast.Constant):
            return []  # stray docstring/no-op expression statement.
        if isinstance(node, ast.Expr) and is_call_to(node.value, "setv"):
            # An unconditional (unguarded) `setv(...)` call.
            call = node.value
            target_node = call.args[0]
            if not isinstance(target_node, ast.Name):
                raise Unsupported(self.func_name, node, "setv's target must be a bare identifier")
            target = self.target_expr(target_node.id)
            keys = unparse_string_list(call.args[1], self.func_name)
            value_expr = self.transpile_expr(call.args[2])
            # Bind the value first: `value_expr` may itself borrow
            # `to_object`/`parent_object` mutably (e.g. a nested converter
            # call using the same variable as its own parent), which would
            # otherwise conflict with `target`'s mutable borrow within one
            # call expression.
            return [f"let __v = {value_expr}; setv({target}, {rust_key_slice(keys)}, __v)?;"]
        raise Unsupported(self.func_name, node, f"unsupported statement: {ast.dump(node)}")

    @staticmethod
    def is_to_object_init(node: ast.stmt) -> bool:
        target = node.targets[0] if isinstance(node, ast.Assign) else node.target if isinstance(node, ast.AnnAssign) else None
        return isinstance(target, ast.Name) and target.id == "to_object"

    def transpile_bare_nested_call_stmt(self, node: ast.Call) -> str:
        """`_XConfig_to_mldev(getv(from_object, ['config']), to_object[, root_object])`
        as a bare statement: a "Parameters" wrapper delegating its
        flattening entirely to a nested converter's side effects on
        to_object/parent_object, discarding that converter's own return
        value."""
        assert isinstance(node.func, ast.Name)
        callee = self.qualified_callee(node.func.id, node)
        args = drop_leading_api_client(list(node.args))
        if not args:
            raise Unsupported(self.func_name, node, "bare nested call needs at least one argument")
        item_expr = self.transpile_value_producing_expr(args[0])
        parent_expr = "None"
        if len(args) >= 2:
            parent_arg = args[1]
            if isinstance(parent_arg, ast.Name) and parent_arg.id in ("to_object", "parent_object"):
                parent_expr = self.target_expr(parent_arg.id)
        root_expr = "None"
        if len(args) == 3 and isinstance(args[2], ast.Name) and args[2].id == "root_object":
            root_expr = "root_object"
        return f"{callee}(&({item_expr}), {parent_expr}, {root_expr})?;"

    @staticmethod
    def is_enum_validate_call(stmt: ast.stmt) -> bool:
        return (
            isinstance(stmt, ast.Expr)
            and isinstance(stmt.value, ast.Call)
            and isinstance(stmt.value.func, ast.Name)
            and stmt.value.func.id.endswith("_enum_validate")
        )

    def transpile_if(self, node: ast.If) -> list[str]:
        if node.orelse:
            raise Unsupported(self.func_name, node, "if/else is not supported (no `_mldev` converter uses it)")
        test = node.test
        if not (isinstance(test, ast.Compare) and is_getv_call(test.left) and len(test.ops) == 1 and isinstance(test.ops[0], ast.IsNot)):
            raise Unsupported(self.func_name, node, "if-guard must be `getv(...) is not None`")

        guard_call = test.left
        assert isinstance(guard_call, ast.Call)
        guard_data = self.transpile_data_arg(guard_call.args[0])
        guard_keys = unparse_string_list(guard_call.args[1], self.func_name)
        guard = f"getv({guard_data}, {rust_key_slice(guard_keys)}).is_some()"

        body = node.body
        if len(body) == 2 and self.is_enum_validate_call(body[0]):
            # `_XEnum_to_mldev_enum_validate(getv(...))` followed by the
            # real statement: the validator only raises on an unrecognized
            # enum value, which this crate's generated enums already
            # tolerate via their `Unknown(String)` fallback variant, so the
            # validation call itself is dropped.
            body = body[1:]
        if len(body) != 1:
            raise Unsupported(self.func_name, node, "if-body must be a single statement")
        inner = body[0]

        if isinstance(inner, ast.Raise):
            field = ".".join(guard_keys)
            return [f'if {guard} {{ return Err(vertex_only_error("{field}")); }}']

        if isinstance(inner, ast.Expr) and is_call_to(inner.value, "setv"):
            call = inner.value
            assert isinstance(call, ast.Call)
            target_node = call.args[0]
            if not isinstance(target_node, ast.Name):
                raise Unsupported(self.func_name, node, "setv's target must be a bare identifier")
            target = self.target_expr(target_node.id)
            keys = unparse_string_list(call.args[1], self.func_name)
            value_expr = self.transpile_expr(call.args[2])
            # See the matching comment in `transpile_stmt`'s unconditional
            # setv case: binding first avoids a double mutable borrow when
            # `value_expr` itself borrows `to_object`/`parent_object`.
            return [f"if {guard} {{ let __v = {value_expr}; setv({target}, {rust_key_slice(keys)}, __v)?; }}"]

        if isinstance(inner, ast.Expr) and is_nested_converter_call(inner.value):
            assert isinstance(inner.value, ast.Call)
            stmt = self.transpile_bare_nested_call_stmt(inner.value)
            return [f"if {guard} {{ {stmt} }}"]

        raise Unsupported(self.func_name, node, f"unsupported if-body: {ast.dump(inner)}")

    def transpile(self, func: ast.FunctionDef) -> str:
        body_lines: list[str] = []
        for stmt in func.body:
            body_lines.extend(self.transpile_stmt(stmt))

        rust_name = to_snake(func.name)
        root_param = "root_object: Option<&Value>" if self.has_root_param else "_root_object: Option<&Value>"
        lines = [
            f"pub(crate) fn {rust_name}(",
            "    from_object: &Value,",
            "    mut parent_object: Option<&mut Value>,",
            f"    {root_param},",
            ") -> Result<Value> {",
            "    let mut to_object = Value::Object(Map::new());",
            *(f"    {line}" for line in body_lines),
            "    Ok(to_object)",
            "}",
        ]
        return "\n".join(lines)


def function_has_root_param(func: ast.FunctionDef) -> bool:
    names = {a.arg for a in func.args.args}
    return "root_object" in names


def find_target_functions(tree: ast.Module) -> list[ast.FunctionDef]:
    return [node for node in ast.walk(tree) if isinstance(node, ast.FunctionDef) and FUNC_NAME_RE.match(node.name)]


def build_known_functions(sdk_dir: pathlib.Path) -> dict[str, str]:
    """Maps every `_X_to_mldev`/`_X_from_mldev` function's Rust (snake_case)
    name to the Rust module it will live in, across *all* target files --
    needed because e.g. `_Part_to_mldev` (defined once, in models.py) is
    called from converters in caches.py, batches.py, etc."""
    known: dict[str, str] = {}
    for module_name, filename in TARGET_FILES.items():
        source_path = sdk_dir / filename
        if not source_path.exists():
            continue
        tree = ast.parse(source_path.read_text(encoding="utf-8"), filename=str(source_path))
        for func in find_target_functions(tree):
            known[to_snake(func.name)] = module_name
    return known


def transpile_module(
    module_name: str, source_path: pathlib.Path, known_functions: dict[str, str]
) -> tuple[str, int, list[str]]:
    tree = ast.parse(source_path.read_text(encoding="utf-8"), filename=str(source_path))
    functions = find_target_functions(tree)

    rendered: list[str] = []
    failures: list[str] = []
    for func in functions:
        override_path = OVERRIDES_DIR / f"{to_snake(func.name)}.rs"
        if override_path.exists():
            rendered.append(f"// override: {override_path.name}\n" + override_path.read_text(encoding="utf-8"))
            continue
        try:
            transpiler = FunctionTranspiler(func.name, function_has_root_param(func), known_functions)
            rendered.append(transpiler.transpile(func))
        except Unsupported as exc:
            failures.append(str(exc))

    doc = f"//! Generated from {len(functions)} converter function(s) in `{source_path.name}`.\n\n"
    body = header(doc)
    body += "\n\n".join(rendered)
    body += "\n"
    return body, len(functions), failures


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    sdk_dir = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else None
    if sdk_dir is None:
        import google.genai  # noqa: PLC0415

        sdk_dir = pathlib.Path(google.genai.__file__).parent

    known_functions = build_known_functions(sdk_dir)

    total_functions = 0
    all_failures: list[str] = []
    mod_lines = ["//! Generated converter modules. See each file for its source module.\n\n"]

    for module_name, filename in TARGET_FILES.items():
        source_path = sdk_dir / filename
        if not source_path.exists():
            print(f"gen_converters.py: skipping {filename} (not found under {sdk_dir})", file=sys.stderr)
            continue
        body, count, failures = transpile_module(module_name, source_path, known_functions)
        (OUT_DIR / f"{module_name}.rs").write_text(body, encoding="utf-8")
        mod_lines.append(f"pub(crate) mod {module_name};\n")
        total_functions += count
        all_failures.extend(failures)

    (OUT_DIR / "mod.rs").write_text("".join(mod_lines), encoding="utf-8")

    ok = total_functions - len(all_failures)
    print(f"gen_converters.py: transpiled {ok}/{total_functions} functions", file=sys.stderr)
    if all_failures:
        print(f"gen_converters.py: {len(all_failures)} unsupported (left out of generated output):", file=sys.stderr)
        for f in all_failures:
            print(f"  - {f}", file=sys.stderr)


if __name__ == "__main__":
    main()
