#!/usr/bin/env python3
"""Reads `methods.toml` and emits `src/blocking/generated.rs`: one thin
`blocking::<struct>` wrapper per `[[client_module]]` entry (`Models`,
`Chats`, `Files`, ...), each holding a shared `Arc<blocking::Runtime>` plus
the wrapped async handle, and one blocking method per `[[method]]` entry
whose `kind` is `unary`, `stream`, `pager`, or `upload`.

`kind = "session"` (methods on `crate::chats::Chat`, plus `Chats::create`
itself) and `kind = "manual"` (`Operations::get<T>`, generic over `T`;
`FileSearchStores::documents()`, a nested-handle accessor rather than an API
call) are intentionally skipped -- `src/blocking/mod.rs` hand-writes those.
See `methods.toml`'s header comment for the full rationale.

See specs/001-port-genai-rust/contracts/codegen.md, "methods.toml /
gen_blocking.py / gen_parity.py". DO NOT hand-edit the generated output;
edit this script (or `methods.toml`) and re-run
`python tools/codegen/generate.py --only blocking` instead.
"""

from __future__ import annotations

import attribution
import upstream

import pathlib
import sys
from typing import Any

try:
    import tomllib
except ModuleNotFoundError:  # Python < 3.11
    import tomli as tomllib  # type: ignore[no-redef]

REPO_ROOT = pathlib.Path(__file__).resolve().parents[2]
METHODS_TOML = pathlib.Path(__file__).resolve().parent / "methods.toml"
OUT_DIR = REPO_ROOT / "src" / "blocking"

GENAI_VERSION = upstream.PINNED_VERSION

# `kind`s this generator actually emits a wrapper method for. `session` and
# `manual` are valid `kind`s in methods.toml but are hand-written instead
# (see the module docstring).
GENERATED_KINDS = {"unary", "upload", "stream", "pager"}
SKIPPED_KINDS = {"session", "manual"}

HEADER = (
    f"// @generated by tools/codegen/gen_blocking.py from methods.toml. DO NOT EDIT.\n"
    + attribution.rust_attribution(
        "gen_blocking.py",
        GENAI_VERSION,
        modified=(
            "the method inventory in `methods.toml` is derived from the upstream\n"
            "SDK's public API surface; gen_blocking.py generates blocking wrappers\n"
            "over this crate's own async port of it."
        ),
    )
    + "// Edit tools/codegen/gen_blocking.py (or tools/codegen/methods.toml) and\n"
    "// re-run `python tools/codegen/generate.py --only blocking` instead.\n"
    f"//! Blocking (`feature = \"blocking\"`) wrappers for every `Client`-accessor\n"
    f"//! module's async methods, generated from `tools/codegen/methods.toml`\n"
    f"//! against google-genai {GENAI_VERSION}'s method inventory. `Chat` (returned by\n"
    "//! `Chats::create`), `Operations::get<T>`, and `FileSearchStores::documents()`\n"
    "//! are hand-written in `src/blocking/mod.rs` instead -- see that file and\n"
    "//! `methods.toml`'s header comment.\n\n"
    "#![allow(\n"
    "    clippy::pedantic,\n"
    "    dead_code,\n"
    "    reason = \"mechanically generated 1:1 blocking wrappers around this crate's own async API; pedantic-tier style lints don't apply, and not every wrapper method is necessarily exercised by every feature combination\"\n"
    ")]\n\n"
)


def parse_args(args: list[str]) -> list[tuple[str, str]]:
    parsed = []
    for arg in args:
        if ": " not in arg:
            sys.exit(f"methods.toml: malformed arg {arg!r} (expected 'name: type')")
        name, ty = arg.split(": ", 1)
        parsed.append((name, ty))
    return parsed


def render_method(m: dict[str, Any]) -> str:
    name = m["name"]
    owner = m["owner"]
    ret = m["ret"]
    kind = m["kind"]
    python = m.get("python") or None
    deprecated = bool(m.get("deprecated", False))
    parsed_args = parse_args(m.get("args", []))

    sig_args = "".join(f", {n}: {t}" for n, t in parsed_args)
    call_args = ", ".join(n for n, _ in parsed_args)

    doc_first_line = f"    /// Blocking wrapper for [`{owner}::{name}`]"
    doc_first_line += f" (Python `{python}`).\n" if python else ".\n"
    doc = (
        f"{doc_first_line}"
        "    ///\n"
        "    /// # Errors\n"
        "    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]\n"
        "    /// if called from inside an already-running Tokio runtime.\n"
    )
    attr = (
        '    #[expect(deprecated, reason = "parity wrapper around the deprecated async method")]\n'
        if deprecated
        else ""
    )

    if kind in ("unary", "upload"):
        ret_ty = f"crate::error::Result<{ret}>"
        body = f"        self.runtime.block_on(self.inner.{name}({call_args}))?"
    elif kind == "stream":
        ret_ty = f"crate::error::Result<crate::blocking::BlockingStream<{ret}>>"
        body = (
            # Two `?`s: `block_on` returns `Result<F::Output>` where
            # `F::Output` is itself the wrapped async method's
            # `Result<Stream, Error>` -- the first `?` handles
            # `BlockingInsideRuntime`, the second the async call's own
            # error, leaving the bare stream to wrap.
            f"        let stream = self.runtime.block_on(self.inner.{name}({call_args}))??;\n"
            "        Ok(crate::blocking::BlockingStream::new(\n"
            "            std::sync::Arc::clone(&self.runtime),\n"
            "            stream,\n"
            "        ))"
        )
    elif kind == "pager":
        ret_ty = f"crate::error::Result<crate::blocking::Pager<{ret}>>"
        body = (
            f"        let pager = self.runtime.block_on(self.inner.{name}({call_args}))??;\n"
            "        Ok(crate::blocking::Pager::new(\n"
            "            std::sync::Arc::clone(&self.runtime),\n"
            "            pager,\n"
            "        ))"
        )
    else:  # pragma: no cover - guarded by main()'s validation pass
        sys.exit(f"gen_blocking.py: unhandled generated kind {kind!r} for {owner}::{name}")

    return f"{doc}{attr}    pub fn {name}(&self{sig_args}) -> {ret_ty} {{\n{body}\n    }}\n\n"


def render_struct(cm: dict[str, Any], methods: list[dict[str, Any]]) -> str:
    struct = cm["struct"]
    owner = cm["owner"]
    name = cm["name"]
    method_bodies = "".join(
        render_method(m) for m in methods if m["kind"] in GENERATED_KINDS
    )
    return (
        f"/// Blocking wrapper for [`{owner}`] (`client.{name}()`).\n"
        f"pub struct {struct} {{\n"
        "    pub(crate) runtime: std::sync::Arc<crate::blocking::Runtime>,\n"
        f"    pub(crate) inner: {owner},\n"
        "}\n\n"
        f"impl {struct} {{\n"
        "    pub(crate) fn new(\n"
        "        runtime: std::sync::Arc<crate::blocking::Runtime>,\n"
        f"        inner: {owner},\n"
        "    ) -> Self {\n"
        "        Self { runtime, inner }\n"
        "    }\n\n"
        f"{method_bodies}"
        "}\n"
    )


def main() -> None:
    data = tomllib.loads(METHODS_TOML.read_text(encoding="utf-8"))
    client_modules: list[dict[str, Any]] = data.get("client_module", [])
    methods: list[dict[str, Any]] = data.get("method", [])

    unknown_kinds = {m["kind"] for m in methods} - GENERATED_KINDS - SKIPPED_KINDS
    if unknown_kinds:
        sys.exit(f"methods.toml: unknown kind(s) {sorted(unknown_kinds)}")

    known_owners = {cm["owner"] for cm in client_modules}
    for m in methods:
        if m["kind"] in GENERATED_KINDS and m["owner"] not in known_owners:
            sys.exit(
                f"methods.toml: {m['owner']}::{m['name']} has kind={m['kind']!r} "
                "but its owner is not a [[client_module]] -- generated methods "
                "must live on a Client-accessor type"
            )

    by_owner: dict[str, list[dict[str, Any]]] = {}
    for m in methods:
        by_owner.setdefault(m["owner"], []).append(m)

    structs = "\n".join(
        render_struct(cm, by_owner.get(cm["owner"], [])) for cm in client_modules
    )

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    (OUT_DIR / "generated.rs").write_text(HEADER + structs, encoding="utf-8")


if __name__ == "__main__":
    main()
