#!/usr/bin/env python3
"""Reads `methods.toml` plus `contracts/parity-matrix.md` and emits
`docs/parity.md` (and its Japanese twin `docs/parity.ja.md`): the Python name
-> Rust name -> Status -> Test(s) table that records how much of google-genai's
Gemini Developer API surface this crate covers.

Two jobs:

1. **Cross-check.** Every method the agreed baseline
   (`specs/001-port-genai-rust/contracts/parity-matrix.md`) marks ✅ must
   have a `[[method]]` entry in `methods.toml`. Anything missing is either
   a real regression or belongs in `NOT_PORTED` / `NON_METHOD_ROWS` below
   with a written justification; otherwise this script exits non-zero and
   names the offending rows.
2. **Render.** Emit `docs/parity.md` from `methods.toml` (the inventory),
   the parity matrix (the agreed statuses), and a scan of the repository's
   test functions (the "Test(s)" column). The same model is rendered once
   per locale: `LOCALE_EN` below for English, `parity_strings.ja.toml` for
   Japanese. Every key in `LOCALE_EN` must exist in the Japanese file and
   vice versa; `load_locales` exits non-zero otherwise, so adding a string
   to one side forces the other.

The contract document is written in Japanese while `docs/parity.md` is
English-only, so the few cells quoted verbatim from it are translated through
`MATRIX_CELL_TRANSLATIONS` below. `docs/parity.ja.md` quotes those same cells
verbatim instead. The Japanese prose lives outside this script because the
repository's pre-commit hook rejects CJK outside `*.ja*` files, and
backslash-escaping a whole document's prose would be unreadable.

See specs/001-port-genai-rust/contracts/codegen.md, "methods.toml /
gen_blocking.py / gen_parity.py". DO NOT hand-edit the generated output;
edit this script (or `methods.toml`) and re-run
`python tools/codegen/generate.py --only parity` instead.
"""

from __future__ import annotations

import attribution
import upstream

import pathlib
import re
import sys
from typing import Any

try:
    import tomllib
except ModuleNotFoundError:  # Python < 3.11
    import tomli as tomllib  # type: ignore[no-redef]

REPO_ROOT = pathlib.Path(__file__).resolve().parents[2]
TOOLS_DIR = pathlib.Path(__file__).resolve().parent
METHODS_TOML = TOOLS_DIR / "methods.toml"
# Lives beside the generator, not under `specs/`: that directory is
# git-ignored (spec-kit artifacts), so a clean CI checkout does not have it
# and `codegen-check` could never run. An input to code generation has to be
# tracked like any other input.
#
# The `.ja` in the name is load-bearing, not decoration: the document is
# written in Japanese, and the repository's english-only-content commit hook
# rejects CJK in any file not matching `*.ja*`. The few cells quoted verbatim
# into the English output go through MATRIX_CELL_TRANSLATIONS below.
PARITY_MATRIX = TOOLS_DIR / "parity-matrix.ja.md"
OUT_DIR = REPO_ROOT / "docs"
# Japanese strings for the second rendering. Output paths come from each
# locale's `out_file`, so this script never hard-codes `parity.ja.md`.
STRINGS_JA = TOOLS_DIR / "parity_strings.ja.toml"

TYPES_DIR = REPO_ROOT / "src" / "types" / "generated"

GENAI_VERSION = upstream.PINNED_VERSION

HEADER = (
    "<!-- @generated by tools/codegen/gen_parity.py from tools/codegen/methods.toml\n"
    "     and tools/codegen/parity-matrix.ja.md. DO NOT EDIT.\n"
    + attribution.html_attribution(
        "gen_parity.py",
        GENAI_VERSION,
        modified=(
            "the method inventory is mechanically derived from the upstream\n"
            "SDK's public API surface."
        ),
    )
    + "     Edit tools/codegen/gen_parity.py (or tools/codegen/methods.toml) and re-run\n"
    "     `python tools/codegen/generate.py --only parity` instead. -->\n"
)

# --- parity-matrix.md → methods.toml module names --------------------------
#
# The matrix names modules the way Python does (`client.aio.live.music`,
# `file_search_stores.documents`); `methods.toml` uses the Rust module
# name.
MODULE_ALIASES = {
    "file_search_stores.documents": "documents",
    "live.AsyncSession": "live",
    "live.music": "live_music",
}

# --- parity-matrix.md strings matched as input -----------------------------
#
# The contract document is Japanese, so the header cell that identifies its
# per-module method table has to be matched in Japanese. Written with
# `\uXXXX` escapes only to keep this file itself ASCII; the value is the
# Japanese word for "Module".
MATRIX_MODULE_HEADER = "\u30e2\u30b8\u30e5\u30fc\u30eb"

# --- parity-matrix.md cells quoted in the output ---------------------------
#
# The "Client construction" table and the non-✅ rows of the "Out of scope"
# table are copied straight out of the contract document, which is Japanese.
# `docs/parity.md` is English-only, so those cells are translated here. Keys
# are the exact source cells (again `\uXXXX`-escaped to keep this file ASCII);
# a cell that still reads as Japanese after the lookup is a hard error, see
# `translate_cell`.
MATRIX_CELL_TRANSLATIONS: dict[str, str] = {
    "`client.*`\uff08\u540c\u671f\uff09": "`client.*` (sync)",
    "builder \u306b\u4e88\u7d04\u3001`build()` \u3067 `UnsupportedBackend`": (
        "reserved in the builder; `build()` returns `UnsupportedBackend`"
    ),
    "\u975e\u540c\u671f\u304c\u4e3b API": "async is the primary API",
    "N/A\uff08IPython \u5c02\u7528\uff09": "N/A (IPython only)",
    "N/A\uff08replay \u6a5f\u69cb\u306f\u79fb\u690d\u3057\u306a\u3044\uff09": (
        "N/A (the replay machinery is not ported)"
    ),
    "✅\uff08feature `blocking`\uff09": "✅ (feature `blocking`)",
    "✅\uff08`httpx_*` / `aiohttp_client` / `client_args` \u306f N/A\uff09": (
        "✅ (`httpx_*` / `aiohttp_client` / `client_args` are N/A)"
    ),
    "⏭ \u5f8c\u7d9a\uff08Vertex AI\uff09": "⏭ later (Vertex AI)",
    "⏭ \u5f8c\u7d9a\uff08Speakeasy \u751f\u6210 NextGen SDK\uff09": (
        "⏭ later (Speakeasy-generated NextGen SDK)"
    ),
    "⏭ \u5f8c\u7d9a\uff08sentencepiece \u30cd\u30a4\u30c6\u30a3\u30d6\u4f9d\u5b58\uff09": (
        "⏭ later (native sentencepiece dependency)"
    ),
    "⏭ \u5bfe\u8c61\u5916\uff08Deprecated\u3001\u4ee3\u66ff\u3042\u308a\uff09": (
        "⏭ out of scope (deprecated, replacement available)"
    ),
}

# The character class the repository's pre-commit hook rejects outside `*.ja*`
# files: CJK punctuation, kana, ideographs and full-width forms.
CJK_RE = re.compile(
    "[\u3000-\u303f\u3040-\u30ff\u3400-\u4dbf\u4e00-\u9fff\uf900-\ufaff\uff00-\uffef]"
)

# --- matrix rows that are not methods --------------------------------------
#
# Two ✅ rows in the matrix's per-module method table describe types, not
# callable methods, so they can have no `[[method]]` entry. Both are covered
# elsewhere; the rationale text is per-locale (see `LOCALE_EN["non_method_rows"]`
# and the `[non_method_rows]` table in parity_strings.ja.toml).
NON_METHOD_ROWS: tuple[str, ...] = ("pagers", "errors")

# --- marked ✅ in the matrix, but not ported to Rust ------------------------
#
# The parity matrix marks ✅ per google-genai "public method", but each method
# below is Vertex AI-only in google-genai 2.19.0: in Gemini Developer API mode
# (`vertexai=False`) the Python implementation always raises `ValueError`.
# This crate targets the Gemini Developer API alone (see the out-of-scope
# section of the parity matrix), so they are not ported. The per-method
# justification, citing the relevant spot in the Python SDK, is per-locale:
# `LOCALE_EN["not_ported"]` and `[not_ported]` in parity_strings.ja.toml,
# keyed `"<module>.<name>"`.
NOT_PORTED: tuple[tuple[str, str], ...] = (
    ("models", "edit_image"),
    ("models", "upscale_image"),
    ("models", "recontext_image"),
    ("models", "segment_image"),
    ("tunings", "validate_reward"),
)

# --- locale strings ----------------------------------------------------------
#
# Every user-visible string in the rendered document, keyed so that
# `parity_strings.ja.toml` can supply the same set in Japanese. `{...}`
# placeholders are filled with `str.format`. Keep this English-only: the
# english-only-content commit hook applies to this file.
LOCALE_EN: dict[str, Any] = {
    "title": "Python → Rust parity table",
    "cross_link": "Japanese version: [parity.ja.md](parity.ja.md)",
    "out_file": "docs/parity.md",
    "baseline": (
        "**Baseline**: google-genai {version} | "
        "**Crate**: `gemini-genai` (`gemini_genai`) | "
        "**Source of truth**: `tools/codegen/parity-matrix.ja.md`"
    ),
    "toc": "Table of Contents",
    "h_overview": "Overview",
    "h_generated": "How this document is generated",
    "h_legend": "Legend",
    "h_summary": "Per-module summary",
    "h_mapping": "Method mapping",
    "h_client": "Client construction",
    "h_types": "Types",
    "h_scope": "Out of scope (with rationale)",
    "overview_p1": (
        "Coverage of the **{total}** public methods that google-genai {version} (Python) "
        "exposes for the Gemini Developer API, plus the Rust-specific accessors. "
        "**{ok}** are implemented, **{unsupported}** are Vertex AI-only and ship as stubs "
        "returning `UnsupportedByBackend`, and **{not_ported}** are Vertex AI-only and not "
        "ported at all. A test function was found automatically for **{tested}** of them."
    ),
    "overview_p2": (
        "This table is generated from `tools/codegen/methods.toml` (the method ledger) and "
        "`tools/codegen/parity-matrix.ja.md` (the agreed source of truth). "
        "If an entry the parity matrix marks ✅ is missing from the ledger, `gen_parity.py` "
        "exits non-zero and CI's `codegen-check` fails."
    ),
    "mermaid_missing": "missing ✅ entry",
    "mermaid_exit": "non-zero exit",
    "legend_col_status": "Status",
    "legend_col_meaning": "Meaning",
    "legend_st_unsupported": "⚠️ `UnsupportedByBackend`",
    "legend_impl_desc": "A matching Rust method exists and is covered by tests",
    "legend_unsup_desc": (
        "Vertex AI-only in Python. Only the signature is ported; calling it always returns an error"
    ),
    "legend_not_ported_desc": (
        "Out of scope because the Python side raises `ValueError` when `vertexai=False`"
    ),
    "legend_note": (
        "The \"Test(s)\" column comes from scanning `tests/**.rs` and the `#[cfg(test)]` "
        "modules under `src/**` for test functions containing a chained "
        "`.<module>().<method>(` call (within a module's own `#[cfg(test)]`, a plain "
        "`.<method>(` call; failing both, an accessor call plus the method name). "
        "**Treat it as a heuristic, not as proof of coverage.** "
        "At most {max_tests} are listed per method."
    ),
    "sum_col_module": "Module",
    "sum_col_methods": "Methods",
    "sum_col_impl": "Implemented",
    "sum_col_not_ported": "Not ported",
    "sum_col_tests": "Tests found",
    "sum_total": "**Total**",
    "col_python": "Python",
    "col_rust": "Rust",
    "col_status": "Status",
    "col_tests": "Test(s)",
    "st_impl": "✅ Implemented",
    "st_unsupported": "⚠️ `UnsupportedByBackend` (Vertex AI only)",
    "st_not_ported": "⏭ Not ported (Vertex AI only)",
    "status_notes": "{status} ({notes})",
    "note_join": ", ",
    "note_deprecated": "`#[deprecated]`",
    "note_private": "private helper",
    "note_async_only": "async only, no sync variant",
    "note_sync_handwritten": "sync variant is hand-written",
    "more_tests": "and {count} more",
    "no_test": "— (no test found)",
    "rust_specific": "— (Rust-specific accessor)",
    "client_p": (
        "Building a `Client` and picking a backend are not individual methods, so they fall "
        "outside `methods.toml`. The matching table from the source of truth is reproduced "
        "here."
    ),
    "types_p1": (
        "`tools/codegen/gen_types.py` turns `google.genai.types` into **{structs} structs / "
        "{enums} enums** (`src/types/generated/structs.rs`, "
        "`src/types/generated/enums.rs`). Type and field names match Python one for one "
        "(snake_case), so the mapping is 1:1 and is not listed here."
    ),
    "types_p2": (
        "Parity on the type side is `gen_types.py`'s own job: the moment it meets an "
        "annotation missing from its mapping table it prints the class and field name and "
        "exits non-zero, so anything overlooked surfaces in CI's `codegen-check` (see "
        "\"gen_types.py\" in `specs/001-port-genai-rust/contracts/codegen.md`)."
    ),
    "scope_col_item": "Item",
    "scope_col_reason": "Rationale",
    "scope_row_suffix": " (row in the source of truth)",
    "scope_per_sot": " (per the source of truth)",
    "scope_tail": (
        "Whole backends that are out of scope (Vertex AI / NextGen / `local_tokenizer` / "
        "replay) are covered by the out-of-scope section of "
        "`tools/codegen/parity-matrix.ja.md`."
    ),
    "not_ported": {
        "models.edit_image": (
            "`models.py::_edit_image` opens with `if not self._api_client.vertexai: raise ValueError"
            "('This method is only supported in Gemini Enterprise Agent Platform mode, ...')`, "
            "so it cannot be called on the Gemini Developer API."
        ),
        "models.upscale_image": (
            "`models.py::_upscale_image` carries the same `vertexai` guard. Vertex AI only."
        ),
        "models.recontext_image": (
            "`models.py::recontext_image` carries the same `vertexai` guard. Vertex AI only."
        ),
        "models.segment_image": (
            "`models.py::segment_image` carries the same `vertexai` guard. Vertex AI only."
        ),
        "tunings.validate_reward": (
            "`tunings.py::validate_reward` carries the same `vertexai` guard. Vertex AI only "
            "(reward model validation is a Vertex AI tuning feature)."
        ),
    },
    "non_method_rows": {
        "pagers": (
            "`Pager` / `AsyncPager` are types, not methods. Rust implements them as "
            "`crate::pager::Pager<T>` (`page()` / `name()` / `page_size()` / "
            "`config()` / `next_page()`), verified by the `#[cfg(test)]` tests in "
            "`src/pager.rs` and by the tests for each `list` method."
        ),
        "errors": (
            "The `APIError` family are types, not methods. Rust implements them as the "
            "`crate::error::Error` enum (`Api` / `Function*` / `UnknownApiResponse` "
            "and friends), verified by the `#[cfg(test)]` tests in `src/error.rs`."
        ),
    },
}


def load_locales() -> dict[str, dict[str, Any]]:
    """Returns `{"en": LOCALE_EN, "ja": <parity_strings.ja.toml>}`.

    A key present in one locale but missing from the other is a hard error:
    the two documents must stay structurally identical, and silently falling
    back to English inside the Japanese file would leak untranslated prose
    without anything failing.
    """
    japanese = tomllib.loads(STRINGS_JA.read_text(encoding="utf-8"))
    locales = {"en": LOCALE_EN, "ja": japanese}

    def flat_keys(strings: dict[str, Any]) -> set[str]:
        keys: set[str] = set()
        for key, value in strings.items():
            if isinstance(value, dict):
                keys.update(f"{key}.{sub}" for sub in value)
            else:
                keys.add(key)
        return keys

    reference = flat_keys(LOCALE_EN)
    problems: list[str] = []
    for code, strings in locales.items():
        keys = flat_keys(strings)
        for missing in sorted(reference - keys):
            problems.append(f"  {code}: missing {missing!r}")
        for extra in sorted(keys - reference):
            problems.append(f"  {code}: unexpected {extra!r} (not in LOCALE_EN)")
    if problems:
        sys.exit(
            "gen_parity.py: locale strings are out of sync between LOCALE_EN and "
            f"{STRINGS_JA.relative_to(REPO_ROOT)}:\n" + "\n".join(problems)
        )
    return locales


def slug(heading: str) -> str:
    """GitHub's heading anchor: lowercased, punctuation dropped, spaces to `-`.

    Works for both scripts: `Out of scope (with rationale)` becomes
    `out-of-scope-with-rationale`, and the Japanese heading with full-width
    parentheses loses them the same way.
    """
    return re.sub(r"[^\w\- ]", "", heading.lower()).replace(" ", "-")


# --- test discovery --------------------------------------------------------
#
# `(required, forbidden)` substrings identifying a module's accessor call in
# a test body. Default is `.<module>()`; `live` / `live_music` share the
# `client.live()` entry point, so they are disambiguated explicitly. The
# accessor requirement is waived for a module's own `#[cfg(test)]` tests,
# which reach the handle through a file-local helper instead (see
# `owner_source_paths`).
ACCESSOR_OVERRIDES: dict[str, tuple[tuple[str, ...], tuple[str, ...]]] = {
    "live": ((".live()",), (".music()",)),
    "live_music": ((".music()",), ()),
}

TEST_ATTR_RE = re.compile(r"#\[(?:tokio::test|test|rstest)\]")
FN_RE = re.compile(r"(?:async\s+)?fn\s+([A-Za-z0-9_]+)")

MAX_TESTS_SHOWN = 3


def load_methods() -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    data = tomllib.loads(METHODS_TOML.read_text(encoding="utf-8"))
    return data.get("client_module", []), data.get("method", [])


# ---------------------------------------------------------------------------
# parity-matrix.md parsing
# ---------------------------------------------------------------------------


def parse_tables(text: str) -> list[list[list[str]]]:
    """Splits a Markdown document into tables (list of rows of cells)."""
    tables: list[list[list[str]]] = []
    current: list[list[str]] = []
    for line in text.splitlines():
        stripped = line.strip()
        if stripped.startswith("|") and stripped.endswith("|"):
            cells = [c.strip() for c in stripped.strip("|").split("|")]
            if all(set(c) <= set("-: ") and c for c in cells):
                continue  # the `|---|---|` separator row
            current.append(cells)
        elif current:
            tables.append(current)
            current = []
    if current:
        tables.append(current)
    return tables


def status_of(cell: str) -> str:
    """First token of a status cell: `✅`, `⏭`, or `N/A`."""
    cell = cell.strip()
    for marker in ("✅", "⏭", "N/A"):
        if cell.startswith(marker):
            return marker
    return cell.split()[0] if cell else ""


def split_names(cell: str) -> list[str]:
    return [n.strip().strip("`") for n in cell.split("/") if n.strip()]


def translate_cell(cell: str) -> str:
    """English rendering of a cell quoted verbatim from parity-matrix.md.

    Cells that are already English pass through untouched; Japanese ones must
    have an entry in `MATRIX_CELL_TRANSLATIONS`, otherwise the generated
    document would leak Japanese into an English-only file.
    """
    text = MATRIX_CELL_TRANSLATIONS.get(cell.strip(), cell)
    if CJK_RE.search(text):
        sys.exit(
            f"gen_parity.py: no English translation for the parity-matrix.md cell {cell!r}; "
            "add it to MATRIX_CELL_TRANSLATIONS in tools/codegen/gen_parity.py "
            "(docs/parity.md must stay English-only)"
        )
    return text


def parse_matrix(text: str) -> tuple[list[dict[str, str]], list[dict[str, str]]]:
    """Returns `(client_rows, method_rows)` from parity-matrix.md.

    `client_rows` are the rows of the three-column `| Python | Rust | status |`
    table; `method_rows` are the rows of the four-column
    `| module | Python method | Rust | status |` table, one per `/`-separated
    method name.
    """
    client_rows: list[dict[str, str]] = []
    method_rows: list[dict[str, str]] = []
    for table in parse_tables(text):
        header = table[0]
        if header[:1] == ["Python"] and len(header) == 3:
            for row in table[1:]:
                client_rows.append(
                    {"python": row[0], "rust": row[1], "status": status_of(row[2]), "raw_status": row[2]}
                )
        elif header[:1] == [MATRIX_MODULE_HEADER] and len(header) == 4:
            for row in table[1:]:
                module = MODULE_ALIASES.get(row[0], row[0])
                for name in split_names(row[1]):
                    method_rows.append(
                        {
                            "matrix_module": row[0],
                            "module": module,
                            "name": name,
                            "rust": row[2],
                            "status": status_of(row[3]),
                            "raw_status": row[3],
                        }
                    )
    if not client_rows or not method_rows:
        sys.exit(
            f"gen_parity.py: could not parse the expected tables out of {PARITY_MATRIX}; "
            "the contract document's table headers may have changed"
        )
    return client_rows, method_rows


# ---------------------------------------------------------------------------
# test discovery
# ---------------------------------------------------------------------------


def rust_test_files() -> list[pathlib.Path]:
    files = [
        p
        for p in sorted((REPO_ROOT / "tests").rglob("*.rs"))
        if "fixtures" not in p.relative_to(REPO_ROOT).parts
    ]
    files += [
        p
        for p in sorted((REPO_ROOT / "src").rglob("*.rs"))
        if "#[cfg(test)]" in p.read_text(encoding="utf-8")
    ]
    return files


def collect_tests() -> list[tuple[str, str, str]]:
    """Returns `(test_id, fn_name, body)` for every `#[test]`-ish function."""
    tests: list[tuple[str, str, str]] = []
    for path in rust_test_files():
        rel = path.relative_to(REPO_ROOT).as_posix()
        text = path.read_text(encoding="utf-8")
        starts = [m.end() for m in TEST_ATTR_RE.finditer(text)]
        for idx, start in enumerate(starts):
            end = starts[idx + 1] if idx + 1 < len(starts) else len(text)
            chunk = text[start:end]
            fn = FN_RE.search(chunk)
            if fn is None:
                continue
            tests.append((f"{rel}::{fn.group(1)}", fn.group(1), chunk[fn.end() :]))
    return tests


def accessors(module: str) -> tuple[tuple[str, ...], tuple[str, ...]]:
    return ACCESSOR_OVERRIDES.get(module, ((f".{module}()",), ()))


def owner_source_paths(owner: str) -> set[str]:
    """`crate::live::music::LiveMusicSession` -> the files that may hold its
    own `#[cfg(test)]` module (`src/live/music.rs`, `src/live/music/mod.rs`)."""
    parts = owner.removeprefix("crate::").split("::")[:-1]
    stem = "src/" + "/".join(parts)
    return {f"{stem}.rs", f"{stem}/mod.rs"}


def find_tests(method: dict[str, Any], tests: list[tuple[str, str, str]]) -> list[str]:
    """Heuristic: prefer test bodies chaining `.<module>().<name>(`; fall back
    to "the module's handle is in scope and the method is called (or named in
    the test's own identifier)". A module's own `#[cfg(test)]` tests build the
    handle through a file-local helper (`models(&server)`), so for those the
    accessor requirement is replaced by "the test lives in that module's
    source file". Reported as a best-effort pointer, not as proof of
    coverage."""
    module, name = method["module"], method["name"]
    required, forbidden = accessors(module)
    own_files = owner_source_paths(method["owner"])
    chained = re.compile(
        r"(?:" + r"|".join(re.escape(acc) for acc in required) + r")"
        r"\s*\.\s*" + re.escape(name) + r"\s*\("
    )
    call = f".{name}("
    strong: list[str] = []
    weak: list[str] = []
    for test_id, fn_name, body in tests:
        in_own_file = test_id.split("::", 1)[0] in own_files
        if not in_own_file:
            if any(bad in body for bad in forbidden):
                continue
            if not any(acc in body for acc in required):
                continue
        if chained.search(body) or (in_own_file and call in body):
            strong.append(test_id)
        elif call in body or name in fn_name:
            weak.append(test_id)

    def rank(test: str) -> tuple[int, int, str]:
        path, fn_name = test.split("::", 1)
        return (
            0 if name in fn_name else 1,
            0 if path in own_files or pathlib.PurePosixPath(path).stem == module else 1,
            test,
        )

    return sorted(strong or weak, key=rank)


# ---------------------------------------------------------------------------
# rendering
# ---------------------------------------------------------------------------


WIRE_KINDS = {"unary", "stream", "pager", "upload"}


def rust_name(method: dict[str, Any]) -> str:
    owner = method["owner"].removeprefix("crate::")
    return f"`{owner}::{method['name']}`"


def is_unsupported(method: dict[str, Any]) -> bool:
    return method["kind"] in WIRE_KINDS and not method.get("path")


def method_status(method: dict[str, Any], s: dict[str, Any]) -> str:
    if is_unsupported(method):
        return s["st_unsupported"]
    notes = []
    if method.get("deprecated"):
        notes.append(s["note_deprecated"])
    if method.get("visibility") == "private":
        notes.append(s["note_private"])
    if method["owner"].startswith("crate::live"):
        notes.append(s["note_async_only"])
    elif method["kind"] in {"session", "manual"}:
        notes.append(s["note_sync_handwritten"])
    if not notes:
        return s["st_impl"]
    return s["status_notes"].format(status=s["st_impl"], notes=s["note_join"].join(notes))


def format_tests(test_ids: list[str], s: dict[str, Any]) -> str:
    if not test_ids:
        return s["no_test"]
    shown = [f"`{t}`" for t in test_ids[:MAX_TESTS_SHOWN]]
    if len(test_ids) > MAX_TESTS_SHOWN:
        shown.append(s["more_tests"].format(count=len(test_ids) - MAX_TESTS_SHOWN))
    return "<br>".join(shown)


def python_name(method: dict[str, Any], s: dict[str, Any]) -> str:
    py = method.get("python") or ""
    return f"`{py}`" if py else s["rust_specific"]


def anchor(module: str) -> str:
    """GitHub's heading slug: lowercased, underscores preserved."""
    return module.lower()


def render(
    client_modules: list[dict[str, Any]],
    methods: list[dict[str, Any]],
    client_rows: list[dict[str, str]],
    method_rows: list[dict[str, str]],
    tests: list[tuple[str, str, str]],
    s: dict[str, Any],
    translate: Any,
) -> str:
    """Renders one locale. `s` is that locale's string table; `translate` maps
    a cell quoted from the (Japanese) parity matrix into the output language
    -- `translate_cell` for English, identity for Japanese."""
    modules: list[str] = []
    for m in methods:
        if m["module"] not in modules:
            modules.append(m["module"])

    # module -> rendered rows + counters
    rows_by_module: dict[str, list[str]] = {m: [] for m in modules}
    stats: dict[str, dict[str, int]] = {
        m: {"total": 0, "ok": 0, "unsupported": 0, "not_ported": 0, "tested": 0} for m in modules
    }

    for m in methods:
        module = m["module"]
        found = find_tests(m, tests)
        stats[module]["total"] += 1
        if is_unsupported(m):
            stats[module]["unsupported"] += 1
        else:
            stats[module]["ok"] += 1
        if found:
            stats[module]["tested"] += 1
        rows_by_module[module].append(
            f"| {python_name(m, s)} | {rust_name(m)} | {method_status(m, s)} | "
            f"{format_tests(found, s)} |"
        )

    for module, name in sorted(NOT_PORTED):
        if module not in rows_by_module:
            rows_by_module[module] = []
            stats[module] = {"total": 0, "ok": 0, "unsupported": 0, "not_ported": 0, "tested": 0}
            modules.append(module)
        stats[module]["total"] += 1
        stats[module]["not_ported"] += 1
        rows_by_module[module].append(f"| `{module}.{name}` | — | {s['st_not_ported']} | — |")

    out: list[str] = [HEADER]
    out.append(f"# {s['title']}\n")
    out.append(s["baseline"].format(version=GENAI_VERSION) + "\n")
    out.append(s["cross_link"] + "\n")

    # --- table of contents ---
    out.append(f"## {s['toc']}\n")
    for heading in ("h_overview", "h_generated", "h_legend", "h_summary", "h_mapping"):
        out.append(f"- [{s[heading]}](#{slug(s[heading])})")
    for module in modules:
        out.append(f"  - [{module}](#{anchor(module)})")
    for heading in ("h_client", "h_types", "h_scope"):
        out.append(f"- [{s[heading]}](#{slug(s[heading])})")
    out.append("")

    # --- overview ---
    total = sum(x["total"] for x in stats.values())
    ok = sum(x["ok"] for x in stats.values())
    unsupported = sum(x["unsupported"] for x in stats.values())
    not_ported = sum(x["not_ported"] for x in stats.values())
    tested = sum(x["tested"] for x in stats.values())
    out.append(f"## {s['h_overview']}\n")
    out.append(
        s["overview_p1"].format(
            total=total,
            version=GENAI_VERSION,
            ok=ok,
            unsupported=unsupported,
            not_ported=not_ported,
            tested=tested,
        )
        + "\n"
    )
    out.append(s["overview_p2"] + "\n")

    # --- how it is generated ---
    out.append(f"## {s['h_generated']}\n")
    out.append("```mermaid")
    out.append("flowchart LR")
    out.append("  M[(tools/codegen/methods.toml)] --> GP[gen_parity.py]")
    out.append("  PM[(tools/codegen/parity-matrix.ja.md)] --> GP")
    out.append("  T[(tests/**.rs<br/>src/**#91;cfg#40;test#41;#93;)] --> GP")
    out.append(f"  GP --> D[{s['out_file']}]")
    out.append(f"  GP -. {s['mermaid_missing']} .-> X[[{s['mermaid_exit']}]]")
    out.append("  M --> GB[gen_blocking.py] --> B[src/blocking/generated.rs]")
    out.append("```\n")

    # --- legend ---
    out.append(f"## {s['h_legend']}\n")
    out.append(f"| {s['legend_col_status']} | {s['legend_col_meaning']} |")
    out.append("|---|---|")
    out.append(f"| {s['st_impl']} | {s['legend_impl_desc']} |")
    out.append(f"| {s['legend_st_unsupported']} | {s['legend_unsup_desc']} |")
    out.append(f"| {s['st_not_ported']} | {s['legend_not_ported_desc']} |")
    out.append("")
    out.append(s["legend_note"].format(max_tests=MAX_TESTS_SHOWN) + "\n")

    # --- summary ---
    out.append(f"## {s['h_summary']}\n")
    out.append(
        f"| {s['sum_col_module']} | {s['sum_col_methods']} | {s['sum_col_impl']} | "
        f"`UnsupportedByBackend` | {s['sum_col_not_ported']} | {s['sum_col_tests']} |"
    )
    out.append("|---|---:|---:|---:|---:|---:|")
    for module in modules:
        x = stats[module]
        out.append(
            f"| [{module}](#{anchor(module)}) | {x['total']} | {x['ok']} | "
            f"{x['unsupported']} | {x['not_ported']} | {x['tested']} |"
        )
    out.append(
        f"| {s['sum_total']} | **{total}** | **{ok}** | **{unsupported}** | "
        f"**{not_ported}** | **{tested}** |"
    )
    out.append("")

    # --- the table itself ---
    out.append(f"## {s['h_mapping']}\n")
    for module in modules:
        out.append(f"### {module}\n")
        out.append(f"| {s['col_python']} | {s['col_rust']} | {s['col_status']} | {s['col_tests']} |")
        out.append("|---|---|---|---|")
        out.extend(rows_by_module[module])
        out.append("")

    # --- client ---
    out.append(f"## {s['h_client']}\n")
    out.append(s["client_p"] + "\n")
    out.append(f"| {s['col_python']} | {s['col_rust']} | {s['col_status']} |")
    out.append("|---|---|---|")
    for row in client_rows:
        out.append(
            f"| {translate(row['python'])} | {translate(row['rust'])} | "
            f"{translate(row['raw_status'])} |"
        )
    out.append("")

    # --- types ---
    out.append(f"## {s['h_types']}\n")
    structs, enums = count_types()
    out.append(s["types_p1"].format(structs=structs, enums=enums) + "\n")
    out.append(s["types_p2"] + "\n")

    # --- out of scope ---
    out.append(f"## {s['h_scope']}\n")
    out.append(f"| {s['scope_col_item']} | {s['scope_col_reason']} |")
    out.append("|---|---|")
    for module, name in sorted(NOT_PORTED):
        out.append(f"| `{module}.{name}` | {s['not_ported'][f'{module}.{name}']} |")
    for module in sorted(NON_METHOD_ROWS):
        out.append(f"| `{module}`{s['scope_row_suffix']} | {s['non_method_rows'][module]} |")
    for row in method_rows:
        if row["status"] != "✅":
            out.append(
                f"| `{row['matrix_module']}.{row['name']}` | "
                f"{translate(row['raw_status'])}{s['scope_per_sot']} |"
            )
    out.append("")
    out.append(s["scope_tail"] + "\n")

    del client_modules  # inventory shape is exercised by gen_blocking.py
    return "\n".join(out)


def count_types() -> tuple[int, int]:
    def count(path: pathlib.Path, keyword: str) -> int:
        if not path.exists():
            return 0
        return sum(1 for line in path.read_text(encoding="utf-8").splitlines() if line.startswith(keyword))

    return count(TYPES_DIR / "structs.rs", "pub struct "), count(TYPES_DIR / "enums.rs", "pub enum ")


# ---------------------------------------------------------------------------
# cross-check
# ---------------------------------------------------------------------------


def cross_check(methods: list[dict[str, Any]], method_rows: list[dict[str, str]]) -> list[str]:
    """Returns a list of human-readable failures (empty == OK)."""
    known = {(m["module"], m["name"]) for m in methods}
    failures: list[str] = []
    for row in method_rows:
        if row["status"] != "✅":
            continue
        module, name = row["module"], row["name"]
        if (module, name) in known:
            continue
        if module in NON_METHOD_ROWS:
            continue
        if (module, name) in NOT_PORTED:
            continue
        failures.append(
            f"  parity-matrix.md marks `{row['matrix_module']}.{name}` ✅ but "
            f"methods.toml has no [[method]] with module = \"{module}\", name = \"{name}\""
        )
    return failures


def main() -> None:
    client_modules, methods = load_methods()
    client_rows, method_rows = parse_matrix(PARITY_MATRIX.read_text(encoding="utf-8"))

    failures = cross_check(methods, method_rows)
    if failures:
        print(
            "gen_parity.py: parity regression -- "
            f"{len(failures)} ✅ item(s) in contracts/parity-matrix.md are missing "
            "from tools/codegen/methods.toml:",
            file=sys.stderr,
        )
        for failure in failures:
            print(failure, file=sys.stderr)
        print(
            "Add the missing [[method]] entries, or (if the method is genuinely out "
            "of scope) add a justified entry to NOT_PORTED in tools/codegen/gen_parity.py.",
            file=sys.stderr,
        )
        sys.exit(1)

    tests = collect_tests()
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    written: list[str] = []
    for code, strings in load_locales().items():
        # The English document must not contain Japanese (the commit hook
        # enforces it), so cells quoted from the Japanese matrix go through
        # MATRIX_CELL_TRANSLATIONS there. The Japanese document quotes them as
        # they are.
        translate = translate_cell if code == "en" else (lambda cell: cell.strip())
        document = render(client_modules, methods, client_rows, method_rows, tests, strings, translate)
        out_file = REPO_ROOT / strings["out_file"]
        out_file.write_text(document, encoding="utf-8")
        written.append(out_file.relative_to(REPO_ROOT).as_posix())
    print(
        f"gen_parity.py: wrote {', '.join(written)} "
        f"({len(methods)} methods, {len(tests)} test fns scanned)",
        file=sys.stderr,
    )


if __name__ == "__main__":
    main()
