#!/usr/bin/env python3
"""Reads `methods.toml` plus `contracts/parity-matrix.md` and emits
`docs/parity.md`: the Python name -> Rust name -> Status -> Test(s) table that
records how much of google-genai's Gemini Developer API surface this crate
covers.

Two jobs:

1. **Cross-check.** Every method the agreed baseline
   (`specs/001-port-genai-rust/contracts/parity-matrix.md`) marks ✅ must
   have a `[[method]]` entry in `methods.toml`. Anything missing is either
   a real regression or belongs in `NOT_PORTED` / `NON_METHOD_ROWS` below
   with a written justification; otherwise this script exits non-zero and
   names the offending rows.
2. **Render.** Emit `docs/parity.md` from `methods.toml` (the inventory),
   the parity matrix (the agreed statuses), and a scan of the repository's
   test functions (the "Test(s)" column).

The contract document is written in Japanese while `docs/parity.md` is
English-only, so the few cells quoted verbatim from it are translated through
`MATRIX_CELL_TRANSLATIONS` below.

See specs/001-port-genai-rust/contracts/codegen.md, "methods.toml /
gen_blocking.py / gen_parity.py". DO NOT hand-edit the generated output;
edit this script (or `methods.toml`) and re-run
`python tools/codegen/generate.py --only parity` instead.
"""

from __future__ import annotations

import attribution
import upstream

import pathlib
import re
import sys
from typing import Any

try:
    import tomllib
except ModuleNotFoundError:  # Python < 3.11
    import tomli as tomllib  # type: ignore[no-redef]

REPO_ROOT = pathlib.Path(__file__).resolve().parents[2]
TOOLS_DIR = pathlib.Path(__file__).resolve().parent
METHODS_TOML = TOOLS_DIR / "methods.toml"
# Lives beside the generator, not under `specs/`: that directory is
# git-ignored (spec-kit artifacts), so a clean CI checkout does not have it
# and `codegen-check` could never run. An input to code generation has to be
# tracked like any other input.
#
# The `.ja` in the name is load-bearing, not decoration: the document is
# written in Japanese, and the repository's english-only-content commit hook
# rejects CJK in any file not matching `*.ja*`. The few cells quoted verbatim
# into the English output go through MATRIX_CELL_TRANSLATIONS below.
PARITY_MATRIX = TOOLS_DIR / "parity-matrix.ja.md"
OUT_DIR = REPO_ROOT / "docs"
OUT_FILE = OUT_DIR / "parity.md"

TYPES_DIR = REPO_ROOT / "src" / "types" / "generated"

GENAI_VERSION = upstream.PINNED_VERSION

HEADER = (
    "<!-- @generated by tools/codegen/gen_parity.py from tools/codegen/methods.toml\n"
    "     and tools/codegen/parity-matrix.ja.md. DO NOT EDIT.\n"
    + attribution.html_attribution(
        "gen_parity.py",
        GENAI_VERSION,
        modified=(
            "the method inventory is mechanically derived from the upstream\n"
            "SDK's public API surface."
        ),
    )
    + "     Edit tools/codegen/gen_parity.py (or tools/codegen/methods.toml) and re-run\n"
    "     `python tools/codegen/generate.py --only parity` instead. -->\n"
)

# --- parity-matrix.md → methods.toml module names --------------------------
#
# The matrix names modules the way Python does (`client.aio.live.music`,
# `file_search_stores.documents`); `methods.toml` uses the Rust module
# name.
MODULE_ALIASES = {
    "file_search_stores.documents": "documents",
    "live.AsyncSession": "live",
    "live.music": "live_music",
}

# --- parity-matrix.md strings matched as input -----------------------------
#
# The contract document is Japanese, so the header cell that identifies its
# per-module method table has to be matched in Japanese. Written with
# `\uXXXX` escapes only to keep this file itself ASCII; the value is the
# Japanese word for "Module".
MATRIX_MODULE_HEADER = "\u30e2\u30b8\u30e5\u30fc\u30eb"

# --- parity-matrix.md cells quoted in the output ---------------------------
#
# The "Client construction" table and the non-✅ rows of the "Out of scope"
# table are copied straight out of the contract document, which is Japanese.
# `docs/parity.md` is English-only, so those cells are translated here. Keys
# are the exact source cells (again `\uXXXX`-escaped to keep this file ASCII);
# a cell that still reads as Japanese after the lookup is a hard error, see
# `translate_cell`.
MATRIX_CELL_TRANSLATIONS: dict[str, str] = {
    "`client.*`\uff08\u540c\u671f\uff09": "`client.*` (sync)",
    "builder \u306b\u4e88\u7d04\u3001`build()` \u3067 `UnsupportedBackend`": (
        "reserved in the builder; `build()` returns `UnsupportedBackend`"
    ),
    "\u975e\u540c\u671f\u304c\u4e3b API": "async is the primary API",
    "N/A\uff08IPython \u5c02\u7528\uff09": "N/A (IPython only)",
    "N/A\uff08replay \u6a5f\u69cb\u306f\u79fb\u690d\u3057\u306a\u3044\uff09": (
        "N/A (the replay machinery is not ported)"
    ),
    "✅\uff08feature `blocking`\uff09": "✅ (feature `blocking`)",
    "✅\uff08`httpx_*` / `aiohttp_client` / `client_args` \u306f N/A\uff09": (
        "✅ (`httpx_*` / `aiohttp_client` / `client_args` are N/A)"
    ),
    "⏭ \u5f8c\u7d9a\uff08Vertex AI\uff09": "⏭ later (Vertex AI)",
    "⏭ \u5f8c\u7d9a\uff08Speakeasy \u751f\u6210 NextGen SDK\uff09": (
        "⏭ later (Speakeasy-generated NextGen SDK)"
    ),
    "⏭ \u5f8c\u7d9a\uff08sentencepiece \u30cd\u30a4\u30c6\u30a3\u30d6\u4f9d\u5b58\uff09": (
        "⏭ later (native sentencepiece dependency)"
    ),
    "⏭ \u5bfe\u8c61\u5916\uff08Deprecated\u3001\u4ee3\u66ff\u3042\u308a\uff09": (
        "⏭ out of scope (deprecated, replacement available)"
    ),
}

# The character class the repository's pre-commit hook rejects outside `*.ja*`
# files: CJK punctuation, kana, ideographs and full-width forms.
CJK_RE = re.compile(
    "[\u3000-\u303f\u3040-\u30ff\u3400-\u4dbf\u4e00-\u9fff\uf900-\ufaff\uff00-\uffef]"
)

# --- matrix rows that are not methods --------------------------------------
#
# Two ✅ rows in the matrix's per-module method table describe types, not
# callable methods, so they can have no `[[method]]` entry. Both are covered
# elsewhere.
NON_METHOD_ROWS = {
    "pagers": (
        "`Pager` / `AsyncPager` are types, not methods. Rust implements them as "
        "`crate::pager::Pager<T>` (`page()` / `name()` / `page_size()` / "
        "`config()` / `next_page()`), verified by the `#[cfg(test)]` tests in "
        "`src/pager.rs` and by the tests for each `list` method."
    ),
    "errors": (
        "The `APIError` family are types, not methods. Rust implements them as the "
        "`crate::error::Error` enum (`Api` / `Function*` / `UnknownApiResponse` "
        "and friends), verified by the `#[cfg(test)]` tests in `src/error.rs`."
    ),
}

# --- marked ✅ in the matrix, but not ported to Rust ------------------------
#
# The parity matrix marks ✅ per google-genai "public method", but each method
# below is Vertex AI-only in google-genai 2.19.0: in Gemini Developer API mode
# (`vertexai=False`) the Python implementation always raises `ValueError`.
# This crate targets the Gemini Developer API alone (see the out-of-scope
# section of contracts/parity-matrix.md), so they are not ported. Each entry
# cites the relevant spot in the Python SDK.
NOT_PORTED: dict[tuple[str, str], str] = {
    ("models", "edit_image"): (
        "`models.py::_edit_image` opens with `if not self._api_client.vertexai: raise ValueError"
        "('This method is only supported in Gemini Enterprise Agent Platform mode, ...')`, "
        "so it cannot be called on the Gemini Developer API."
    ),
    ("models", "upscale_image"): (
        "`models.py::_upscale_image` carries the same `vertexai` guard. Vertex AI only."
    ),
    ("models", "recontext_image"): (
        "`models.py::recontext_image` carries the same `vertexai` guard. Vertex AI only."
    ),
    ("models", "segment_image"): (
        "`models.py::segment_image` carries the same `vertexai` guard. Vertex AI only."
    ),
    ("tunings", "validate_reward"): (
        "`tunings.py::validate_reward` carries the same `vertexai` guard. Vertex AI only "
        "(reward model validation is a Vertex AI tuning feature)."
    ),
}

# --- test discovery --------------------------------------------------------
#
# `(required, forbidden)` substrings identifying a module's accessor call in
# a test body. Default is `.<module>()`; `live` / `live_music` share the
# `client.live()` entry point, so they are disambiguated explicitly. The
# accessor requirement is waived for a module's own `#[cfg(test)]` tests,
# which reach the handle through a file-local helper instead (see
# `owner_source_paths`).
ACCESSOR_OVERRIDES: dict[str, tuple[tuple[str, ...], tuple[str, ...]]] = {
    "live": ((".live()",), (".music()",)),
    "live_music": ((".music()",), ()),
}

TEST_ATTR_RE = re.compile(r"#\[(?:tokio::test|test|rstest)\]")
FN_RE = re.compile(r"(?:async\s+)?fn\s+([A-Za-z0-9_]+)")

MAX_TESTS_SHOWN = 3


def load_methods() -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    data = tomllib.loads(METHODS_TOML.read_text(encoding="utf-8"))
    return data.get("client_module", []), data.get("method", [])


# ---------------------------------------------------------------------------
# parity-matrix.md parsing
# ---------------------------------------------------------------------------


def parse_tables(text: str) -> list[list[list[str]]]:
    """Splits a Markdown document into tables (list of rows of cells)."""
    tables: list[list[list[str]]] = []
    current: list[list[str]] = []
    for line in text.splitlines():
        stripped = line.strip()
        if stripped.startswith("|") and stripped.endswith("|"):
            cells = [c.strip() for c in stripped.strip("|").split("|")]
            if all(set(c) <= set("-: ") and c for c in cells):
                continue  # the `|---|---|` separator row
            current.append(cells)
        elif current:
            tables.append(current)
            current = []
    if current:
        tables.append(current)
    return tables


def status_of(cell: str) -> str:
    """First token of a status cell: `✅`, `⏭`, or `N/A`."""
    cell = cell.strip()
    for marker in ("✅", "⏭", "N/A"):
        if cell.startswith(marker):
            return marker
    return cell.split()[0] if cell else ""


def split_names(cell: str) -> list[str]:
    return [n.strip().strip("`") for n in cell.split("/") if n.strip()]


def translate_cell(cell: str) -> str:
    """English rendering of a cell quoted verbatim from parity-matrix.md.

    Cells that are already English pass through untouched; Japanese ones must
    have an entry in `MATRIX_CELL_TRANSLATIONS`, otherwise the generated
    document would leak Japanese into an English-only file.
    """
    text = MATRIX_CELL_TRANSLATIONS.get(cell.strip(), cell)
    if CJK_RE.search(text):
        sys.exit(
            f"gen_parity.py: no English translation for the parity-matrix.md cell {cell!r}; "
            "add it to MATRIX_CELL_TRANSLATIONS in tools/codegen/gen_parity.py "
            "(docs/parity.md must stay English-only)"
        )
    return text


def parse_matrix(text: str) -> tuple[list[dict[str, str]], list[dict[str, str]]]:
    """Returns `(client_rows, method_rows)` from parity-matrix.md.

    `client_rows` are the rows of the three-column `| Python | Rust | status |`
    table; `method_rows` are the rows of the four-column
    `| module | Python method | Rust | status |` table, one per `/`-separated
    method name.
    """
    client_rows: list[dict[str, str]] = []
    method_rows: list[dict[str, str]] = []
    for table in parse_tables(text):
        header = table[0]
        if header[:1] == ["Python"] and len(header) == 3:
            for row in table[1:]:
                client_rows.append(
                    {"python": row[0], "rust": row[1], "status": status_of(row[2]), "raw_status": row[2]}
                )
        elif header[:1] == [MATRIX_MODULE_HEADER] and len(header) == 4:
            for row in table[1:]:
                module = MODULE_ALIASES.get(row[0], row[0])
                for name in split_names(row[1]):
                    method_rows.append(
                        {
                            "matrix_module": row[0],
                            "module": module,
                            "name": name,
                            "rust": row[2],
                            "status": status_of(row[3]),
                            "raw_status": row[3],
                        }
                    )
    if not client_rows or not method_rows:
        sys.exit(
            f"gen_parity.py: could not parse the expected tables out of {PARITY_MATRIX}; "
            "the contract document's table headers may have changed"
        )
    return client_rows, method_rows


# ---------------------------------------------------------------------------
# test discovery
# ---------------------------------------------------------------------------


def rust_test_files() -> list[pathlib.Path]:
    files = [
        p
        for p in sorted((REPO_ROOT / "tests").rglob("*.rs"))
        if "fixtures" not in p.relative_to(REPO_ROOT).parts
    ]
    files += [
        p
        for p in sorted((REPO_ROOT / "src").rglob("*.rs"))
        if "#[cfg(test)]" in p.read_text(encoding="utf-8")
    ]
    return files


def collect_tests() -> list[tuple[str, str, str]]:
    """Returns `(test_id, fn_name, body)` for every `#[test]`-ish function."""
    tests: list[tuple[str, str, str]] = []
    for path in rust_test_files():
        rel = path.relative_to(REPO_ROOT).as_posix()
        text = path.read_text(encoding="utf-8")
        starts = [m.end() for m in TEST_ATTR_RE.finditer(text)]
        for idx, start in enumerate(starts):
            end = starts[idx + 1] if idx + 1 < len(starts) else len(text)
            chunk = text[start:end]
            fn = FN_RE.search(chunk)
            if fn is None:
                continue
            tests.append((f"{rel}::{fn.group(1)}", fn.group(1), chunk[fn.end() :]))
    return tests


def accessors(module: str) -> tuple[tuple[str, ...], tuple[str, ...]]:
    return ACCESSOR_OVERRIDES.get(module, ((f".{module}()",), ()))


def owner_source_paths(owner: str) -> set[str]:
    """`crate::live::music::LiveMusicSession` -> the files that may hold its
    own `#[cfg(test)]` module (`src/live/music.rs`, `src/live/music/mod.rs`)."""
    parts = owner.removeprefix("crate::").split("::")[:-1]
    stem = "src/" + "/".join(parts)
    return {f"{stem}.rs", f"{stem}/mod.rs"}


def find_tests(method: dict[str, Any], tests: list[tuple[str, str, str]]) -> list[str]:
    """Heuristic: prefer test bodies chaining `.<module>().<name>(`; fall back
    to "the module's handle is in scope and the method is called (or named in
    the test's own identifier)". A module's own `#[cfg(test)]` tests build the
    handle through a file-local helper (`models(&server)`), so for those the
    accessor requirement is replaced by "the test lives in that module's
    source file". Reported as a best-effort pointer, not as proof of
    coverage."""
    module, name = method["module"], method["name"]
    required, forbidden = accessors(module)
    own_files = owner_source_paths(method["owner"])
    chained = re.compile(
        r"(?:" + r"|".join(re.escape(acc) for acc in required) + r")"
        r"\s*\.\s*" + re.escape(name) + r"\s*\("
    )
    call = f".{name}("
    strong: list[str] = []
    weak: list[str] = []
    for test_id, fn_name, body in tests:
        in_own_file = test_id.split("::", 1)[0] in own_files
        if not in_own_file:
            if any(bad in body for bad in forbidden):
                continue
            if not any(acc in body for acc in required):
                continue
        if chained.search(body) or (in_own_file and call in body):
            strong.append(test_id)
        elif call in body or name in fn_name:
            weak.append(test_id)

    def rank(test: str) -> tuple[int, int, str]:
        path, fn_name = test.split("::", 1)
        return (
            0 if name in fn_name else 1,
            0 if path in own_files or pathlib.PurePosixPath(path).stem == module else 1,
            test,
        )

    return sorted(strong or weak, key=rank)


# ---------------------------------------------------------------------------
# rendering
# ---------------------------------------------------------------------------


WIRE_KINDS = {"unary", "stream", "pager", "upload"}


def rust_name(method: dict[str, Any]) -> str:
    owner = method["owner"].removeprefix("crate::")
    return f"`{owner}::{method['name']}`"


def method_status(method: dict[str, Any]) -> str:
    if method["kind"] in WIRE_KINDS and not method.get("path"):
        return "⚠️ `UnsupportedByBackend` (Vertex AI only)"
    notes = []
    if method.get("deprecated"):
        notes.append("`#[deprecated]`")
    if method.get("visibility") == "private":
        notes.append("private helper")
    if method["owner"].startswith("crate::live"):
        notes.append("async only, no sync variant")
    elif method["kind"] in {"session", "manual"}:
        notes.append("sync variant is hand-written")
    return "✅ Implemented" + (f" ({', '.join(notes)})" if notes else "")


def format_tests(test_ids: list[str]) -> str:
    if not test_ids:
        return "— (no test found)"
    shown = [f"`{t}`" for t in test_ids[:MAX_TESTS_SHOWN]]
    if len(test_ids) > MAX_TESTS_SHOWN:
        shown.append(f"and {len(test_ids) - MAX_TESTS_SHOWN} more")
    return "<br>".join(shown)


def python_name(method: dict[str, Any]) -> str:
    py = method.get("python") or ""
    return f"`{py}`" if py else "— (Rust-specific accessor)"


def anchor(module: str) -> str:
    """GitHub's heading slug: lowercased, underscores preserved."""
    return module.lower()


def render(
    client_modules: list[dict[str, Any]],
    methods: list[dict[str, Any]],
    client_rows: list[dict[str, str]],
    method_rows: list[dict[str, str]],
    tests: list[tuple[str, str, str]],
) -> str:
    modules: list[str] = []
    for m in methods:
        if m["module"] not in modules:
            modules.append(m["module"])

    # module -> rendered rows + counters
    rows_by_module: dict[str, list[str]] = {m: [] for m in modules}
    stats: dict[str, dict[str, int]] = {
        m: {"total": 0, "ok": 0, "unsupported": 0, "not_ported": 0, "tested": 0} for m in modules
    }

    for m in methods:
        module = m["module"]
        status = method_status(m)
        found = find_tests(m, tests)
        stats[module]["total"] += 1
        if status.startswith("⚠️"):
            stats[module]["unsupported"] += 1
        else:
            stats[module]["ok"] += 1
        if found:
            stats[module]["tested"] += 1
        rows_by_module[module].append(
            f"| {python_name(m)} | {rust_name(m)} | {status} | {format_tests(found)} |"
        )

    for (module, name), reason in sorted(NOT_PORTED.items()):
        if module not in rows_by_module:
            rows_by_module[module] = []
            stats[module] = {"total": 0, "ok": 0, "unsupported": 0, "not_ported": 0, "tested": 0}
            modules.append(module)
        stats[module]["total"] += 1
        stats[module]["not_ported"] += 1
        rows_by_module[module].append(
            f"| `{module}.{name}` | — | ⏭ Not ported (Vertex AI only) | — |"
        )
        del reason  # rendered in the out-of-scope section instead

    out: list[str] = [HEADER]
    out.append("# Python → Rust parity table\n")
    out.append(
        f"**Baseline**: google-genai {GENAI_VERSION} | "
        "**Crate**: `gemini-genai` (`gemini_genai`) | "
        "**Source of truth**: `tools/codegen/parity-matrix.ja.md`\n"
    )

    # --- table of contents ---
    out.append("## Table of Contents\n")
    out.append("- [Overview](#overview)")
    out.append("- [How this document is generated](#how-this-document-is-generated)")
    out.append("- [Legend](#legend)")
    out.append("- [Per-module summary](#per-module-summary)")
    out.append("- [Method mapping](#method-mapping)")
    for module in modules:
        out.append(f"  - [{module}](#{anchor(module)})")
    out.append("- [Client construction](#client-construction)")
    out.append("- [Types](#types)")
    out.append("- [Out of scope (with rationale)](#out-of-scope-with-rationale)")
    out.append("")

    # --- overview ---
    total = sum(s["total"] for s in stats.values())
    ok = sum(s["ok"] for s in stats.values())
    unsupported = sum(s["unsupported"] for s in stats.values())
    not_ported = sum(s["not_ported"] for s in stats.values())
    tested = sum(s["tested"] for s in stats.values())
    out.append("## Overview\n")
    out.append(
        f"Coverage of the **{total}** public methods that google-genai {GENAI_VERSION} (Python) "
        f"exposes for the Gemini Developer API, plus the Rust-specific accessors. "
        f"**{ok}** are implemented, **{unsupported}** are Vertex AI-only and ship as stubs "
        f"returning `UnsupportedByBackend`, and **{not_ported}** are Vertex AI-only and not "
        f"ported at all. A test function was found automatically for **{tested}** of them.\n"
    )
    out.append(
        "This table is generated from `tools/codegen/methods.toml` (the method ledger) and "
        "`tools/codegen/parity-matrix.ja.md` (the agreed source of truth). "
        "If an entry the parity matrix marks ✅ is missing from the ledger, `gen_parity.py` "
        "exits non-zero and CI's `codegen-check` fails.\n"
    )

    # --- how it is generated ---
    out.append("## How this document is generated\n")
    out.append("```mermaid")
    out.append("flowchart LR")
    out.append("  M[(tools/codegen/methods.toml)] --> GP[gen_parity.py]")
    out.append("  PM[(contracts/parity-matrix.md)] --> GP")
    out.append("  T[(tests/**.rs<br/>src/**#91;cfg#40;test#41;#93;)] --> GP")
    out.append("  GP --> D[docs/parity.md]")
    out.append("  GP -. missing ✅ entry .-> X[[non-zero exit]]")
    out.append("  M --> GB[gen_blocking.py] --> B[src/blocking/generated.rs]")
    out.append("```\n")

    # --- legend ---
    out.append("## Legend\n")
    out.append("| Status | Meaning |")
    out.append("|---|---|")
    out.append("| ✅ Implemented | A matching Rust method exists and is covered by tests |")
    out.append(
        "| ⚠️ `UnsupportedByBackend` | Vertex AI-only in Python. "
        "Only the signature is ported; calling it always returns an error |"
    )
    out.append(
        "| ⏭ Not ported (Vertex AI only) | Out of scope because the Python side raises "
        "`ValueError` when `vertexai=False` |"
    )
    out.append("")
    out.append(
        "The \"Test(s)\" column comes from scanning `tests/**.rs` and the `#[cfg(test)]` "
        "modules under `src/**` for test functions containing a chained "
        "`.<module>().<method>(` call (within a module's own `#[cfg(test)]`, a plain "
        "`.<method>(` call; failing both, an accessor call plus the method name). "
        "**Treat it as a heuristic, not as proof of coverage.** "
        f"At most {MAX_TESTS_SHOWN} are listed per method.\n"
    )

    # --- summary ---
    out.append("## Per-module summary\n")
    out.append("| Module | Methods | Implemented | `UnsupportedByBackend` | Not ported | Tests found |")
    out.append("|---|---:|---:|---:|---:|---:|")
    for module in modules:
        s = stats[module]
        out.append(
            f"| [{module}](#{anchor(module)}) | {s['total']} | {s['ok']} | "
            f"{s['unsupported']} | {s['not_ported']} | {s['tested']} |"
        )
    out.append(f"| **Total** | **{total}** | **{ok}** | **{unsupported}** | **{not_ported}** | **{tested}** |")
    out.append("")

    # --- the table itself ---
    out.append("## Method mapping\n")
    for module in modules:
        out.append(f"### {module}\n")
        out.append("| Python | Rust | Status | Test(s) |")
        out.append("|---|---|---|---|")
        out.extend(rows_by_module[module])
        out.append("")

    # --- client ---
    out.append("## Client construction\n")
    out.append(
        "Building a `Client` and picking a backend are not individual methods, so they fall "
        "outside `methods.toml`. The matching table from the source of truth is reproduced "
        "here.\n"
    )
    out.append("| Python | Rust | Status |")
    out.append("|---|---|---|")
    for row in client_rows:
        out.append(
            f"| {translate_cell(row['python'])} | {translate_cell(row['rust'])} | "
            f"{translate_cell(row['raw_status'])} |"
        )
    out.append("")

    # --- types ---
    out.append("## Types\n")
    structs, enums = count_types()
    out.append(
        f"`tools/codegen/gen_types.py` turns `google.genai.types` into **{structs} structs / "
        f"{enums} enums** (`src/types/generated/structs.rs`, "
        "`src/types/generated/enums.rs`). Type and field names match Python one for one "
        "(snake_case), so the mapping is 1:1 and is not listed here.\n"
    )
    out.append(
        "Parity on the type side is `gen_types.py`'s own job: the moment it meets an "
        "annotation missing from its mapping table it prints the class and field name and "
        "exits non-zero, so anything overlooked surfaces in CI's `codegen-check` (see "
        "\"gen_types.py\" in `specs/001-port-genai-rust/contracts/codegen.md`).\n"
    )

    # --- out of scope ---
    out.append("## Out of scope (with rationale)\n")
    out.append("| Item | Rationale |")
    out.append("|---|---|")
    for (module, name), reason in sorted(NOT_PORTED.items()):
        out.append(f"| `{module}.{name}` | {reason} |")
    for module, reason in sorted(NON_METHOD_ROWS.items()):
        out.append(f"| `{module}` (row in the source of truth) | {reason} |")
    for row in method_rows:
        if row["status"] != "✅":
            out.append(
                f"| `{row['matrix_module']}.{row['name']}` | "
                f"{translate_cell(row['raw_status'])} (per the source of truth) |"
            )
    out.append("")
    out.append(
        "Whole backends that are out of scope (Vertex AI / NextGen / `local_tokenizer` / "
        "replay) are covered by the out-of-scope section of "
        "`specs/001-port-genai-rust/contracts/parity-matrix.md`.\n"
    )

    del client_modules  # inventory shape is exercised by gen_blocking.py
    return "\n".join(out)


def count_types() -> tuple[int, int]:
    def count(path: pathlib.Path, keyword: str) -> int:
        if not path.exists():
            return 0
        return sum(1 for line in path.read_text(encoding="utf-8").splitlines() if line.startswith(keyword))

    return count(TYPES_DIR / "structs.rs", "pub struct "), count(TYPES_DIR / "enums.rs", "pub enum ")


# ---------------------------------------------------------------------------
# cross-check
# ---------------------------------------------------------------------------


def cross_check(methods: list[dict[str, Any]], method_rows: list[dict[str, str]]) -> list[str]:
    """Returns a list of human-readable failures (empty == OK)."""
    known = {(m["module"], m["name"]) for m in methods}
    failures: list[str] = []
    for row in method_rows:
        if row["status"] != "✅":
            continue
        module, name = row["module"], row["name"]
        if (module, name) in known:
            continue
        if module in NON_METHOD_ROWS:
            continue
        if (module, name) in NOT_PORTED:
            continue
        failures.append(
            f"  parity-matrix.md marks `{row['matrix_module']}.{name}` ✅ but "
            f"methods.toml has no [[method]] with module = \"{module}\", name = \"{name}\""
        )
    return failures


def main() -> None:
    client_modules, methods = load_methods()
    client_rows, method_rows = parse_matrix(PARITY_MATRIX.read_text(encoding="utf-8"))

    failures = cross_check(methods, method_rows)
    if failures:
        print(
            "gen_parity.py: parity regression -- "
            f"{len(failures)} ✅ item(s) in contracts/parity-matrix.md are missing "
            "from tools/codegen/methods.toml:",
            file=sys.stderr,
        )
        for failure in failures:
            print(failure, file=sys.stderr)
        print(
            "Add the missing [[method]] entries, or (if the method is genuinely out "
            "of scope) add a justified entry to NOT_PORTED in tools/codegen/gen_parity.py.",
            file=sys.stderr,
        )
        sys.exit(1)

    tests = collect_tests()
    document = render(client_modules, methods, client_rows, method_rows, tests)

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    OUT_FILE.write_text(document, encoding="utf-8")
    print(
        f"gen_parity.py: wrote {OUT_FILE.relative_to(REPO_ROOT)} "
        f"({len(methods)} methods, {len(tests)} test fns scanned)",
        file=sys.stderr,
    )


if __name__ == "__main__":
    main()
