"""Inventories the upstream `google/genai/tests` suite.

Every `test_*` function (module level, or inside a `Test*` class) is one
entry keyed `(file, name)`. Every `pytest_helper.TestTableItem(name=...)` is a
*case* keyed `(file, "", case)`: table-driven tests are generated by the
helper rather than written as functions, and upstream runs each case against
recorded replays that are not published, so the Rust side runs them through an
oracle corpus instead (see gen_upstream_cases.py).
"""

from __future__ import annotations

import ast
import dataclasses
import pathlib

TESTS_SUBDIR = pathlib.Path("google") / "genai" / "tests"
TABLE_ITEM_CTOR = "TestTableItem"
DYNAMIC_CASE_PREFIX = "dynamic:"


@dataclasses.dataclass(frozen=True)
class UpstreamTest:
    """One upstream test function or table case."""

    file: str
    name: str
    case: str
    lineno: int
    has_vertex_marker: bool


def _call_name(node: ast.Call) -> str:
    func = node.func
    return getattr(func, "attr", getattr(func, "id", ""))


def _kw_const(node: ast.Call, key: str) -> str | None:
    for kw in node.keywords:
        if kw.arg == key and isinstance(kw.value, ast.Constant) and isinstance(kw.value.value, str):
            return kw.value.value
    return None


def _is_test_function(node: ast.AST) -> bool:
    return isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)) and node.name.startswith("test_")


def _vertex_marker(source: str, name: str) -> bool:
    return "vertexai=True" in source or "vertex" in name.lower()


def _file_entries(rel: str, source: str) -> list[UpstreamTest]:
    tree = ast.parse(source)
    entries: list[UpstreamTest] = []

    def visit(body: list[ast.stmt], prefix: str) -> None:
        for node in body:
            if _is_test_function(node):
                segment = ast.get_source_segment(source, node) or ""
                entries.append(
                    UpstreamTest(rel, f"{prefix}{node.name}", "", node.lineno, _vertex_marker(segment, node.name))
                )
            elif isinstance(node, ast.ClassDef) and node.name.startswith("Test"):
                visit(node.body, f"{node.name}::")

    visit(tree.body, "")
    for node in ast.walk(tree):
        if isinstance(node, ast.Call) and _call_name(node) == TABLE_ITEM_CTOR:
            literal = _kw_const(node, "name")
            case = literal if literal is not None else f"{DYNAMIC_CASE_PREFIX}{node.lineno}"
            segment = ast.get_source_segment(source, node) or ""
            entries.append(UpstreamTest(rel, "", case, node.lineno, _vertex_marker(segment, case)))
    return entries


def inventory(checkout: pathlib.Path) -> list[UpstreamTest]:
    """Returns all upstream tests under `checkout`, in file then source order."""
    root = checkout / TESTS_SUBDIR
    out: list[UpstreamTest] = []
    for path in sorted(root.rglob("test_*.py")):
        rel = path.relative_to(root).as_posix()
        entries = _file_entries(rel, path.read_text(encoding="utf-8"))
        ordered = sorted(entries, key=lambda e: (e.lineno, e.name, e.case))
        # Python lets a later definition shadow an earlier one of the same name;
        # pytest only collects the live one, so only that one is inventoried.
        last: dict[tuple[str, str], UpstreamTest] = {}
        for entry in ordered:
            last[(entry.name, entry.case)] = entry
        out.extend(e for e in ordered if last[(e.name, e.case)] is e)
    return out
