// @generated by tools/codegen/gen_gaos.py from google-genai 2.28.0. DO NOT EDIT.
//
// SPDX-FileCopyrightText: 2025 Google LLC
// SPDX-FileCopyrightText: 2026 Daisuke ITO
// SPDX-License-Identifier: Apache-2.0
//
// Derived from the Google Gen AI Python SDK (google-genai 2.28.0),
// https://github.com/googleapis/python-genai
// Copyright 2025 Google LLC, licensed under the Apache License, Version 2.0.
//
// Modified: mechanically derived from the Python SDK's internal `_gaos` sub-SDK by gen_gaos.py:
// model fields, string enums and unions were reflected into Rust types, and HTTP
// operations were extracted from the resource classes. Doc comments reproduce the
// upstream Python docstrings.
//
// See the NOTICE file at the repository root for the full attribution.
//
// Edit tools/codegen/gen_gaos.py (or tools/codegen/gaos_overrides.toml) and re-run
// `python tools/codegen/generate.py --only gaos` instead.

//! `client.credentials()`: the `_gaos` `credentials` operations. Generated from
//! `google/genai/_gaos/credentials.py`.

#![allow(
    clippy::pedantic,
    clippy::large_enum_variant,
    clippy::enum_variant_names,
    dead_code,
    rustdoc::bare_urls,
    reason = "mechanically generated port of the google-genai `_gaos` sub-SDK; pedantic-tier style lints, size-based enum lints and bare-URL doc warnings do not apply to a generated public API surface whose doc comments are verbatim Python docstrings"
)]

use reqwest::Method;

use crate::{client::Client, errors::Result, gaos::wire, types::HttpOptions};

/// Handle for the `credentials` operations (`client.credentials()`).
#[derive(Debug, Clone)]
pub struct Credentials {
    pub(crate) client: Client,
    pub(crate) http_options: Option<HttpOptions>,
}

impl Credentials {
    pub(crate) fn new(client: Client) -> Self {
        Self {
            client,
            http_options: None,
        }
    }

    /// Returns a handle whose calls use `options` instead of the client's `HttpOptions`:
    /// extra `headers`, a per-call `api_version`, `timeout`, `extra_body` or `retry_options`
    /// (the upstream per-call `extra_headers` / `api_version` / `timeout` arguments).
    #[must_use]
    pub fn with_http_options(mut self, options: HttpOptions) -> Self {
        self.http_options = Some(options);
        self
    }

    /// Lists credentials.
    ///
    /// `GET /{api_version}/credentials`.
    ///
    /// # Errors
    /// Returns [`Error::Api`](crate::errors::Error::Api) for a non-2xx response,
    /// [`Error::Http`](crate::errors::Error::Http) for transport failures, and
    /// [`Error::Json`](crate::errors::Error::Json) if the request cannot be serialized or the response cannot be decoded.
    pub async fn list(
        &self,
        params: &crate::gaos::models::ListCredentialsRequest,
    ) -> Result<crate::gaos::types::credentials::CredentialListResponse> {
        let url_path = "credentials";
        let mut query = wire::Query::default();
        query.push("page_size", params.page_size.as_ref());
        query.push("page_token", params.page_token.as_ref());
        let query = query.finish();
        let response = self
            .client
            .http()
            .request(
                Method::GET,
                url_path,
                query.as_deref(),
                None,
                self.http_options.as_ref(),
            )
            .await?;
        wire::parse(&response.body)
    }

    /// Creates a new credential.
    ///
    /// `POST /{api_version}/credentials`.
    ///
    /// # Errors
    /// Returns [`Error::Api`](crate::errors::Error::Api) for a non-2xx response,
    /// [`Error::Http`](crate::errors::Error::Http) for transport failures, and
    /// [`Error::Json`](crate::errors::Error::Json) if the request cannot be serialized or the response cannot be decoded.
    pub async fn create(
        &self,
        body: &crate::gaos::types::credentials::CredentialCreateParams,
    ) -> Result<crate::gaos::types::credentials::Credential> {
        let url_path = "credentials";
        let query: Option<String> = None;
        let body = serde_json::to_value(body)?;
        let response = self
            .client
            .http()
            .request(
                Method::POST,
                url_path,
                query.as_deref(),
                Some(body),
                self.http_options.as_ref(),
            )
            .await?;
        wire::parse(&response.body)
    }

    /// Deletes a credential.
    ///
    /// `DELETE /{api_version}/credentials/{id}`.
    ///
    /// # Errors
    /// Returns [`Error::Api`](crate::errors::Error::Api) for a non-2xx response,
    /// [`Error::Http`](crate::errors::Error::Http) for transport failures, and
    /// [`Error::Json`](crate::errors::Error::Json) if the request cannot be serialized or the response cannot be decoded.
    pub async fn delete(&self, id: &str) -> Result<crate::gaos::types::interactions::Empty> {
        let url_path = format!("credentials/{}", wire::path_segment(id));
        let query: Option<String> = None;
        let response = self
            .client
            .http()
            .request(
                Method::DELETE,
                &url_path,
                query.as_deref(),
                None,
                self.http_options.as_ref(),
            )
            .await?;
        wire::parse(&response.body)
    }

    /// Gets a credential by ID.
    ///
    /// `GET /{api_version}/credentials/{id}`.
    ///
    /// # Errors
    /// Returns [`Error::Api`](crate::errors::Error::Api) for a non-2xx response,
    /// [`Error::Http`](crate::errors::Error::Http) for transport failures, and
    /// [`Error::Json`](crate::errors::Error::Json) if the request cannot be serialized or the response cannot be decoded.
    pub async fn get(&self, id: &str) -> Result<crate::gaos::types::credentials::Credential> {
        let url_path = format!("credentials/{}", wire::path_segment(id));
        let query: Option<String> = None;
        let response = self
            .client
            .http()
            .request(
                Method::GET,
                &url_path,
                query.as_deref(),
                None,
                self.http_options.as_ref(),
            )
            .await?;
        wire::parse(&response.body)
    }

    /// Updates a credential.
    ///
    /// `PATCH /{api_version}/credentials/{id}`.
    ///
    /// # Errors
    /// Returns [`Error::Api`](crate::errors::Error::Api) for a non-2xx response,
    /// [`Error::Http`](crate::errors::Error::Http) for transport failures, and
    /// [`Error::Json`](crate::errors::Error::Json) if the request cannot be serialized or the response cannot be decoded.
    pub async fn update(
        &self,
        id: &str,
        body: &crate::gaos::types::credentials::CredentialUpdate,
        params: &crate::gaos::models::UpdateCredentialRequest,
    ) -> Result<crate::gaos::types::credentials::Credential> {
        let url_path = format!("credentials/{}", wire::path_segment(id));
        let mut query = wire::Query::default();
        query.push("update_mask", params.update_mask.as_ref());
        let query = query.finish();
        let body = serde_json::to_value(body)?;
        let response = self
            .client
            .http()
            .request(
                Method::PATCH,
                &url_path,
                query.as_deref(),
                Some(body),
                self.http_options.as_ref(),
            )
            .await?;
        wire::parse(&response.body)
    }
}
