// @generated by tools/codegen/gen_gaos.py from google-genai 2.28.0. DO NOT EDIT.
//
// SPDX-FileCopyrightText: 2025 Google LLC
// SPDX-FileCopyrightText: 2026 Daisuke ITO
// SPDX-License-Identifier: Apache-2.0
//
// Derived from the Google Gen AI Python SDK (google-genai 2.28.0),
// https://github.com/googleapis/python-genai
// Copyright 2025 Google LLC, licensed under the Apache License, Version 2.0.
//
// Modified: mechanically derived from the Python SDK's internal `_gaos` sub-SDK by gen_gaos.py:
// model fields, string enums and unions were reflected into Rust types, and HTTP
// operations were extracted from the resource classes. Doc comments reproduce the
// upstream Python docstrings.
//
// See the NOTICE file at the repository root for the full attribution.
//
// Edit tools/codegen/gen_gaos.py (or tools/codegen/gaos_overrides.toml) and re-run
// `python tools/codegen/generate.py --only gaos` instead.

//! Resource handles of the `_gaos` sub-SDK, one module per resource.

#![allow(
    clippy::pedantic,
    clippy::large_enum_variant,
    clippy::enum_variant_names,
    dead_code,
    rustdoc::bare_urls,
    reason = "mechanically generated port of the google-genai `_gaos` sub-SDK; pedantic-tier style lints, size-based enum lints and bare-URL doc warnings do not apply to a generated public API surface whose doc comments are verbatim Python docstrings"
)]

pub mod agents;
pub mod credentials;
pub mod environments;
pub mod interactions;
pub mod triggers;
pub mod voices;
pub mod webhooks;
