// @generated by tools/codegen/gen_gaos.py from google-genai 2.28.0. DO NOT EDIT.
//
// SPDX-FileCopyrightText: 2025 Google LLC
// SPDX-FileCopyrightText: 2026 Daisuke ITO
// SPDX-License-Identifier: Apache-2.0
//
// Derived from the Google Gen AI Python SDK (google-genai 2.28.0),
// https://github.com/googleapis/python-genai
// Copyright 2025 Google LLC, licensed under the Apache License, Version 2.0.
//
// Modified: mechanically derived from the Python SDK's internal `_gaos` sub-SDK by gen_gaos.py:
// model fields, string enums and unions were reflected into Rust types, and HTTP
// operations were extracted from the resource classes. Doc comments reproduce the
// upstream Python docstrings.
//
// See the NOTICE file at the repository root for the full attribution.
//
// Edit tools/codegen/gen_gaos.py (or tools/codegen/gaos_overrides.toml) and re-run
// `python tools/codegen/generate.py --only gaos` instead.

//! `client.webhooks()`: the `_gaos` `webhooks` operations. Generated from
//! `google/genai/_gaos/webhooks.py`.

#![allow(
    clippy::pedantic,
    clippy::large_enum_variant,
    clippy::enum_variant_names,
    dead_code,
    rustdoc::bare_urls,
    reason = "mechanically generated port of the google-genai `_gaos` sub-SDK; pedantic-tier style lints, size-based enum lints and bare-URL doc warnings do not apply to a generated public API surface whose doc comments are verbatim Python docstrings"
)]

use reqwest::Method;

use crate::{client::Client, errors::Result, gaos::wire, types::HttpOptions};

/// Handle for the `webhooks` operations (`client.webhooks()`).
#[derive(Debug, Clone)]
pub struct Webhooks {
    pub(crate) client: Client,
    pub(crate) http_options: Option<HttpOptions>,
}

impl Webhooks {
    pub(crate) fn new(client: Client) -> Self {
        Self {
            client,
            http_options: None,
        }
    }

    /// Returns a handle whose calls use `options` instead of the client's `HttpOptions`:
    /// extra `headers`, a per-call `api_version`, `timeout`, `extra_body` or `retry_options`
    /// (the upstream per-call `extra_headers` / `api_version` / `timeout` arguments).
    #[must_use]
    pub fn with_http_options(mut self, options: HttpOptions) -> Self {
        self.http_options = Some(options);
        self
    }

    /// Lists all Webhooks.
    ///
    /// `GET /{api_version}/webhooks`.
    ///
    /// # Errors
    /// Returns [`Error::Api`](crate::errors::Error::Api) for a non-2xx response,
    /// [`Error::Http`](crate::errors::Error::Http) for transport failures, and
    /// [`Error::Json`](crate::errors::Error::Json) if the request cannot be serialized or the response cannot be decoded.
    pub async fn list(
        &self,
        params: &crate::gaos::models::ListWebhooksRequest,
    ) -> Result<crate::gaos::types::webhooks::WebhookListResponse> {
        let url_path = "webhooks";
        let mut query = wire::Query::default();
        query.push("page_size", params.page_size.as_ref());
        query.push("page_token", params.page_token.as_ref());
        let query = query.finish();
        let response = self
            .client
            .http()
            .request(
                Method::GET,
                url_path,
                query.as_deref(),
                None,
                self.http_options.as_ref(),
            )
            .await?;
        wire::parse(&response.body)
    }

    /// Creates a new Webhook.
    ///
    /// `POST /{api_version}/webhooks`.
    ///
    /// # Errors
    /// Returns [`Error::Api`](crate::errors::Error::Api) for a non-2xx response,
    /// [`Error::Http`](crate::errors::Error::Http) for transport failures, and
    /// [`Error::Json`](crate::errors::Error::Json) if the request cannot be serialized or the response cannot be decoded.
    pub async fn create(
        &self,
        body: &crate::gaos::types::webhooks::WebhookInput,
    ) -> Result<crate::gaos::types::webhooks::Webhook> {
        let url_path = "webhooks";
        let query: Option<String> = None;
        let body = serde_json::to_value(body)?;
        let response = self
            .client
            .http()
            .request(
                Method::POST,
                url_path,
                query.as_deref(),
                Some(body),
                self.http_options.as_ref(),
            )
            .await?;
        wire::parse(&response.body)
    }

    /// Deletes a Webhook.
    ///
    /// `DELETE /{api_version}/webhooks/{id}`.
    ///
    /// # Errors
    /// Returns [`Error::Api`](crate::errors::Error::Api) for a non-2xx response,
    /// [`Error::Http`](crate::errors::Error::Http) for transport failures, and
    /// [`Error::Json`](crate::errors::Error::Json) if the request cannot be serialized or the response cannot be decoded.
    pub async fn delete(&self, id: &str) -> Result<crate::gaos::types::interactions::Empty> {
        let url_path = format!("webhooks/{}", wire::path_segment(id));
        let query: Option<String> = None;
        let response = self
            .client
            .http()
            .request(
                Method::DELETE,
                &url_path,
                query.as_deref(),
                None,
                self.http_options.as_ref(),
            )
            .await?;
        wire::parse(&response.body)
    }

    /// Gets a specific Webhook.
    ///
    /// `GET /{api_version}/webhooks/{id}`.
    ///
    /// # Errors
    /// Returns [`Error::Api`](crate::errors::Error::Api) for a non-2xx response,
    /// [`Error::Http`](crate::errors::Error::Http) for transport failures, and
    /// [`Error::Json`](crate::errors::Error::Json) if the request cannot be serialized or the response cannot be decoded.
    pub async fn get(&self, id: &str) -> Result<crate::gaos::types::webhooks::Webhook> {
        let url_path = format!("webhooks/{}", wire::path_segment(id));
        let query: Option<String> = None;
        let response = self
            .client
            .http()
            .request(
                Method::GET,
                &url_path,
                query.as_deref(),
                None,
                self.http_options.as_ref(),
            )
            .await?;
        wire::parse(&response.body)
    }

    /// Updates an existing Webhook.
    ///
    /// `PATCH /{api_version}/webhooks/{id}`.
    ///
    /// # Errors
    /// Returns [`Error::Api`](crate::errors::Error::Api) for a non-2xx response,
    /// [`Error::Http`](crate::errors::Error::Http) for transport failures, and
    /// [`Error::Json`](crate::errors::Error::Json) if the request cannot be serialized or the response cannot be decoded.
    pub async fn update(
        &self,
        id: &str,
        body: Option<&crate::gaos::types::webhooks::WebhookUpdate>,
        params: &crate::gaos::models::UpdateWebhookRequest,
    ) -> Result<crate::gaos::types::webhooks::Webhook> {
        let url_path = format!("webhooks/{}", wire::path_segment(id));
        let mut query = wire::Query::default();
        query.push("update_mask", params.update_mask.as_ref());
        let query = query.finish();
        let body = body.map(serde_json::to_value).transpose()?;
        let response = self
            .client
            .http()
            .request(
                Method::PATCH,
                &url_path,
                query.as_deref(),
                body,
                self.http_options.as_ref(),
            )
            .await?;
        wire::parse(&response.body)
    }

    /// Sends a ping event to a Webhook.
    ///
    /// `POST /{api_version}/webhooks/{id}:ping`.
    ///
    /// # Errors
    /// Returns [`Error::Api`](crate::errors::Error::Api) for a non-2xx response,
    /// [`Error::Http`](crate::errors::Error::Http) for transport failures, and
    /// [`Error::Json`](crate::errors::Error::Json) if the request cannot be serialized or the response cannot be decoded.
    pub async fn ping(
        &self,
        id: &str,
        body: Option<&crate::gaos::types::webhooks::PingWebhookRequest>,
    ) -> Result<crate::gaos::types::webhooks::WebhookPingResponse> {
        let url_path = format!("webhooks/{}:ping", wire::path_segment(id));
        let query: Option<String> = None;
        let body = body.map(serde_json::to_value).transpose()?;
        let response = self
            .client
            .http()
            .request(
                Method::POST,
                &url_path,
                query.as_deref(),
                body,
                self.http_options.as_ref(),
            )
            .await?;
        wire::parse(&response.body)
    }

    /// Generates a new signing secret for a Webhook.
    ///
    /// `POST /{api_version}/webhooks/{id}:rotateSigningSecret`.
    ///
    /// # Errors
    /// Returns [`Error::Api`](crate::errors::Error::Api) for a non-2xx response,
    /// [`Error::Http`](crate::errors::Error::Http) for transport failures, and
    /// [`Error::Json`](crate::errors::Error::Json) if the request cannot be serialized or the response cannot be decoded.
    pub async fn rotate_signing_secret(
        &self,
        id: &str,
        body: Option<&crate::gaos::types::webhooks::RotateSigningSecretRequest>,
    ) -> Result<crate::gaos::types::webhooks::WebhookRotateSigningSecretResponse> {
        let url_path = format!("webhooks/{}:rotateSigningSecret", wire::path_segment(id));
        let query: Option<String> = None;
        let body = body.map(serde_json::to_value).transpose()?;
        let response = self
            .client
            .http()
            .request(
                Method::POST,
                &url_path,
                query.as_deref(),
                body,
                self.http_options.as_ref(),
            )
            .await?;
        wire::parse(&response.body)
    }
}
