// @generated by tools/codegen/gen_blocking.py from methods.toml. DO NOT EDIT.
//
// SPDX-FileCopyrightText: 2025 Google LLC
// SPDX-FileCopyrightText: 2026 Daisuke ITO
// SPDX-License-Identifier: Apache-2.0
//
// Derived from the Google Gen AI Python SDK (google-genai 2.28.0),
// https://github.com/googleapis/python-genai
// Copyright 2025 Google LLC, licensed under the Apache License, Version 2.0.
//
// Modified: the method inventory in `methods.toml` is derived from the upstream
// SDK's public API surface; gen_blocking.py generates blocking wrappers
// over this crate's own async port of it.
//
// See the NOTICE file at the repository root for the full attribution.
//
// Edit tools/codegen/gen_blocking.py (or tools/codegen/methods.toml) and
// re-run `python tools/codegen/generate.py --only blocking` instead.
//! Blocking (`feature = "blocking"`) wrappers for every `Client`-accessor
//! module's async methods, generated from `tools/codegen/methods.toml`
//! against google-genai 2.28.0's method inventory. `Chat` (returned by
//! `Chats::create`), `Operations::get<T>`, and `FileSearchStores::documents()`
//! are hand-written in `src/blocking/mod.rs` instead -- see that file and
//! `methods.toml`'s header comment.

#![allow(
    clippy::pedantic,
    dead_code,
    reason = "mechanically generated 1:1 blocking wrappers around this crate's own async API; pedantic-tier style lints don't apply, and not every wrapper method is necessarily exercised by every feature combination"
)]

/// Blocking wrapper for [`crate::models::Models`] (`client.models()`).
pub struct Models {
    pub(crate) runtime: std::sync::Arc<crate::blocking::Runtime>,
    pub(crate) inner: crate::models::Models,
}

impl Models {
    pub(crate) fn new(
        runtime: std::sync::Arc<crate::blocking::Runtime>,
        inner: crate::models::Models,
    ) -> Self {
        Self { runtime, inner }
    }

    /// Blocking wrapper for [`crate::models::Models::generate_content`] (Python `models.generate_content`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn generate_content(
        &self,
        model: &str,
        contents: impl Into<crate::types::Contents>,
        config: Option<crate::types::GenerateContentConfig>,
    ) -> crate::errors::Result<crate::types::GenerateContentResponse> {
        self.runtime
            .block_on(self.inner.generate_content(model, contents, config))?
    }

    /// Blocking wrapper for [`crate::models::Models::generate_content_stream`] (Python `models.generate_content_stream`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn generate_content_stream(
        &self,
        model: &str,
        contents: impl Into<crate::types::Contents>,
        config: Option<crate::types::GenerateContentConfig>,
    ) -> crate::errors::Result<crate::blocking::BlockingStream<crate::types::GenerateContentResponse>>
    {
        let stream = self
            .runtime
            .block_on(self.inner.generate_content_stream(model, contents, config))??;
        Ok(crate::blocking::BlockingStream::new(
            std::sync::Arc::clone(&self.runtime),
            stream,
        ))
    }

    /// Blocking wrapper for [`crate::models::Models::embed_content`] (Python `models.embed_content`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn embed_content(
        &self,
        model: &str,
        contents: impl Into<crate::types::Contents>,
        config: Option<crate::types::EmbedContentConfig>,
    ) -> crate::errors::Result<crate::types::EmbedContentResponse> {
        self.runtime
            .block_on(self.inner.embed_content(model, contents, config))?
    }

    /// Blocking wrapper for [`crate::models::Models::count_tokens`] (Python `models.count_tokens`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn count_tokens(
        &self,
        model: &str,
        contents: impl Into<crate::types::Contents>,
        config: Option<crate::types::CountTokensConfig>,
    ) -> crate::errors::Result<crate::types::CountTokensResponse> {
        self.runtime
            .block_on(self.inner.count_tokens(model, contents, config))?
    }

    /// Blocking wrapper for [`crate::models::Models::compute_tokens`] (Python `models.compute_tokens`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn compute_tokens(
        &self,
        model: &str,
        contents: impl Into<crate::types::Contents>,
        config: Option<serde_json::Value>,
    ) -> crate::errors::Result<crate::types::ComputeTokensResponse> {
        self.runtime
            .block_on(self.inner.compute_tokens(model, contents, config))?
    }

    /// Blocking wrapper for [`crate::models::Models::get`] (Python `models.get`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn get(
        &self,
        model: &str,
        config: Option<crate::types::GetModelConfig>,
    ) -> crate::errors::Result<crate::types::Model> {
        self.runtime.block_on(self.inner.get(model, config))?
    }

    /// Blocking wrapper for [`crate::models::Models::list`] (Python `models.list`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn list(
        &self,
        config: Option<crate::types::ListModelsConfig>,
    ) -> crate::errors::Result<crate::blocking::Pager<crate::types::Model>> {
        let pager = self.runtime.block_on(self.inner.list(config))??;
        Ok(crate::blocking::Pager::new(
            std::sync::Arc::clone(&self.runtime),
            pager,
        ))
    }

    /// Blocking wrapper for [`crate::models::Models::update`] (Python `models.update`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn update(
        &self,
        model: &str,
        config: crate::types::UpdateModelConfig,
    ) -> crate::errors::Result<crate::types::Model> {
        self.runtime.block_on(self.inner.update(model, config))?
    }

    /// Blocking wrapper for [`crate::models::Models::delete`] (Python `models.delete`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn delete(
        &self,
        model: &str,
        config: Option<crate::types::DeleteModelConfig>,
    ) -> crate::errors::Result<crate::types::DeleteModelResponse> {
        self.runtime.block_on(self.inner.delete(model, config))?
    }

    /// Blocking wrapper for [`crate::models::Models::generate_images`] (Python `models.generate_images`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    #[expect(
        deprecated,
        reason = "parity wrapper around the deprecated async method"
    )]
    pub fn generate_images(
        &self,
        model: &str,
        prompt: &str,
        config: Option<crate::types::GenerateImagesConfig>,
    ) -> crate::errors::Result<crate::types::GenerateImagesResponse> {
        self.runtime
            .block_on(self.inner.generate_images(model, prompt, config))?
    }

    /// Blocking wrapper for [`crate::models::Models::generate_videos`] (Python `models.generate_videos`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn generate_videos(
        &self,
        model: &str,
        source: crate::types::GenerateVideosSource,
        config: Option<crate::types::GenerateVideosConfig>,
    ) -> crate::errors::Result<crate::types::GenerateVideosOperation> {
        self.runtime
            .block_on(self.inner.generate_videos(model, source, config))?
    }
}

/// Blocking wrapper for [`crate::chats::Chats`] (`client.chats()`).
pub struct Chats {
    pub(crate) runtime: std::sync::Arc<crate::blocking::Runtime>,
    pub(crate) inner: crate::chats::Chats,
}

impl Chats {
    pub(crate) fn new(
        runtime: std::sync::Arc<crate::blocking::Runtime>,
        inner: crate::chats::Chats,
    ) -> Self {
        Self { runtime, inner }
    }
}

/// Blocking wrapper for [`crate::files::Files`] (`client.files()`).
pub struct Files {
    pub(crate) runtime: std::sync::Arc<crate::blocking::Runtime>,
    pub(crate) inner: crate::files::Files,
}

impl Files {
    pub(crate) fn new(
        runtime: std::sync::Arc<crate::blocking::Runtime>,
        inner: crate::files::Files,
    ) -> Self {
        Self { runtime, inner }
    }

    /// Blocking wrapper for [`crate::files::Files::upload`] (Python `files.upload`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn upload(
        &self,
        source: impl Into<crate::files::UploadSource>,
        config: Option<crate::types::UploadFileConfig>,
    ) -> crate::errors::Result<crate::types::File> {
        self.runtime.block_on(self.inner.upload(source, config))?
    }

    /// Blocking wrapper for [`crate::files::Files::get`] (Python `files.get`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn get(
        &self,
        name: &str,
        config: Option<crate::types::GetFileConfig>,
    ) -> crate::errors::Result<crate::types::File> {
        self.runtime.block_on(self.inner.get(name, config))?
    }

    /// Blocking wrapper for [`crate::files::Files::list`] (Python `files.list`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn list(
        &self,
        config: Option<crate::types::ListFilesConfig>,
    ) -> crate::errors::Result<crate::blocking::Pager<crate::types::File>> {
        let pager = self.runtime.block_on(self.inner.list(config))??;
        Ok(crate::blocking::Pager::new(
            std::sync::Arc::clone(&self.runtime),
            pager,
        ))
    }

    /// Blocking wrapper for [`crate::files::Files::delete`] (Python `files.delete`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn delete(
        &self,
        name: &str,
        config: Option<crate::types::DeleteFileConfig>,
    ) -> crate::errors::Result<crate::types::DeleteFileResponse> {
        self.runtime.block_on(self.inner.delete(name, config))?
    }

    /// Blocking wrapper for [`crate::files::Files::download`] (Python `files.download`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn download(
        &self,
        file: &str,
        config: Option<crate::types::DownloadFileConfig>,
    ) -> crate::errors::Result<bytes::Bytes> {
        self.runtime.block_on(self.inner.download(file, config))?
    }

    /// Blocking wrapper for [`crate::files::Files::download_stream`] (Python `files.download`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn download_stream(
        &self,
        file: impl Into<crate::files::FileSource>,
        config: Option<crate::types::DownloadFileConfig>,
    ) -> crate::errors::Result<crate::blocking::BlockingStream<bytes::Bytes>> {
        let stream = self
            .runtime
            .block_on(self.inner.download_stream(file, config))??;
        Ok(crate::blocking::BlockingStream::new(
            std::sync::Arc::clone(&self.runtime),
            stream,
        ))
    }

    /// Blocking wrapper for [`crate::files::Files::download_to_path`] (Python `files.download`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn download_to_path(
        &self,
        file: impl Into<crate::files::FileSource>,
        destination: &std::path::Path,
        config: Option<crate::types::DownloadFileConfig>,
    ) -> crate::errors::Result<()> {
        self.runtime
            .block_on(self.inner.download_to_path(file, destination, config))?
    }

    /// Blocking wrapper for [`crate::files::Files::register_files`] (Python `files._register_files`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn register_files(
        &self,
        uris: Vec<String>,
        config: Option<crate::types::RegisterFilesConfig>,
    ) -> crate::errors::Result<crate::types::RegisterFilesResponse> {
        self.runtime
            .block_on(self.inner.register_files(uris, config))?
    }
}

/// Blocking wrapper for [`crate::caches::Caches`] (`client.caches()`).
pub struct Caches {
    pub(crate) runtime: std::sync::Arc<crate::blocking::Runtime>,
    pub(crate) inner: crate::caches::Caches,
}

impl Caches {
    pub(crate) fn new(
        runtime: std::sync::Arc<crate::blocking::Runtime>,
        inner: crate::caches::Caches,
    ) -> Self {
        Self { runtime, inner }
    }

    /// Blocking wrapper for [`crate::caches::Caches::create`] (Python `caches.create`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn create(
        &self,
        model: &str,
        config: Option<crate::types::CreateCachedContentConfig>,
    ) -> crate::errors::Result<crate::types::CachedContent> {
        self.runtime.block_on(self.inner.create(model, config))?
    }

    /// Blocking wrapper for [`crate::caches::Caches::get`] (Python `caches.get`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn get(
        &self,
        name: &str,
        config: Option<crate::types::GetCachedContentConfig>,
    ) -> crate::errors::Result<crate::types::CachedContent> {
        self.runtime.block_on(self.inner.get(name, config))?
    }

    /// Blocking wrapper for [`crate::caches::Caches::list`] (Python `caches.list`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn list(
        &self,
        config: Option<crate::types::ListCachedContentsConfig>,
    ) -> crate::errors::Result<crate::blocking::Pager<crate::types::CachedContent>> {
        let pager = self.runtime.block_on(self.inner.list(config))??;
        Ok(crate::blocking::Pager::new(
            std::sync::Arc::clone(&self.runtime),
            pager,
        ))
    }

    /// Blocking wrapper for [`crate::caches::Caches::update`] (Python `caches.update`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn update(
        &self,
        name: &str,
        config: Option<crate::types::UpdateCachedContentConfig>,
    ) -> crate::errors::Result<crate::types::CachedContent> {
        self.runtime.block_on(self.inner.update(name, config))?
    }

    /// Blocking wrapper for [`crate::caches::Caches::delete`] (Python `caches.delete`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn delete(
        &self,
        name: &str,
        config: Option<crate::types::DeleteCachedContentConfig>,
    ) -> crate::errors::Result<crate::types::DeleteCachedContentResponse> {
        self.runtime.block_on(self.inner.delete(name, config))?
    }
}

/// Blocking wrapper for [`crate::tunings::Tunings`] (`client.tunings()`).
pub struct Tunings {
    pub(crate) runtime: std::sync::Arc<crate::blocking::Runtime>,
    pub(crate) inner: crate::tunings::Tunings,
}

impl Tunings {
    pub(crate) fn new(
        runtime: std::sync::Arc<crate::blocking::Runtime>,
        inner: crate::tunings::Tunings,
    ) -> Self {
        Self { runtime, inner }
    }

    /// Blocking wrapper for [`crate::tunings::Tunings::tune`] (Python `tunings.tune`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn tune(
        &self,
        base_model: &str,
        training_dataset: crate::types::TuningDataset,
        config: Option<crate::types::CreateTuningJobConfig>,
    ) -> crate::errors::Result<crate::types::TuningJob> {
        self.runtime
            .block_on(self.inner.tune(base_model, training_dataset, config))?
    }

    /// Blocking wrapper for [`crate::tunings::Tunings::get`] (Python `tunings.get`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn get(
        &self,
        name: &str,
        config: Option<crate::types::GetTuningJobConfig>,
    ) -> crate::errors::Result<crate::types::TuningJob> {
        self.runtime.block_on(self.inner.get(name, config))?
    }

    /// Blocking wrapper for [`crate::tunings::Tunings::list`] (Python `tunings.list`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn list(
        &self,
        config: Option<crate::types::ListTuningJobsConfig>,
    ) -> crate::errors::Result<crate::blocking::Pager<crate::types::TuningJob>> {
        let pager = self.runtime.block_on(self.inner.list(config))??;
        Ok(crate::blocking::Pager::new(
            std::sync::Arc::clone(&self.runtime),
            pager,
        ))
    }

    /// Blocking wrapper for [`crate::tunings::Tunings::cancel`] (Python `tunings.cancel`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn cancel(
        &self,
        name: &str,
        config: Option<crate::types::CancelTuningJobConfig>,
    ) -> crate::errors::Result<crate::types::CancelTuningJobResponse> {
        self.runtime.block_on(self.inner.cancel(name, config))?
    }
}

/// Blocking wrapper for [`crate::batches::Batches`] (`client.batches()`).
pub struct Batches {
    pub(crate) runtime: std::sync::Arc<crate::blocking::Runtime>,
    pub(crate) inner: crate::batches::Batches,
}

impl Batches {
    pub(crate) fn new(
        runtime: std::sync::Arc<crate::blocking::Runtime>,
        inner: crate::batches::Batches,
    ) -> Self {
        Self { runtime, inner }
    }

    /// Blocking wrapper for [`crate::batches::Batches::create`] (Python `batches.create`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn create(
        &self,
        model: &str,
        src: impl Into<crate::types::BatchJobSource>,
        config: Option<crate::types::CreateBatchJobConfig>,
    ) -> crate::errors::Result<crate::types::BatchJob> {
        self.runtime
            .block_on(self.inner.create(model, src, config))?
    }

    /// Blocking wrapper for [`crate::batches::Batches::create_embeddings`] (Python `batches.create_embeddings`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn create_embeddings(
        &self,
        model: &str,
        src: crate::types::EmbeddingsBatchJobSource,
        config: Option<crate::types::CreateEmbeddingsBatchJobConfig>,
    ) -> crate::errors::Result<crate::types::BatchJob> {
        self.runtime
            .block_on(self.inner.create_embeddings(model, src, config))?
    }

    /// Blocking wrapper for [`crate::batches::Batches::get`] (Python `batches.get`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn get(
        &self,
        name: &str,
        config: Option<crate::types::GetBatchJobConfig>,
    ) -> crate::errors::Result<crate::types::BatchJob> {
        self.runtime.block_on(self.inner.get(name, config))?
    }

    /// Blocking wrapper for [`crate::batches::Batches::cancel`] (Python `batches.cancel`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn cancel(
        &self,
        name: &str,
        config: Option<crate::types::CancelBatchJobConfig>,
    ) -> crate::errors::Result<()> {
        self.runtime.block_on(self.inner.cancel(name, config))?
    }

    /// Blocking wrapper for [`crate::batches::Batches::delete`] (Python `batches.delete`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn delete(
        &self,
        name: &str,
        config: Option<crate::types::DeleteBatchJobConfig>,
    ) -> crate::errors::Result<crate::types::DeleteResourceJob> {
        self.runtime.block_on(self.inner.delete(name, config))?
    }

    /// Blocking wrapper for [`crate::batches::Batches::list`] (Python `batches.list`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn list(
        &self,
        config: Option<crate::types::ListBatchJobsConfig>,
    ) -> crate::errors::Result<crate::blocking::Pager<crate::types::BatchJob>> {
        let pager = self.runtime.block_on(self.inner.list(config))??;
        Ok(crate::blocking::Pager::new(
            std::sync::Arc::clone(&self.runtime),
            pager,
        ))
    }
}

/// Blocking wrapper for [`crate::operations::Operations`] (`client.operations()`).
pub struct Operations {
    pub(crate) runtime: std::sync::Arc<crate::blocking::Runtime>,
    pub(crate) inner: crate::operations::Operations,
}

impl Operations {
    pub(crate) fn new(
        runtime: std::sync::Arc<crate::blocking::Runtime>,
        inner: crate::operations::Operations,
    ) -> Self {
        Self { runtime, inner }
    }
}

/// Blocking wrapper for [`crate::file_search_stores::FileSearchStores`] (`client.file_search_stores()`).
pub struct FileSearchStores {
    pub(crate) runtime: std::sync::Arc<crate::blocking::Runtime>,
    pub(crate) inner: crate::file_search_stores::FileSearchStores,
}

impl FileSearchStores {
    pub(crate) fn new(
        runtime: std::sync::Arc<crate::blocking::Runtime>,
        inner: crate::file_search_stores::FileSearchStores,
    ) -> Self {
        Self { runtime, inner }
    }

    /// Blocking wrapper for [`crate::file_search_stores::FileSearchStores::create`] (Python `file_search_stores.create`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn create(
        &self,
        config: Option<crate::types::CreateFileSearchStoreConfig>,
    ) -> crate::errors::Result<crate::types::FileSearchStore> {
        self.runtime.block_on(self.inner.create(config))?
    }

    /// Blocking wrapper for [`crate::file_search_stores::FileSearchStores::get`] (Python `file_search_stores.get`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn get(
        &self,
        name: &str,
        config: Option<crate::types::GetFileSearchStoreConfig>,
    ) -> crate::errors::Result<crate::types::FileSearchStore> {
        self.runtime.block_on(self.inner.get(name, config))?
    }

    /// Blocking wrapper for [`crate::file_search_stores::FileSearchStores::delete`] (Python `file_search_stores.delete`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn delete(
        &self,
        name: &str,
        config: Option<crate::types::DeleteFileSearchStoreConfig>,
    ) -> crate::errors::Result<()> {
        self.runtime.block_on(self.inner.delete(name, config))?
    }

    /// Blocking wrapper for [`crate::file_search_stores::FileSearchStores::list`] (Python `file_search_stores.list`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn list(
        &self,
        config: Option<crate::types::ListFileSearchStoresConfig>,
    ) -> crate::errors::Result<crate::blocking::Pager<crate::types::FileSearchStore>> {
        let pager = self.runtime.block_on(self.inner.list(config))??;
        Ok(crate::blocking::Pager::new(
            std::sync::Arc::clone(&self.runtime),
            pager,
        ))
    }

    /// Blocking wrapper for [`crate::file_search_stores::FileSearchStores::import_file`] (Python `file_search_stores.import_file`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn import_file(
        &self,
        file_search_store_name: &str,
        file_name: &str,
        config: Option<crate::types::ImportFileConfig>,
    ) -> crate::errors::Result<crate::types::ImportFileOperation> {
        self.runtime.block_on(
            self.inner
                .import_file(file_search_store_name, file_name, config),
        )?
    }

    /// Blocking wrapper for [`crate::file_search_stores::FileSearchStores::upload_to_file_search_store`] (Python `file_search_stores.upload_to_file_search_store`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn upload_to_file_search_store(
        &self,
        file_search_store_name: &str,
        data: &[u8],
        mime_type: &str,
        config: Option<crate::types::UploadToFileSearchStoreConfig>,
    ) -> crate::errors::Result<crate::types::UploadToFileSearchStoreOperation> {
        self.runtime
            .block_on(self.inner.upload_to_file_search_store(
                file_search_store_name,
                data,
                mime_type,
                config,
            ))?
    }

    /// Blocking wrapper for [`crate::file_search_stores::FileSearchStores::download_media`] (Python `file_search_stores.download_media`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn download_media(
        &self,
        media_id: &str,
        config: Option<crate::types::DownloadMediaConfig>,
    ) -> crate::errors::Result<bytes::Bytes> {
        self.runtime
            .block_on(self.inner.download_media(media_id, config))?
    }
}

/// Blocking wrapper for [`crate::documents::Documents`] (`client.documents()`).
pub struct Documents {
    pub(crate) runtime: std::sync::Arc<crate::blocking::Runtime>,
    pub(crate) inner: crate::documents::Documents,
}

impl Documents {
    pub(crate) fn new(
        runtime: std::sync::Arc<crate::blocking::Runtime>,
        inner: crate::documents::Documents,
    ) -> Self {
        Self { runtime, inner }
    }

    /// Blocking wrapper for [`crate::documents::Documents::get`] (Python `documents.get`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn get(
        &self,
        name: &str,
        config: Option<crate::types::GetDocumentConfig>,
    ) -> crate::errors::Result<crate::types::Document> {
        self.runtime.block_on(self.inner.get(name, config))?
    }

    /// Blocking wrapper for [`crate::documents::Documents::delete`] (Python `documents.delete`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn delete(
        &self,
        name: &str,
        config: Option<crate::types::DeleteDocumentConfig>,
    ) -> crate::errors::Result<()> {
        self.runtime.block_on(self.inner.delete(name, config))?
    }

    /// Blocking wrapper for [`crate::documents::Documents::list`] (Python `documents.list`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn list(
        &self,
        parent: &str,
        config: Option<crate::types::ListDocumentsConfig>,
    ) -> crate::errors::Result<crate::blocking::Pager<crate::types::Document>> {
        let pager = self.runtime.block_on(self.inner.list(parent, config))??;
        Ok(crate::blocking::Pager::new(
            std::sync::Arc::clone(&self.runtime),
            pager,
        ))
    }
}

/// Blocking wrapper for [`crate::tokens::AuthTokens`] (`client.auth_tokens()`).
pub struct AuthTokens {
    pub(crate) runtime: std::sync::Arc<crate::blocking::Runtime>,
    pub(crate) inner: crate::tokens::AuthTokens,
}

impl AuthTokens {
    pub(crate) fn new(
        runtime: std::sync::Arc<crate::blocking::Runtime>,
        inner: crate::tokens::AuthTokens,
    ) -> Self {
        Self { runtime, inner }
    }

    /// Blocking wrapper for [`crate::tokens::AuthTokens::create`] (Python `tokens.create`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn create(
        &self,
        config: Option<crate::types::CreateAuthTokenConfig>,
    ) -> crate::errors::Result<crate::types::AuthToken> {
        self.runtime.block_on(self.inner.create(config))?
    }
}

/// Blocking wrapper for [`crate::gaos::resources::agents::Agents`] (`client.agents()`).
pub struct Agents {
    pub(crate) runtime: std::sync::Arc<crate::blocking::Runtime>,
    pub(crate) inner: crate::gaos::resources::agents::Agents,
}

impl Agents {
    pub(crate) fn new(
        runtime: std::sync::Arc<crate::blocking::Runtime>,
        inner: crate::gaos::resources::agents::Agents,
    ) -> Self {
        Self { runtime, inner }
    }

    /// Blocking wrapper for [`crate::gaos::resources::agents::Agents::list`] (Python `agents.list`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn list(
        &self,
        params: &crate::gaos::models::ListAgentsRequest,
    ) -> crate::errors::Result<crate::gaos::types::agents::AgentListResponse> {
        self.runtime.block_on(self.inner.list(params))?
    }

    /// Blocking wrapper for [`crate::gaos::resources::agents::Agents::create`] (Python `agents.create`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn create(
        &self,
        body: &crate::gaos::types::agents::Agent,
    ) -> crate::errors::Result<crate::gaos::types::agents::Agent> {
        self.runtime.block_on(self.inner.create(body))?
    }

    /// Blocking wrapper for [`crate::gaos::resources::agents::Agents::delete`] (Python `agents.delete`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn delete(
        &self,
        id: &str,
    ) -> crate::errors::Result<crate::gaos::types::interactions::Empty> {
        self.runtime.block_on(self.inner.delete(id))?
    }

    /// Blocking wrapper for [`crate::gaos::resources::agents::Agents::get`] (Python `agents.get`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn get(&self, id: &str) -> crate::errors::Result<crate::gaos::types::agents::Agent> {
        self.runtime.block_on(self.inner.get(id))?
    }
}

/// Blocking wrapper for [`crate::gaos::resources::credentials::Credentials`] (`client.credentials()`).
pub struct Credentials {
    pub(crate) runtime: std::sync::Arc<crate::blocking::Runtime>,
    pub(crate) inner: crate::gaos::resources::credentials::Credentials,
}

impl Credentials {
    pub(crate) fn new(
        runtime: std::sync::Arc<crate::blocking::Runtime>,
        inner: crate::gaos::resources::credentials::Credentials,
    ) -> Self {
        Self { runtime, inner }
    }

    /// Blocking wrapper for [`crate::gaos::resources::credentials::Credentials::list`] (Python `credentials.list`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn list(
        &self,
        params: &crate::gaos::models::ListCredentialsRequest,
    ) -> crate::errors::Result<crate::gaos::types::credentials::CredentialListResponse> {
        self.runtime.block_on(self.inner.list(params))?
    }

    /// Blocking wrapper for [`crate::gaos::resources::credentials::Credentials::create`] (Python `credentials.create`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn create(
        &self,
        body: &crate::gaos::types::credentials::CredentialCreateParams,
    ) -> crate::errors::Result<crate::gaos::types::credentials::Credential> {
        self.runtime.block_on(self.inner.create(body))?
    }

    /// Blocking wrapper for [`crate::gaos::resources::credentials::Credentials::delete`] (Python `credentials.delete`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn delete(
        &self,
        id: &str,
    ) -> crate::errors::Result<crate::gaos::types::interactions::Empty> {
        self.runtime.block_on(self.inner.delete(id))?
    }

    /// Blocking wrapper for [`crate::gaos::resources::credentials::Credentials::get`] (Python `credentials.get`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn get(
        &self,
        id: &str,
    ) -> crate::errors::Result<crate::gaos::types::credentials::Credential> {
        self.runtime.block_on(self.inner.get(id))?
    }

    /// Blocking wrapper for [`crate::gaos::resources::credentials::Credentials::update`] (Python `credentials.update`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn update(
        &self,
        id: &str,
        body: &crate::gaos::types::credentials::CredentialUpdate,
        params: &crate::gaos::models::UpdateCredentialRequest,
    ) -> crate::errors::Result<crate::gaos::types::credentials::Credential> {
        self.runtime.block_on(self.inner.update(id, body, params))?
    }
}

/// Blocking wrapper for [`crate::gaos::resources::environments::Environments`] (`client.environments()`).
pub struct Environments {
    pub(crate) runtime: std::sync::Arc<crate::blocking::Runtime>,
    pub(crate) inner: crate::gaos::resources::environments::Environments,
}

impl Environments {
    pub(crate) fn new(
        runtime: std::sync::Arc<crate::blocking::Runtime>,
        inner: crate::gaos::resources::environments::Environments,
    ) -> Self {
        Self { runtime, inner }
    }

    /// Blocking wrapper for [`crate::gaos::resources::environments::Environments::list_environments`] (Python `environments.list_environments`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn list_environments(
        &self,
        params: &crate::gaos::models::ListEnvironmentsRequest,
    ) -> crate::errors::Result<crate::gaos::types::environments::ListEnvironmentsResponse> {
        self.runtime
            .block_on(self.inner.list_environments(params))?
    }

    /// Blocking wrapper for [`crate::gaos::resources::environments::Environments::create_environment`] (Python `environments.create_environment`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn create_environment(
        &self,
        body: &crate::gaos::types::environments::CreateEnvironmentRequest,
    ) -> crate::errors::Result<crate::gaos::types::environments::Environment> {
        self.runtime.block_on(self.inner.create_environment(body))?
    }

    /// Blocking wrapper for [`crate::gaos::resources::environments::Environments::delete_environment`] (Python `environments.delete_environment`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn delete_environment(
        &self,
        id: &str,
    ) -> crate::errors::Result<crate::gaos::types::interactions::Empty> {
        self.runtime.block_on(self.inner.delete_environment(id))?
    }

    /// Blocking wrapper for [`crate::gaos::resources::environments::Environments::get_environment`] (Python `environments.get_environment`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn get_environment(
        &self,
        id: &str,
    ) -> crate::errors::Result<crate::gaos::types::environments::Environment> {
        self.runtime.block_on(self.inner.get_environment(id))?
    }

    /// Blocking wrapper for [`crate::gaos::resources::environments::Environments::files_list`] (Python `environments.files.list`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn files_list(
        &self,
        environment: &str,
        path: &str,
        params: &crate::gaos::models::GetEnvironmentFilesRequest,
    ) -> crate::errors::Result<crate::gaos::types::environments::GetEnvironmentFilesResponse> {
        self.runtime
            .block_on(self.inner.files_list(environment, path, params))?
    }
}

/// Blocking wrapper for [`crate::gaos::resources::interactions::Interactions`] (`client.interactions()`).
pub struct Interactions {
    pub(crate) runtime: std::sync::Arc<crate::blocking::Runtime>,
    pub(crate) inner: crate::gaos::resources::interactions::Interactions,
}

impl Interactions {
    pub(crate) fn new(
        runtime: std::sync::Arc<crate::blocking::Runtime>,
        inner: crate::gaos::resources::interactions::Interactions,
    ) -> Self {
        Self { runtime, inner }
    }

    /// Blocking wrapper for [`crate::gaos::resources::interactions::Interactions::create`] (Python `interactions.create`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn create(
        &self,
        body: &crate::gaos::types::interactions::CreateInteractionRequestBody,
    ) -> crate::errors::Result<crate::gaos::types::interactions::Interaction> {
        self.runtime.block_on(self.inner.create(body))?
    }

    /// Blocking wrapper for [`crate::gaos::resources::interactions::Interactions::create_stream`] (Python `interactions.create`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn create_stream(
        &self,
        body: &crate::gaos::types::interactions::CreateInteractionRequestBody,
    ) -> crate::errors::Result<
        crate::blocking::BlockingStream<crate::gaos::types::interactions::InteractionSSEEvent>,
    > {
        let stream = self.runtime.block_on(self.inner.create_stream(body))??;
        Ok(crate::blocking::BlockingStream::new(
            std::sync::Arc::clone(&self.runtime),
            stream,
        ))
    }

    /// Blocking wrapper for [`crate::gaos::resources::interactions::Interactions::delete`] (Python `interactions.delete`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn delete(&self, id: &str) -> crate::errors::Result<()> {
        self.runtime.block_on(self.inner.delete(id))?
    }

    /// Blocking wrapper for [`crate::gaos::resources::interactions::Interactions::get`] (Python `interactions.get`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn get(
        &self,
        id: &str,
        params: &crate::gaos::models::GetInteractionByIDRequest,
    ) -> crate::errors::Result<crate::gaos::types::interactions::Interaction> {
        self.runtime.block_on(self.inner.get(id, params))?
    }

    /// Blocking wrapper for [`crate::gaos::resources::interactions::Interactions::get_stream`] (Python `interactions.get`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn get_stream(
        &self,
        id: &str,
        params: &crate::gaos::models::GetInteractionByIDRequest,
    ) -> crate::errors::Result<
        crate::blocking::BlockingStream<crate::gaos::types::interactions::InteractionSSEEvent>,
    > {
        let stream = self.runtime.block_on(self.inner.get_stream(id, params))??;
        Ok(crate::blocking::BlockingStream::new(
            std::sync::Arc::clone(&self.runtime),
            stream,
        ))
    }

    /// Blocking wrapper for [`crate::gaos::resources::interactions::Interactions::cancel`] (Python `interactions.cancel`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn cancel(
        &self,
        id: &str,
    ) -> crate::errors::Result<crate::gaos::types::interactions::Interaction> {
        self.runtime.block_on(self.inner.cancel(id))?
    }
}

/// Blocking wrapper for [`crate::gaos::resources::triggers::Triggers`] (`client.triggers()`).
pub struct Triggers {
    pub(crate) runtime: std::sync::Arc<crate::blocking::Runtime>,
    pub(crate) inner: crate::gaos::resources::triggers::Triggers,
}

impl Triggers {
    pub(crate) fn new(
        runtime: std::sync::Arc<crate::blocking::Runtime>,
        inner: crate::gaos::resources::triggers::Triggers,
    ) -> Self {
        Self { runtime, inner }
    }

    /// Blocking wrapper for [`crate::gaos::resources::triggers::Triggers::list`] (Python `triggers.list`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn list(
        &self,
        params: &crate::gaos::models::ListTriggersRequest,
    ) -> crate::errors::Result<crate::gaos::types::triggers::ListTriggersResponse> {
        self.runtime.block_on(self.inner.list(params))?
    }

    /// Blocking wrapper for [`crate::gaos::resources::triggers::Triggers::create`] (Python `triggers.create`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn create(
        &self,
        body: &crate::gaos::types::triggers::TriggerCreateParams,
    ) -> crate::errors::Result<crate::gaos::types::triggers::Trigger> {
        self.runtime.block_on(self.inner.create(body))?
    }

    /// Blocking wrapper for [`crate::gaos::resources::triggers::Triggers::delete`] (Python `triggers.delete`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn delete(
        &self,
        id: &str,
    ) -> crate::errors::Result<crate::gaos::types::interactions::Empty> {
        self.runtime.block_on(self.inner.delete(id))?
    }

    /// Blocking wrapper for [`crate::gaos::resources::triggers::Triggers::get`] (Python `triggers.get`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn get(&self, id: &str) -> crate::errors::Result<crate::gaos::types::triggers::Trigger> {
        self.runtime.block_on(self.inner.get(id))?
    }

    /// Blocking wrapper for [`crate::gaos::resources::triggers::Triggers::update`] (Python `triggers.update`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn update(
        &self,
        id: &str,
        body: &crate::gaos::types::triggers::TriggerUpdate,
    ) -> crate::errors::Result<crate::gaos::types::triggers::Trigger> {
        self.runtime.block_on(self.inner.update(id, body))?
    }

    /// Blocking wrapper for [`crate::gaos::resources::triggers::Triggers::list_executions`] (Python `triggers.list_executions`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn list_executions(
        &self,
        trigger_id: &str,
        params: &crate::gaos::models::ListTriggerExecutionsRequest,
    ) -> crate::errors::Result<crate::gaos::types::triggers::ListTriggerExecutionsResponse> {
        self.runtime
            .block_on(self.inner.list_executions(trigger_id, params))?
    }

    /// Blocking wrapper for [`crate::gaos::resources::triggers::Triggers::run`] (Python `triggers.run`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn run(
        &self,
        trigger_id: &str,
    ) -> crate::errors::Result<crate::gaos::types::triggers::TriggerExecution> {
        self.runtime.block_on(self.inner.run(trigger_id))?
    }
}

/// Blocking wrapper for [`crate::gaos::resources::voices::Voices`] (`client.voices()`).
pub struct Voices {
    pub(crate) runtime: std::sync::Arc<crate::blocking::Runtime>,
    pub(crate) inner: crate::gaos::resources::voices::Voices,
}

impl Voices {
    pub(crate) fn new(
        runtime: std::sync::Arc<crate::blocking::Runtime>,
        inner: crate::gaos::resources::voices::Voices,
    ) -> Self {
        Self { runtime, inner }
    }

    /// Blocking wrapper for [`crate::gaos::resources::voices::Voices::list`] (Python `voices.list`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn list(
        &self,
        params: &crate::gaos::models::ListVoicesRequest,
    ) -> crate::errors::Result<crate::gaos::types::voices::ListVoicesResponse> {
        self.runtime.block_on(self.inner.list(params))?
    }

    /// Blocking wrapper for [`crate::gaos::resources::voices::Voices::create`] (Python `voices.create`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn create(
        &self,
        body: &crate::gaos::types::voices::CreateVoiceRequest,
    ) -> crate::errors::Result<crate::gaos::types::voices::VoiceOutput> {
        self.runtime.block_on(self.inner.create(body))?
    }

    /// Blocking wrapper for [`crate::gaos::resources::voices::Voices::delete`] (Python `voices.delete`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn delete(
        &self,
        id: &str,
    ) -> crate::errors::Result<crate::gaos::types::voices::DeleteVoiceResponse> {
        self.runtime.block_on(self.inner.delete(id))?
    }

    /// Blocking wrapper for [`crate::gaos::resources::voices::Voices::get`] (Python `voices.get`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn get(&self, id: &str) -> crate::errors::Result<crate::gaos::types::voices::VoiceOutput> {
        self.runtime.block_on(self.inner.get(id))?
    }
}

/// Blocking wrapper for [`crate::gaos::resources::webhooks::Webhooks`] (`client.webhooks()`).
pub struct Webhooks {
    pub(crate) runtime: std::sync::Arc<crate::blocking::Runtime>,
    pub(crate) inner: crate::gaos::resources::webhooks::Webhooks,
}

impl Webhooks {
    pub(crate) fn new(
        runtime: std::sync::Arc<crate::blocking::Runtime>,
        inner: crate::gaos::resources::webhooks::Webhooks,
    ) -> Self {
        Self { runtime, inner }
    }

    /// Blocking wrapper for [`crate::gaos::resources::webhooks::Webhooks::list`] (Python `webhooks.list`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn list(
        &self,
        params: &crate::gaos::models::ListWebhooksRequest,
    ) -> crate::errors::Result<crate::gaos::types::webhooks::WebhookListResponse> {
        self.runtime.block_on(self.inner.list(params))?
    }

    /// Blocking wrapper for [`crate::gaos::resources::webhooks::Webhooks::create`] (Python `webhooks.create`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn create(
        &self,
        body: &crate::gaos::types::webhooks::WebhookInput,
    ) -> crate::errors::Result<crate::gaos::types::webhooks::Webhook> {
        self.runtime.block_on(self.inner.create(body))?
    }

    /// Blocking wrapper for [`crate::gaos::resources::webhooks::Webhooks::delete`] (Python `webhooks.delete`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn delete(
        &self,
        id: &str,
    ) -> crate::errors::Result<crate::gaos::types::interactions::Empty> {
        self.runtime.block_on(self.inner.delete(id))?
    }

    /// Blocking wrapper for [`crate::gaos::resources::webhooks::Webhooks::get`] (Python `webhooks.get`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn get(&self, id: &str) -> crate::errors::Result<crate::gaos::types::webhooks::Webhook> {
        self.runtime.block_on(self.inner.get(id))?
    }

    /// Blocking wrapper for [`crate::gaos::resources::webhooks::Webhooks::update`] (Python `webhooks.update`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn update(
        &self,
        id: &str,
        body: Option<&crate::gaos::types::webhooks::WebhookUpdate>,
        params: &crate::gaos::models::UpdateWebhookRequest,
    ) -> crate::errors::Result<crate::gaos::types::webhooks::Webhook> {
        self.runtime.block_on(self.inner.update(id, body, params))?
    }

    /// Blocking wrapper for [`crate::gaos::resources::webhooks::Webhooks::ping`] (Python `webhooks.ping`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn ping(
        &self,
        id: &str,
        body: Option<&crate::gaos::types::webhooks::PingWebhookRequest>,
    ) -> crate::errors::Result<crate::gaos::types::webhooks::WebhookPingResponse> {
        self.runtime.block_on(self.inner.ping(id, body))?
    }

    /// Blocking wrapper for [`crate::gaos::resources::webhooks::Webhooks::rotate_signing_secret`] (Python `webhooks.rotate_signing_secret`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn rotate_signing_secret(
        &self,
        id: &str,
        body: Option<&crate::gaos::types::webhooks::RotateSigningSecretRequest>,
    ) -> crate::errors::Result<crate::gaos::types::webhooks::WebhookRotateSigningSecretResponse>
    {
        self.runtime
            .block_on(self.inner.rotate_signing_secret(id, body))?
    }
}
