// @generated by tools/codegen/gen_blocking.py from methods.toml. DO NOT EDIT.
// Edit tools/codegen/gen_blocking.py (or tools/codegen/methods.toml) and
// re-run `python tools/codegen/generate.py --only blocking` instead.
//! Blocking (`feature = "blocking"`) wrappers for every `Client`-accessor
//! module's async methods, generated from `tools/codegen/methods.toml`
//! against google-genai 2.19.0's method inventory. `Chat` (returned by
//! `Chats::create`), `Operations::get<T>`, and `FileSearchStores::documents()`
//! are hand-written in `src/blocking/mod.rs` instead -- see that file and
//! `methods.toml`'s header comment.

#![allow(
    clippy::pedantic,
    dead_code,
    reason = "mechanically generated 1:1 blocking wrappers around this crate's own async API; pedantic-tier style lints don't apply, and not every wrapper method is necessarily exercised by every feature combination"
)]

/// Blocking wrapper for [`crate::models::Models`] (`client.models()`).
pub struct Models {
    pub(crate) runtime: std::sync::Arc<crate::blocking::Runtime>,
    pub(crate) inner: crate::models::Models,
}

impl Models {
    pub(crate) fn new(
        runtime: std::sync::Arc<crate::blocking::Runtime>,
        inner: crate::models::Models,
    ) -> Self {
        Self { runtime, inner }
    }

    /// Blocking wrapper for [`crate::models::Models::generate_content`] (Python `models.generate_content`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn generate_content(
        &self,
        model: &str,
        contents: impl Into<crate::types::Contents>,
        config: Option<crate::types::GenerateContentConfig>,
    ) -> crate::error::Result<crate::types::GenerateContentResponse> {
        self.runtime
            .block_on(self.inner.generate_content(model, contents, config))?
    }

    /// Blocking wrapper for [`crate::models::Models::generate_content_stream`] (Python `models.generate_content_stream`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn generate_content_stream(
        &self,
        model: &str,
        contents: impl Into<crate::types::Contents>,
        config: Option<crate::types::GenerateContentConfig>,
    ) -> crate::error::Result<crate::blocking::BlockingStream<crate::types::GenerateContentResponse>>
    {
        let stream = self
            .runtime
            .block_on(self.inner.generate_content_stream(model, contents, config))??;
        Ok(crate::blocking::BlockingStream::new(
            std::sync::Arc::clone(&self.runtime),
            stream,
        ))
    }

    /// Blocking wrapper for [`crate::models::Models::embed_content`] (Python `models.embed_content`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn embed_content(
        &self,
        model: &str,
        contents: impl Into<crate::types::Contents>,
        config: Option<crate::types::EmbedContentConfig>,
    ) -> crate::error::Result<crate::types::EmbedContentResponse> {
        self.runtime
            .block_on(self.inner.embed_content(model, contents, config))?
    }

    /// Blocking wrapper for [`crate::models::Models::count_tokens`] (Python `models.count_tokens`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn count_tokens(
        &self,
        model: &str,
        contents: impl Into<crate::types::Contents>,
        config: Option<crate::types::CountTokensConfig>,
    ) -> crate::error::Result<crate::types::CountTokensResponse> {
        self.runtime
            .block_on(self.inner.count_tokens(model, contents, config))?
    }

    /// Blocking wrapper for [`crate::models::Models::compute_tokens`] (Python `models.compute_tokens`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn compute_tokens(
        &self,
        model: &str,
        contents: impl Into<crate::types::Contents>,
        config: Option<serde_json::Value>,
    ) -> crate::error::Result<crate::types::ComputeTokensResponse> {
        self.runtime
            .block_on(self.inner.compute_tokens(model, contents, config))?
    }

    /// Blocking wrapper for [`crate::models::Models::get`] (Python `models.get`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn get(
        &self,
        model: &str,
        config: Option<crate::types::GetModelConfig>,
    ) -> crate::error::Result<crate::types::Model> {
        self.runtime.block_on(self.inner.get(model, config))?
    }

    /// Blocking wrapper for [`crate::models::Models::list`] (Python `models.list`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn list(
        &self,
        config: Option<crate::types::ListModelsConfig>,
    ) -> crate::error::Result<crate::blocking::Pager<crate::types::Model>> {
        let pager = self.runtime.block_on(self.inner.list(config))??;
        Ok(crate::blocking::Pager::new(
            std::sync::Arc::clone(&self.runtime),
            pager,
        ))
    }

    /// Blocking wrapper for [`crate::models::Models::update`] (Python `models.update`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn update(
        &self,
        model: &str,
        config: crate::types::UpdateModelConfig,
    ) -> crate::error::Result<crate::types::Model> {
        self.runtime.block_on(self.inner.update(model, config))?
    }

    /// Blocking wrapper for [`crate::models::Models::delete`] (Python `models.delete`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn delete(
        &self,
        model: &str,
        config: Option<crate::types::DeleteModelConfig>,
    ) -> crate::error::Result<crate::types::DeleteModelResponse> {
        self.runtime.block_on(self.inner.delete(model, config))?
    }

    /// Blocking wrapper for [`crate::models::Models::generate_images`] (Python `models.generate_images`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    #[expect(
        deprecated,
        reason = "parity wrapper around the deprecated async method"
    )]
    pub fn generate_images(
        &self,
        model: &str,
        prompt: &str,
        config: Option<crate::types::GenerateImagesConfig>,
    ) -> crate::error::Result<crate::types::GenerateImagesResponse> {
        self.runtime
            .block_on(self.inner.generate_images(model, prompt, config))?
    }

    /// Blocking wrapper for [`crate::models::Models::generate_videos`] (Python `models.generate_videos`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn generate_videos(
        &self,
        model: &str,
        source: crate::types::GenerateVideosSource,
        config: Option<crate::types::GenerateVideosConfig>,
    ) -> crate::error::Result<crate::types::GenerateVideosOperation> {
        self.runtime
            .block_on(self.inner.generate_videos(model, source, config))?
    }
}

/// Blocking wrapper for [`crate::chats::Chats`] (`client.chats()`).
pub struct Chats {
    pub(crate) runtime: std::sync::Arc<crate::blocking::Runtime>,
    pub(crate) inner: crate::chats::Chats,
}

impl Chats {
    pub(crate) fn new(
        runtime: std::sync::Arc<crate::blocking::Runtime>,
        inner: crate::chats::Chats,
    ) -> Self {
        Self { runtime, inner }
    }
}

/// Blocking wrapper for [`crate::files::Files`] (`client.files()`).
pub struct Files {
    pub(crate) runtime: std::sync::Arc<crate::blocking::Runtime>,
    pub(crate) inner: crate::files::Files,
}

impl Files {
    pub(crate) fn new(
        runtime: std::sync::Arc<crate::blocking::Runtime>,
        inner: crate::files::Files,
    ) -> Self {
        Self { runtime, inner }
    }

    /// Blocking wrapper for [`crate::files::Files::upload`] (Python `files.upload`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn upload(
        &self,
        source: impl Into<crate::files::UploadSource>,
        config: Option<crate::types::UploadFileConfig>,
    ) -> crate::error::Result<crate::types::File> {
        self.runtime.block_on(self.inner.upload(source, config))?
    }

    /// Blocking wrapper for [`crate::files::Files::get`] (Python `files.get`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn get(
        &self,
        name: &str,
        config: Option<crate::types::GetFileConfig>,
    ) -> crate::error::Result<crate::types::File> {
        self.runtime.block_on(self.inner.get(name, config))?
    }

    /// Blocking wrapper for [`crate::files::Files::list`] (Python `files.list`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn list(
        &self,
        config: Option<crate::types::ListFilesConfig>,
    ) -> crate::error::Result<crate::blocking::Pager<crate::types::File>> {
        let pager = self.runtime.block_on(self.inner.list(config))??;
        Ok(crate::blocking::Pager::new(
            std::sync::Arc::clone(&self.runtime),
            pager,
        ))
    }

    /// Blocking wrapper for [`crate::files::Files::delete`] (Python `files.delete`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn delete(
        &self,
        name: &str,
        config: Option<crate::types::DeleteFileConfig>,
    ) -> crate::error::Result<crate::types::DeleteFileResponse> {
        self.runtime.block_on(self.inner.delete(name, config))?
    }

    /// Blocking wrapper for [`crate::files::Files::download`] (Python `files.download`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn download(
        &self,
        file: &str,
        config: Option<crate::types::DownloadFileConfig>,
    ) -> crate::error::Result<bytes::Bytes> {
        self.runtime.block_on(self.inner.download(file, config))?
    }

    /// Blocking wrapper for [`crate::files::Files::register_files`] (Python `files._register_files`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn register_files(
        &self,
        uris: Vec<String>,
        config: Option<crate::types::RegisterFilesConfig>,
    ) -> crate::error::Result<crate::types::RegisterFilesResponse> {
        self.runtime
            .block_on(self.inner.register_files(uris, config))?
    }
}

/// Blocking wrapper for [`crate::caches::Caches`] (`client.caches()`).
pub struct Caches {
    pub(crate) runtime: std::sync::Arc<crate::blocking::Runtime>,
    pub(crate) inner: crate::caches::Caches,
}

impl Caches {
    pub(crate) fn new(
        runtime: std::sync::Arc<crate::blocking::Runtime>,
        inner: crate::caches::Caches,
    ) -> Self {
        Self { runtime, inner }
    }

    /// Blocking wrapper for [`crate::caches::Caches::create`] (Python `caches.create`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn create(
        &self,
        model: &str,
        config: Option<crate::types::CreateCachedContentConfig>,
    ) -> crate::error::Result<crate::types::CachedContent> {
        self.runtime.block_on(self.inner.create(model, config))?
    }

    /// Blocking wrapper for [`crate::caches::Caches::get`] (Python `caches.get`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn get(
        &self,
        name: &str,
        config: Option<crate::types::GetCachedContentConfig>,
    ) -> crate::error::Result<crate::types::CachedContent> {
        self.runtime.block_on(self.inner.get(name, config))?
    }

    /// Blocking wrapper for [`crate::caches::Caches::list`] (Python `caches.list`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn list(
        &self,
        config: Option<crate::types::ListCachedContentsConfig>,
    ) -> crate::error::Result<crate::blocking::Pager<crate::types::CachedContent>> {
        let pager = self.runtime.block_on(self.inner.list(config))??;
        Ok(crate::blocking::Pager::new(
            std::sync::Arc::clone(&self.runtime),
            pager,
        ))
    }

    /// Blocking wrapper for [`crate::caches::Caches::update`] (Python `caches.update`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn update(
        &self,
        name: &str,
        config: Option<crate::types::UpdateCachedContentConfig>,
    ) -> crate::error::Result<crate::types::CachedContent> {
        self.runtime.block_on(self.inner.update(name, config))?
    }

    /// Blocking wrapper for [`crate::caches::Caches::delete`] (Python `caches.delete`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn delete(
        &self,
        name: &str,
        config: Option<crate::types::DeleteCachedContentConfig>,
    ) -> crate::error::Result<crate::types::DeleteCachedContentResponse> {
        self.runtime.block_on(self.inner.delete(name, config))?
    }
}

/// Blocking wrapper for [`crate::tunings::Tunings`] (`client.tunings()`).
pub struct Tunings {
    pub(crate) runtime: std::sync::Arc<crate::blocking::Runtime>,
    pub(crate) inner: crate::tunings::Tunings,
}

impl Tunings {
    pub(crate) fn new(
        runtime: std::sync::Arc<crate::blocking::Runtime>,
        inner: crate::tunings::Tunings,
    ) -> Self {
        Self { runtime, inner }
    }

    /// Blocking wrapper for [`crate::tunings::Tunings::tune`] (Python `tunings.tune`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn tune(
        &self,
        base_model: &str,
        training_dataset: crate::types::TuningDataset,
        config: Option<crate::types::CreateTuningJobConfig>,
    ) -> crate::error::Result<crate::types::TuningJob> {
        self.runtime
            .block_on(self.inner.tune(base_model, training_dataset, config))?
    }

    /// Blocking wrapper for [`crate::tunings::Tunings::get`] (Python `tunings.get`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn get(
        &self,
        name: &str,
        config: Option<crate::types::GetTuningJobConfig>,
    ) -> crate::error::Result<crate::types::TuningJob> {
        self.runtime.block_on(self.inner.get(name, config))?
    }

    /// Blocking wrapper for [`crate::tunings::Tunings::list`] (Python `tunings.list`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn list(
        &self,
        config: Option<crate::types::ListTuningJobsConfig>,
    ) -> crate::error::Result<crate::blocking::Pager<crate::types::TuningJob>> {
        let pager = self.runtime.block_on(self.inner.list(config))??;
        Ok(crate::blocking::Pager::new(
            std::sync::Arc::clone(&self.runtime),
            pager,
        ))
    }

    /// Blocking wrapper for [`crate::tunings::Tunings::cancel`] (Python `tunings.cancel`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn cancel(
        &self,
        name: &str,
        config: Option<crate::types::CancelTuningJobConfig>,
    ) -> crate::error::Result<crate::types::CancelTuningJobResponse> {
        self.runtime.block_on(self.inner.cancel(name, config))?
    }
}

/// Blocking wrapper for [`crate::batches::Batches`] (`client.batches()`).
pub struct Batches {
    pub(crate) runtime: std::sync::Arc<crate::blocking::Runtime>,
    pub(crate) inner: crate::batches::Batches,
}

impl Batches {
    pub(crate) fn new(
        runtime: std::sync::Arc<crate::blocking::Runtime>,
        inner: crate::batches::Batches,
    ) -> Self {
        Self { runtime, inner }
    }

    /// Blocking wrapper for [`crate::batches::Batches::create`] (Python `batches.create`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn create(
        &self,
        model: &str,
        src: impl Into<crate::types::BatchJobSource>,
        config: Option<crate::types::CreateBatchJobConfig>,
    ) -> crate::error::Result<crate::types::BatchJob> {
        self.runtime
            .block_on(self.inner.create(model, src, config))?
    }

    /// Blocking wrapper for [`crate::batches::Batches::create_embeddings`] (Python `batches.create_embeddings`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn create_embeddings(
        &self,
        model: &str,
        src: crate::types::EmbeddingsBatchJobSource,
        config: Option<crate::types::CreateEmbeddingsBatchJobConfig>,
    ) -> crate::error::Result<crate::types::BatchJob> {
        self.runtime
            .block_on(self.inner.create_embeddings(model, src, config))?
    }

    /// Blocking wrapper for [`crate::batches::Batches::get`] (Python `batches.get`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn get(
        &self,
        name: &str,
        config: Option<crate::types::GetBatchJobConfig>,
    ) -> crate::error::Result<crate::types::BatchJob> {
        self.runtime.block_on(self.inner.get(name, config))?
    }

    /// Blocking wrapper for [`crate::batches::Batches::cancel`] (Python `batches.cancel`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn cancel(
        &self,
        name: &str,
        config: Option<crate::types::CancelBatchJobConfig>,
    ) -> crate::error::Result<()> {
        self.runtime.block_on(self.inner.cancel(name, config))?
    }

    /// Blocking wrapper for [`crate::batches::Batches::delete`] (Python `batches.delete`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn delete(
        &self,
        name: &str,
        config: Option<crate::types::DeleteBatchJobConfig>,
    ) -> crate::error::Result<crate::types::DeleteResourceJob> {
        self.runtime.block_on(self.inner.delete(name, config))?
    }

    /// Blocking wrapper for [`crate::batches::Batches::list`] (Python `batches.list`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn list(
        &self,
        config: Option<crate::types::ListBatchJobsConfig>,
    ) -> crate::error::Result<crate::blocking::Pager<crate::types::BatchJob>> {
        let pager = self.runtime.block_on(self.inner.list(config))??;
        Ok(crate::blocking::Pager::new(
            std::sync::Arc::clone(&self.runtime),
            pager,
        ))
    }
}

/// Blocking wrapper for [`crate::operations::Operations`] (`client.operations()`).
pub struct Operations {
    pub(crate) runtime: std::sync::Arc<crate::blocking::Runtime>,
    pub(crate) inner: crate::operations::Operations,
}

impl Operations {
    pub(crate) fn new(
        runtime: std::sync::Arc<crate::blocking::Runtime>,
        inner: crate::operations::Operations,
    ) -> Self {
        Self { runtime, inner }
    }
}

/// Blocking wrapper for [`crate::file_search_stores::FileSearchStores`] (`client.file_search_stores()`).
pub struct FileSearchStores {
    pub(crate) runtime: std::sync::Arc<crate::blocking::Runtime>,
    pub(crate) inner: crate::file_search_stores::FileSearchStores,
}

impl FileSearchStores {
    pub(crate) fn new(
        runtime: std::sync::Arc<crate::blocking::Runtime>,
        inner: crate::file_search_stores::FileSearchStores,
    ) -> Self {
        Self { runtime, inner }
    }

    /// Blocking wrapper for [`crate::file_search_stores::FileSearchStores::create`] (Python `file_search_stores.create`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn create(
        &self,
        config: Option<crate::types::CreateFileSearchStoreConfig>,
    ) -> crate::error::Result<crate::types::FileSearchStore> {
        self.runtime.block_on(self.inner.create(config))?
    }

    /// Blocking wrapper for [`crate::file_search_stores::FileSearchStores::get`] (Python `file_search_stores.get`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn get(
        &self,
        name: &str,
        config: Option<crate::types::GetFileSearchStoreConfig>,
    ) -> crate::error::Result<crate::types::FileSearchStore> {
        self.runtime.block_on(self.inner.get(name, config))?
    }

    /// Blocking wrapper for [`crate::file_search_stores::FileSearchStores::delete`] (Python `file_search_stores.delete`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn delete(
        &self,
        name: &str,
        config: Option<crate::types::DeleteFileSearchStoreConfig>,
    ) -> crate::error::Result<()> {
        self.runtime.block_on(self.inner.delete(name, config))?
    }

    /// Blocking wrapper for [`crate::file_search_stores::FileSearchStores::list`] (Python `file_search_stores.list`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn list(
        &self,
        config: Option<crate::types::ListFileSearchStoresConfig>,
    ) -> crate::error::Result<crate::blocking::Pager<crate::types::FileSearchStore>> {
        let pager = self.runtime.block_on(self.inner.list(config))??;
        Ok(crate::blocking::Pager::new(
            std::sync::Arc::clone(&self.runtime),
            pager,
        ))
    }

    /// Blocking wrapper for [`crate::file_search_stores::FileSearchStores::import_file`] (Python `file_search_stores.import_file`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn import_file(
        &self,
        file_search_store_name: &str,
        file_name: &str,
        config: Option<crate::types::ImportFileConfig>,
    ) -> crate::error::Result<crate::types::ImportFileOperation> {
        self.runtime.block_on(
            self.inner
                .import_file(file_search_store_name, file_name, config),
        )?
    }

    /// Blocking wrapper for [`crate::file_search_stores::FileSearchStores::upload_to_file_search_store`] (Python `file_search_stores.upload_to_file_search_store`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn upload_to_file_search_store(
        &self,
        file_search_store_name: &str,
        data: &[u8],
        mime_type: &str,
        config: Option<crate::types::UploadToFileSearchStoreConfig>,
    ) -> crate::error::Result<crate::types::UploadToFileSearchStoreOperation> {
        self.runtime
            .block_on(self.inner.upload_to_file_search_store(
                file_search_store_name,
                data,
                mime_type,
                config,
            ))?
    }

    /// Blocking wrapper for [`crate::file_search_stores::FileSearchStores::download_media`] (Python `file_search_stores.download_media`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn download_media(
        &self,
        media_id: &str,
        config: Option<crate::types::DownloadMediaConfig>,
    ) -> crate::error::Result<bytes::Bytes> {
        self.runtime
            .block_on(self.inner.download_media(media_id, config))?
    }
}

/// Blocking wrapper for [`crate::documents::Documents`] (`client.documents()`).
pub struct Documents {
    pub(crate) runtime: std::sync::Arc<crate::blocking::Runtime>,
    pub(crate) inner: crate::documents::Documents,
}

impl Documents {
    pub(crate) fn new(
        runtime: std::sync::Arc<crate::blocking::Runtime>,
        inner: crate::documents::Documents,
    ) -> Self {
        Self { runtime, inner }
    }

    /// Blocking wrapper for [`crate::documents::Documents::get`] (Python `documents.get`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn get(
        &self,
        name: &str,
        config: Option<crate::types::GetDocumentConfig>,
    ) -> crate::error::Result<crate::types::Document> {
        self.runtime.block_on(self.inner.get(name, config))?
    }

    /// Blocking wrapper for [`crate::documents::Documents::delete`] (Python `documents.delete`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn delete(
        &self,
        name: &str,
        config: Option<crate::types::DeleteDocumentConfig>,
    ) -> crate::error::Result<()> {
        self.runtime.block_on(self.inner.delete(name, config))?
    }

    /// Blocking wrapper for [`crate::documents::Documents::list`] (Python `documents.list`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn list(
        &self,
        parent: &str,
        config: Option<crate::types::ListDocumentsConfig>,
    ) -> crate::error::Result<crate::blocking::Pager<crate::types::Document>> {
        let pager = self.runtime.block_on(self.inner.list(parent, config))??;
        Ok(crate::blocking::Pager::new(
            std::sync::Arc::clone(&self.runtime),
            pager,
        ))
    }
}

/// Blocking wrapper for [`crate::auth_tokens::AuthTokens`] (`client.auth_tokens()`).
pub struct AuthTokens {
    pub(crate) runtime: std::sync::Arc<crate::blocking::Runtime>,
    pub(crate) inner: crate::auth_tokens::AuthTokens,
}

impl AuthTokens {
    pub(crate) fn new(
        runtime: std::sync::Arc<crate::blocking::Runtime>,
        inner: crate::auth_tokens::AuthTokens,
    ) -> Self {
        Self { runtime, inner }
    }

    /// Blocking wrapper for [`crate::auth_tokens::AuthTokens::create`] (Python `tokens.create`).
    ///
    /// # Errors
    /// See the async method, plus [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn create(
        &self,
        config: Option<crate::types::CreateAuthTokenConfig>,
    ) -> crate::error::Result<crate::types::AuthToken> {
        self.runtime.block_on(self.inner.create(config))?
    }
}
