//! The synchronous (`fn`, not `async fn`) wrapper around this crate's async
//! API (`feature = "blocking"`). Mirrors the Python SDK's default
//! (synchronous) surface for callers who don't want to bring their own
//! Tokio runtime.
//!
//! [`blocking::Client`](Client) provides the same module accessors as
//! [`crate::Client`] (`models()`, `chats()`, `files()`, ...) except
//! `live()`: the Live API is inherently asynchronous (bidirectional
//! streaming) in the Python SDK too, so there is no blocking equivalent.
//! Every accessor returns a thin wrapper -- mostly generated by
//! `tools/codegen/gen_blocking.py` from `tools/codegen/methods.toml` into
//! `generated` -- that shares one dedicated single-threaded Tokio runtime
//! ([`Runtime`]) per [`Client`].
//!
//! ```no_run
//! # fn run() -> google_genai::Result<()> {
//! use google_genai::blocking::Client;
//!
//! let client = Client::new()?;
//! let response = client
//!     .models()
//!     .generate_content("gemini-2.5-flash", "Why is the sky blue?", None)?;
//! println!("{}", response.text().unwrap_or_default());
//! # Ok(())
//! # }
//! ```
//!
//! # Design
//!
//! Each [`Client`] owns a [`tokio::runtime::Runtime`] built with
//! [`Builder::new_current_thread`](tokio::runtime::Builder::new_current_thread):
//! no background worker threads, no extra OS threads at all -- every
//! blocking call runs the async call graph to completion on the *calling*
//! thread via [`tokio::runtime::Runtime::block_on`]. That call panics if
//! invoked reentrantly (from a thread that is already inside another
//! Tokio runtime's `block_on`), so `Runtime::block_on` first checks
//! [`tokio::runtime::Handle::try_current`] and returns
//! [`crate::Error::BlockingInsideRuntime`] instead of risking that panic --
//! e.g. calling `blocking::Client` from within `#[tokio::main]` or a
//! `#[tokio::test]`. [`Client::new`]/[`ClientBuilder::build`] apply the
//! same check when building a [`Client`]'s [`Runtime`], for a related but
//! distinct reason: a `tokio::runtime::Runtime` may not be *dropped* from
//! inside an async context either, so a [`Client`] built there would
//! panic later, whenever it happened to go out of scope, rather than
//! failing fast at the actual mistake.
//!
//! Streams (`Stream<Item = Result<T>>`) become [`BlockingStream<T>`], an
//! [`Iterator<Item = Result<T>>`]; pagers ([`crate::pager::Pager<T>`])
//! become [`Pager<T>`]. Both hold the same `Arc<Runtime>` as the [`Client`]
//! they were created from, so they keep working after the [`Client`] that
//! produced them is dropped.
//!
//! ## Interface with the generated wrappers
//!
//! `generated` defines one struct per [`crate::Client`] accessor
//! (`Models`, `Chats`, `Files`, ...), each with a `pub(crate) runtime:
//! Arc<Runtime>` and `pub(crate) inner: crate::<module>::<Type>` field and
//! a `pub(crate) fn new(runtime, inner)` constructor -- see
//! `tools/codegen/methods.toml`'s header comment for exactly which methods
//! it generates onto those structs versus which are hand-written here:
//!
//! - [`Chats::create`](generated::Chats) returns a [`Chat`] (this module),
//!   since `crate::chats::Chat` is a stateful type returned *by value*,
//!   not a `Client` accessor -- it has no `generated` struct of its own.
//! - [`Operations::get`](generated::Operations) is generic over `T:
//!   OperationLike + Serialize + DeserializeOwned`, a shape
//!   `tools/codegen/gen_blocking.py`'s `"name: type"` string format can't
//!   express.
//! - [`FileSearchStores::documents`](generated::FileSearchStores) is a
//!   nested-handle accessor (mirroring `Client::file_search_stores()`
//!   itself), not an API call.

use std::future::Future;
use std::sync::Arc;

use futures_util::StreamExt;

use crate::error::{Error, Result};

mod generated;

pub use generated::{
    AuthTokens, Batches, Caches, Chats, Documents, FileSearchStores, Files, Models, Operations,
    Tunings,
};

/// A dedicated single-threaded Tokio runtime backing one [`Client`] (and
/// everything constructed from it -- [`BlockingStream`], [`Pager`]).
/// Not constructible or nameable outside this crate; see the module docs
/// for why `block_on` is guarded rather than a bare
/// [`tokio::runtime::Runtime::block_on`] call.
pub struct Runtime(tokio::runtime::Runtime);

impl Runtime {
    /// Builds a fresh runtime, unless the calling thread is already
    /// inside a running Tokio runtime.
    ///
    /// This rejects construction (not just [`Self::block_on`]) from
    /// inside a running runtime for a second, independent reason beyond
    /// avoiding `block_on`'s reentrancy panic: a `tokio::runtime::Runtime`
    /// may not be *dropped* from inside an async context either (worker
    /// threads disallow the blocking shutdown that requires), so a
    /// [`Client`] built inside one would panic later, whenever it (and
    /// this `Runtime`) happened to go out of scope -- possibly long after,
    /// and far away from, the mistake of constructing it there. Rejecting
    /// construction up front turns that latent panic into an immediate,
    /// recoverable [`Error::BlockingInsideRuntime`].
    fn new() -> Result<Self> {
        if tokio::runtime::Handle::try_current().is_ok() {
            return Err(Error::BlockingInsideRuntime);
        }
        Ok(Self(
            tokio::runtime::Builder::new_current_thread()
                .enable_all()
                .build()?,
        ))
    }

    /// Runs `fut` to completion on this runtime and returns its output,
    /// unless the calling thread is already inside a running Tokio
    /// runtime -- which would make the underlying
    /// [`tokio::runtime::Runtime::block_on`] panic -- in which case this
    /// returns [`Error::BlockingInsideRuntime`] instead.
    pub(crate) fn block_on<F: Future>(&self, fut: F) -> Result<F::Output> {
        if tokio::runtime::Handle::try_current().is_ok() {
            return Err(Error::BlockingInsideRuntime);
        }
        Ok(self.0.block_on(fut))
    }
}

/// The blocking entry point (`feature = "blocking"`): same module
/// accessors as [`crate::Client`] (`models()`, `chats()`, ...), minus
/// `live()`. See the [module docs](self) for the runtime/threading model.
///
/// Cheap to clone: internally reference-counted, like [`crate::Client`].
#[derive(Clone)]
pub struct Client {
    runtime: Arc<Runtime>,
    inner: crate::Client,
}

impl std::fmt::Debug for Client {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        // `Runtime` wraps `tokio::runtime::Runtime`, which has no `Debug`
        // impl, so it's omitted here rather than propagating a `Debug`
        // bound this crate doesn't otherwise need.
        f.debug_struct("Client")
            .field("inner", &self.inner)
            .finish_non_exhaustive()
    }
}

impl Client {
    /// Builds a [`Client`] using the Gemini Developer API and an API key
    /// resolved from the environment. See [`crate::Client::new`].
    ///
    /// # Errors
    /// See [`crate::Client::new`], plus any error building this client's
    /// dedicated Tokio runtime (an OS resource-exhaustion failure, in
    /// practice).
    pub fn new() -> Result<Self> {
        Self::builder().build()
    }

    /// Starts building a [`Client`] with explicit configuration. See
    /// [`crate::Client::builder`].
    #[must_use]
    pub fn builder() -> ClientBuilder {
        ClientBuilder::default()
    }

    /// Text/image generation, embeddings, token counting, and model
    /// listing (`client.models()...`).
    #[must_use]
    pub fn models(&self) -> Models {
        Models::new(Arc::clone(&self.runtime), self.inner.models())
    }

    /// Multi-turn chat sessions (`client.chats().create(...)`).
    #[must_use]
    pub fn chats(&self) -> Chats {
        Chats::new(Arc::clone(&self.runtime), self.inner.chats())
    }

    /// File upload/get/list/delete/download (`client.files()...`).
    #[must_use]
    pub fn files(&self) -> Files {
        Files::new(Arc::clone(&self.runtime), self.inner.files())
    }

    /// Context cache create/get/list/update/delete
    /// (`client.caches()...`).
    #[must_use]
    pub fn caches(&self) -> Caches {
        Caches::new(Arc::clone(&self.runtime), self.inner.caches())
    }

    /// Fine-tuning job create/get/list/cancel (`client.tunings()...`).
    #[must_use]
    pub fn tunings(&self) -> Tunings {
        Tunings::new(Arc::clone(&self.runtime), self.inner.tunings())
    }

    /// Batch job create/get/list/cancel/delete (`client.batches()...`).
    #[must_use]
    pub fn batches(&self) -> Batches {
        Batches::new(Arc::clone(&self.runtime), self.inner.batches())
    }

    /// Long-running operation polling (`client.operations()...`).
    #[must_use]
    pub fn operations(&self) -> Operations {
        Operations::new(Arc::clone(&self.runtime), self.inner.operations())
    }

    /// File Search store create/get/list/delete/import
    /// (`client.file_search_stores()...`).
    #[must_use]
    pub fn file_search_stores(&self) -> FileSearchStores {
        FileSearchStores::new(Arc::clone(&self.runtime), self.inner.file_search_stores())
    }

    /// Ephemeral auth token creation for the Live API
    /// (`client.auth_tokens()...`).
    #[must_use]
    pub fn auth_tokens(&self) -> AuthTokens {
        AuthTokens::new(Arc::clone(&self.runtime), self.inner.auth_tokens())
    }
}

/// Builder for [`Client`]. See [`Client::builder`] and
/// [`crate::ClientBuilder`].
pub struct ClientBuilder(crate::ClientBuilder);

impl Default for ClientBuilder {
    fn default() -> Self {
        Self(crate::Client::builder())
    }
}

impl ClientBuilder {
    /// Sets the Gemini Developer API key explicitly, overriding the
    /// environment variables. See
    /// [`crate::client::ClientBuilder::api_key`].
    #[must_use]
    pub fn api_key(mut self, api_key: impl Into<String>) -> Self {
        self.0 = self.0.api_key(api_key);
        self
    }

    /// Sets the client-level [`crate::types::HttpOptions`]. See
    /// [`crate::client::ClientBuilder::http_options`].
    #[must_use]
    pub fn http_options(mut self, http_options: crate::types::HttpOptions) -> Self {
        self.0 = self.0.http_options(http_options);
        self
    }

    /// Requests the Vertex AI backend. **Not yet implemented**: `build()`
    /// returns [`Error::UnsupportedBackend`] when this is `true`.
    #[must_use]
    pub fn vertexai(mut self, vertexai: bool) -> Self {
        self.0 = self.0.vertexai(vertexai);
        self
    }

    /// Sets the Google Cloud project for the (not yet implemented) Vertex
    /// AI backend.
    #[must_use]
    pub fn project(mut self, project: impl Into<String>) -> Self {
        self.0 = self.0.project(project);
        self
    }

    /// Sets the Google Cloud region for the (not yet implemented) Vertex
    /// AI backend.
    #[must_use]
    pub fn location(mut self, location: impl Into<String>) -> Self {
        self.0 = self.0.location(location);
        self
    }

    /// Resolves configuration and builds the [`Client`], including its
    /// dedicated Tokio runtime.
    ///
    /// # Errors
    /// See [`crate::Client::new`], plus any error building this client's
    /// dedicated Tokio runtime.
    pub fn build(self) -> Result<Client> {
        Ok(Client {
            runtime: Arc::new(Runtime::new()?),
            inner: self.0.build()?,
        })
    }
}

/// A blocking [`Iterator`] over the items of an async
/// `Stream<Item = Result<T>>`, driven by the [`Runtime`] it was created
/// from. Returned by every `generate_content_stream`/`send_message_stream`
/// wrapper.
///
/// A mid-stream failure yields one `Some(Err(_))` item and then ends the
/// iterator, exactly like the underlying async stream. Calling
/// [`Iterator::next`] from inside an already-running Tokio runtime yields
/// `Some(Err(Error::BlockingInsideRuntime))` instead of blocking (or
/// panicking); the iterator does not automatically stop afterwards, since
/// that error reflects the *caller's* execution context, not the
/// stream's state -- a caller that fixes its context (e.g. moves the
/// blocking client to a non-async thread) can keep polling.
pub struct BlockingStream<T> {
    runtime: Arc<Runtime>,
    inner: std::pin::Pin<Box<dyn futures_core::Stream<Item = Result<T>>>>,
}

impl<T> BlockingStream<T> {
    pub(crate) fn new<S>(runtime: Arc<Runtime>, inner: S) -> Self
    where
        S: futures_core::Stream<Item = Result<T>> + 'static,
    {
        Self {
            runtime,
            inner: Box::pin(inner),
        }
    }
}

impl<T> Iterator for BlockingStream<T> {
    type Item = Result<T>;

    fn next(&mut self) -> Option<Result<T>> {
        match self.runtime.block_on(self.inner.next()) {
            Ok(item) => item,
            Err(err) => Some(Err(err)),
        }
    }
}

/// A blocking wrapper around [`crate::pager::Pager<T>`]: [`next_page`] /
/// [`page`] / [`page_size`] / [`config`] / [`name`] mirror the async
/// pager's methods synchronously, and [`into_stream`] returns a
/// [`BlockingStream<T>`] walking every item across every page. Returned by
/// every `list(...)` wrapper.
///
/// [`next_page`]: Pager::next_page
/// [`page`]: Pager::page
/// [`page_size`]: Pager::page_size
/// [`config`]: Pager::config
/// [`name`]: Pager::name
/// [`into_stream`]: Pager::into_stream
pub struct Pager<T> {
    runtime: Arc<Runtime>,
    inner: crate::pager::Pager<T>,
}

impl<T: std::fmt::Debug> std::fmt::Debug for Pager<T> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("Pager")
            .field("inner", &self.inner)
            .finish_non_exhaustive()
    }
}

impl<T> Pager<T> {
    pub(crate) fn new(runtime: Arc<Runtime>, inner: crate::pager::Pager<T>) -> Self {
        Self { runtime, inner }
    }

    /// Which resource kind this pager lists. See
    /// [`crate::pager::Pager::name`].
    #[must_use]
    pub fn name(&self) -> crate::pager::PagedItem {
        self.inner.name()
    }

    /// The current page's items. See [`crate::pager::Pager::page`].
    #[must_use]
    pub fn page(&self) -> &[T] {
        self.inner.page()
    }

    /// The current page's size. See [`crate::pager::Pager::page_size`].
    #[must_use]
    pub fn page_size(&self) -> usize {
        self.inner.page_size()
    }

    /// The request config used to fetch the current page. See
    /// [`crate::pager::Pager::config`].
    #[must_use]
    pub fn config(&self) -> &serde_json::Map<String, serde_json::Value> {
        self.inner.config()
    }

    /// Fetches and returns the next page, replacing the current one. See
    /// [`crate::pager::Pager::next_page`].
    ///
    /// # Errors
    /// Returns [`crate::Error::NoMorePages`] if there
    /// is no further page, or
    /// [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn next_page(&mut self) -> Result<&[T]> {
        self.runtime.block_on(self.inner.next_page())?
    }

    /// Consumes this pager, returning a [`BlockingStream`] of every item
    /// across every page (including the current one). See
    /// [`crate::pager::Pager::into_stream`].
    #[must_use = "returns a lazy iterator; nothing is fetched until it is iterated"]
    pub fn into_stream(self) -> BlockingStream<T>
    where
        T: Send + 'static,
    {
        BlockingStream::new(Arc::clone(&self.runtime), self.inner.into_stream())
    }
}

/// A blocking wrapper around a [`crate::chats::Chat`] session, returned by
/// [`generated::Chats::create`]. Hand-written (not generated): see the
/// [module docs](self).
pub struct Chat {
    runtime: Arc<Runtime>,
    inner: crate::chats::Chat,
}

impl generated::Chats {
    /// Creates a new [`Chat`] session. Blocking wrapper for
    /// [`crate::chats::Chats::create`] (Python `chats.create`).
    #[must_use]
    pub fn create(
        &self,
        model: &str,
        config: Option<crate::types::GenerateContentConfig>,
        history: Option<Vec<crate::types::Content>>,
    ) -> Chat {
        Chat {
            runtime: Arc::clone(&self.runtime),
            inner: self.inner.create(model, config, history),
        }
    }
}

impl generated::Operations {
    /// Fetches the latest status of a long-running operation, returning
    /// an updated value of the same type. Blocking wrapper for
    /// [`crate::operations::Operations::get`] (Python `operations.get`).
    /// Generic over `T`, which `tools/codegen/methods.toml`'s
    /// `"name: type"` argument format can't express -- see the
    /// [module docs](self).
    ///
    /// # Errors
    /// See the async method, plus
    /// [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn get<T>(&self, operation: &T) -> Result<T>
    where
        T: crate::operations::OperationLike + serde::Serialize + serde::de::DeserializeOwned,
    {
        self.runtime.block_on(self.inner.get(operation))?
    }
}

impl generated::FileSearchStores {
    /// Document get/list/delete for a File Search store's Documents
    /// (`client.file_search_stores().documents()`). Blocking wrapper for
    /// [`crate::file_search_stores::FileSearchStores::documents`].
    #[must_use]
    pub fn documents(&self) -> Documents {
        Documents::new(Arc::clone(&self.runtime), self.inner.documents())
    }
}

impl Chat {
    /// Sends `message` plus the accumulated curated history to the model
    /// and returns its response. Blocking wrapper for
    /// [`crate::chats::Chat::send_message`] (Python
    /// `chats.Chat.send_message`).
    ///
    /// # Errors
    /// See the async method, plus
    /// [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn send_message(
        &mut self,
        message: impl Into<crate::types::Contents>,
        config: Option<crate::types::GenerateContentConfig>,
    ) -> Result<crate::types::GenerateContentResponse> {
        self.runtime
            .block_on(self.inner.send_message(message, config))?
    }

    /// Sends `message` plus the accumulated curated history to the model,
    /// returning a [`BlockingStream`] of incremental response chunks that
    /// finalizes this [`Chat`]'s history once fully drained. Blocking
    /// wrapper for [`crate::chats::Chat::send_message_stream`] (Python
    /// `chats.Chat.send_message_stream`).
    ///
    /// Unlike the async `ChatStream<'_>` (which borrows the `Chat` for its
    /// lifetime), this drives the underlying stream to completion (or its
    /// first error) *inside* `block_on` -- since `self.runtime.block_on`
    /// cannot itself return a value borrowing from a future it drives --
    /// finalizing this `Chat`'s history exactly as the async version does,
    /// then hands back the already-fetched chunks as a [`BlockingStream`].
    /// A mid-stream failure is preserved as that stream's last (and only
    /// erroring) item, matching the async version; only a failure to
    /// *start* the request at all (before any chunk was produced)
    /// surfaces as this method's `Err`.
    ///
    /// # Errors
    /// See the async method, plus
    /// [`crate::Error::BlockingInsideRuntime`]
    /// if called from inside an already-running Tokio runtime.
    pub fn send_message_stream(
        &mut self,
        message: impl Into<crate::types::Contents>,
        config: Option<crate::types::GenerateContentConfig>,
    ) -> Result<BlockingStream<crate::types::GenerateContentResponse>> {
        let items = self.runtime.block_on(async {
            let mut stream = self.inner.send_message_stream(message, config).await?;
            let mut items = Vec::new();
            while let Some(item) = stream.next().await {
                let is_err = item.is_err();
                items.push(item);
                if is_err {
                    break;
                }
            }
            Result::Ok(items)
        })??;
        Ok(BlockingStream::new(
            Arc::clone(&self.runtime),
            tokio_stream::iter(items),
        ))
    }

    /// Returns the chat history. See [`crate::chats::Chat::get_history`].
    #[must_use]
    pub fn get_history(&self, curated: bool) -> &[crate::types::Content] {
        self.inner.get_history(curated)
    }
}
