// @generated by tools/codegen/gen_gaos.py from google-genai 2.28.0. DO NOT EDIT.
//
// SPDX-FileCopyrightText: 2025 Google LLC
// SPDX-FileCopyrightText: 2026 Daisuke ITO
// SPDX-License-Identifier: Apache-2.0
//
// Derived from the Google Gen AI Python SDK (google-genai 2.28.0),
// https://github.com/googleapis/python-genai
// Copyright 2025 Google LLC, licensed under the Apache License, Version 2.0.
//
// Modified: mechanically derived from the Python SDK's internal `_gaos` sub-SDK by gen_gaos.py:
// model fields, string enums and unions were reflected into Rust types, and HTTP
// operations were extracted from the resource classes. Doc comments reproduce the
// upstream Python docstrings.
//
// See the NOTICE file at the repository root for the full attribution.
//
// Edit tools/codegen/gen_gaos.py (or tools/codegen/gaos_overrides.toml) and re-run
// `python tools/codegen/generate.py --only gaos` instead.

//! One wiremock test per `_gaos` operation: HTTP verb, path, request body (golden
//! fixture) and typed response decoding. Generated from the upstream resource
//! classes; fixtures live in `tests/fixtures/gaos/`.

#![allow(
    clippy::pedantic,
    clippy::unwrap_used,
    clippy::expect_used,
    reason = "generated integration tests; failures should panic with the fixture name"
)]

use serde_json::Value;
use wiremock::{
    Mock, MockServer, ResponseTemplate,
    matchers::{body_json, method, path},
};

use crate::common::test_client;

fn wire_stream_body(body: &Value) -> Value {
    let mut body = body.clone();
    body["stream"] = Value::Bool(true);
    body
}

fn fixture(name: &str) -> Value {
    let path = format!(
        "{}/tests/fixtures/gaos/{name}.json",
        env!("CARGO_MANIFEST_DIR")
    );
    let text = std::fs::read_to_string(&path).expect("fixture is readable");
    serde_json::from_str(&text).expect("fixture is JSON")
}

#[tokio::test]
async fn agents_list_sends_get_and_decodes_response() {
    let server = MockServer::start().await;
    let expected = fixture("agents_list");
    let mock = Mock::given(method("GET"))
        .and(path("/v1beta/agents"))
        .respond_with(ResponseTemplate::new(200).set_body_json(&expected));
    mock.expect(1).mount(&server).await;
    let client = test_client(server.uri());
    let response = client
        .agents()
        .list(&Default::default())
        .await
        .expect("call succeeds");
    assert_eq!(
        serde_json::to_value(&response).expect("response serializes"),
        expected
    );
}

#[tokio::test]
async fn agents_create_sends_post_and_decodes_response() {
    let server = MockServer::start().await;
    let request_body = fixture("agents_create_request");
    let expected = fixture("agents_create");
    let mock = Mock::given(method("POST"))
        .and(path("/v1beta/agents"))
        .and(body_json(request_body.clone()))
        .respond_with(ResponseTemplate::new(200).set_body_json(&expected));
    mock.expect(1).mount(&server).await;
    let client = test_client(server.uri());
    let response = client
        .agents()
        .create(&serde_json::from_value(request_body.clone()).expect("request fixture decodes"))
        .await
        .expect("call succeeds");
    assert_eq!(
        serde_json::to_value(&response).expect("response serializes"),
        expected
    );
}

#[tokio::test]
async fn agents_delete_sends_delete_and_decodes_response() {
    let server = MockServer::start().await;
    let expected = fixture("agents_delete");
    let mock = Mock::given(method("DELETE"))
        .and(path("/v1beta/agents/test-agentsId"))
        .respond_with(ResponseTemplate::new(200).set_body_json(&expected));
    mock.expect(1).mount(&server).await;
    let client = test_client(server.uri());
    let response = client
        .agents()
        .delete("test-agentsId")
        .await
        .expect("call succeeds");
    assert_eq!(
        serde_json::to_value(&response).expect("response serializes"),
        expected
    );
}

#[tokio::test]
async fn agents_get_sends_get_and_decodes_response() {
    let server = MockServer::start().await;
    let expected = fixture("agents_get");
    let mock = Mock::given(method("GET"))
        .and(path("/v1beta/agents/test-agentsId"))
        .respond_with(ResponseTemplate::new(200).set_body_json(&expected));
    mock.expect(1).mount(&server).await;
    let client = test_client(server.uri());
    let response = client
        .agents()
        .get("test-agentsId")
        .await
        .expect("call succeeds");
    assert_eq!(
        serde_json::to_value(&response).expect("response serializes"),
        expected
    );
}

#[tokio::test]
async fn credentials_list_sends_get_and_decodes_response() {
    let server = MockServer::start().await;
    let expected = fixture("credentials_list");
    let mock = Mock::given(method("GET"))
        .and(path("/v1beta/credentials"))
        .respond_with(ResponseTemplate::new(200).set_body_json(&expected));
    mock.expect(1).mount(&server).await;
    let client = test_client(server.uri());
    let response = client
        .credentials()
        .list(&Default::default())
        .await
        .expect("call succeeds");
    assert_eq!(
        serde_json::to_value(&response).expect("response serializes"),
        expected
    );
}

#[tokio::test]
async fn credentials_create_sends_post_and_decodes_response() {
    let server = MockServer::start().await;
    let request_body = fixture("credentials_create_request");
    let expected = fixture("credentials_create");
    let mock = Mock::given(method("POST"))
        .and(path("/v1beta/credentials"))
        .and(body_json(request_body.clone()))
        .respond_with(ResponseTemplate::new(200).set_body_json(&expected));
    mock.expect(1).mount(&server).await;
    let client = test_client(server.uri());
    let response = client
        .credentials()
        .create(&serde_json::from_value(request_body.clone()).expect("request fixture decodes"))
        .await
        .expect("call succeeds");
    assert_eq!(
        serde_json::to_value(&response).expect("response serializes"),
        expected
    );
}

#[tokio::test]
async fn credentials_delete_sends_delete_and_decodes_response() {
    let server = MockServer::start().await;
    let expected = fixture("credentials_delete");
    let mock = Mock::given(method("DELETE"))
        .and(path("/v1beta/credentials/test-id"))
        .respond_with(ResponseTemplate::new(200).set_body_json(&expected));
    mock.expect(1).mount(&server).await;
    let client = test_client(server.uri());
    let response = client
        .credentials()
        .delete("test-id")
        .await
        .expect("call succeeds");
    assert_eq!(
        serde_json::to_value(&response).expect("response serializes"),
        expected
    );
}

#[tokio::test]
async fn credentials_get_sends_get_and_decodes_response() {
    let server = MockServer::start().await;
    let expected = fixture("credentials_get");
    let mock = Mock::given(method("GET"))
        .and(path("/v1beta/credentials/test-id"))
        .respond_with(ResponseTemplate::new(200).set_body_json(&expected));
    mock.expect(1).mount(&server).await;
    let client = test_client(server.uri());
    let response = client
        .credentials()
        .get("test-id")
        .await
        .expect("call succeeds");
    assert_eq!(
        serde_json::to_value(&response).expect("response serializes"),
        expected
    );
}

#[tokio::test]
async fn credentials_update_sends_patch_and_decodes_response() {
    let server = MockServer::start().await;
    let request_body = fixture("credentials_update_request");
    let expected = fixture("credentials_update");
    let mock = Mock::given(method("PATCH"))
        .and(path("/v1beta/credentials/test-id"))
        .and(body_json(request_body.clone()))
        .respond_with(ResponseTemplate::new(200).set_body_json(&expected));
    mock.expect(1).mount(&server).await;
    let client = test_client(server.uri());
    let response = client
        .credentials()
        .update(
            "test-id",
            &serde_json::from_value(request_body.clone()).expect("request fixture decodes"),
            &Default::default(),
        )
        .await
        .expect("call succeeds");
    assert_eq!(
        serde_json::to_value(&response).expect("response serializes"),
        expected
    );
}

#[tokio::test]
async fn environments_list_environments_sends_get_and_decodes_response() {
    let server = MockServer::start().await;
    let expected = fixture("environments_list_environments");
    let mock = Mock::given(method("GET"))
        .and(path("/v1beta/environments"))
        .respond_with(ResponseTemplate::new(200).set_body_json(&expected));
    mock.expect(1).mount(&server).await;
    let client = test_client(server.uri());
    let response = client
        .environments()
        .list_environments(&Default::default())
        .await
        .expect("call succeeds");
    assert_eq!(
        serde_json::to_value(&response).expect("response serializes"),
        expected
    );
}

#[tokio::test]
async fn environments_create_environment_sends_post_and_decodes_response() {
    let server = MockServer::start().await;
    let request_body = fixture("environments_create_environment_request");
    let expected = fixture("environments_create_environment");
    let mock = Mock::given(method("POST"))
        .and(path("/v1beta/environments"))
        .and(body_json(request_body.clone()))
        .respond_with(ResponseTemplate::new(200).set_body_json(&expected));
    mock.expect(1).mount(&server).await;
    let client = test_client(server.uri());
    let response = client
        .environments()
        .create_environment(
            &serde_json::from_value(request_body.clone()).expect("request fixture decodes"),
        )
        .await
        .expect("call succeeds");
    assert_eq!(
        serde_json::to_value(&response).expect("response serializes"),
        expected
    );
}

#[tokio::test]
async fn environments_delete_environment_sends_delete_and_decodes_response() {
    let server = MockServer::start().await;
    let expected = fixture("environments_delete_environment");
    let mock = Mock::given(method("DELETE"))
        .and(path("/v1beta/environments/test-id"))
        .respond_with(ResponseTemplate::new(200).set_body_json(&expected));
    mock.expect(1).mount(&server).await;
    let client = test_client(server.uri());
    let response = client
        .environments()
        .delete_environment("test-id")
        .await
        .expect("call succeeds");
    assert_eq!(
        serde_json::to_value(&response).expect("response serializes"),
        expected
    );
}

#[tokio::test]
async fn environments_get_environment_sends_get_and_decodes_response() {
    let server = MockServer::start().await;
    let expected = fixture("environments_get_environment");
    let mock = Mock::given(method("GET"))
        .and(path("/v1beta/environments/test-id"))
        .respond_with(ResponseTemplate::new(200).set_body_json(&expected));
    mock.expect(1).mount(&server).await;
    let client = test_client(server.uri());
    let response = client
        .environments()
        .get_environment("test-id")
        .await
        .expect("call succeeds");
    assert_eq!(
        serde_json::to_value(&response).expect("response serializes"),
        expected
    );
}

#[tokio::test]
async fn environments_files_list_sends_get_and_decodes_response() {
    let server = MockServer::start().await;
    let expected = fixture("environments_files_list");
    let mock = Mock::given(method("GET"))
        .and(path(
            "/v1beta/environments/test-environment/files/test-path",
        ))
        .respond_with(ResponseTemplate::new(200).set_body_json(&expected));
    mock.expect(1).mount(&server).await;
    let client = test_client(server.uri());
    let response = client
        .environments()
        .files_list("test-environment", "test-path", &Default::default())
        .await
        .expect("call succeeds");
    assert_eq!(
        serde_json::to_value(&response).expect("response serializes"),
        expected
    );
}

#[tokio::test]
async fn interactions_create_sends_post_and_decodes_response() {
    let server = MockServer::start().await;
    let request_body = fixture("interactions_create_request");
    let expected = fixture("interactions_create");
    let mock = Mock::given(method("POST"))
        .and(path("/v1beta/interactions"))
        .and(body_json(request_body.clone()))
        .respond_with(ResponseTemplate::new(200).set_body_json(&expected));
    mock.expect(1).mount(&server).await;
    let client = test_client(server.uri());
    let response = client
        .interactions()
        .create(&serde_json::from_value(request_body.clone()).expect("request fixture decodes"))
        .await
        .expect("call succeeds");
    assert_eq!(
        serde_json::to_value(&response).expect("response serializes"),
        expected
    );
}

#[tokio::test]
async fn interactions_create_stream_sends_post_and_decodes_response() {
    let server = MockServer::start().await;
    let request_body = fixture("interactions_create_request");
    let event = fixture("interactions_create_event");
    let mock = Mock::given(method("POST"))
        .and(path("/v1beta/interactions"))
        .and(body_json(wire_stream_body(&request_body)))
        .respond_with(
            ResponseTemplate::new(200)
                .insert_header("content-type", "text/event-stream")
                .set_body_string(format!("data: {event}\n\n")),
        );
    mock.expect(1).mount(&server).await;
    let client = test_client(server.uri());
    let mut events = client
        .interactions()
        .create_stream(
            &serde_json::from_value(request_body.clone()).expect("request fixture decodes"),
        )
        .await
        .expect("stream opens");
    let first = futures_util::StreamExt::next(&mut events)
        .await
        .expect("one event")
        .expect("event decodes");
    assert_eq!(
        serde_json::to_value(&first).expect("event serializes"),
        event
    );
}

#[tokio::test]
async fn interactions_delete_sends_delete_and_decodes_response() {
    let server = MockServer::start().await;
    let mock = Mock::given(method("DELETE"))
        .and(path("/v1beta/interactions/test-interactionsId"))
        .respond_with(ResponseTemplate::new(200));
    mock.expect(1).mount(&server).await;
    let client = test_client(server.uri());
    client
        .interactions()
        .delete("test-interactionsId")
        .await
        .expect("call succeeds");
}

#[tokio::test]
async fn interactions_get_sends_get_and_decodes_response() {
    let server = MockServer::start().await;
    let expected = fixture("interactions_get");
    let mock = Mock::given(method("GET"))
        .and(path("/v1beta/interactions/test-interactionsId"))
        .respond_with(ResponseTemplate::new(200).set_body_json(&expected));
    mock.expect(1).mount(&server).await;
    let client = test_client(server.uri());
    let response = client
        .interactions()
        .get("test-interactionsId", &Default::default())
        .await
        .expect("call succeeds");
    assert_eq!(
        serde_json::to_value(&response).expect("response serializes"),
        expected
    );
}

#[tokio::test]
async fn interactions_get_stream_sends_get_and_decodes_response() {
    let server = MockServer::start().await;
    let event = fixture("interactions_get_event");
    let mock = Mock::given(method("GET"))
        .and(path("/v1beta/interactions/test-interactionsId"))
        .respond_with(
            ResponseTemplate::new(200)
                .insert_header("content-type", "text/event-stream")
                .set_body_string(format!("data: {event}\n\n")),
        );
    mock.expect(1).mount(&server).await;
    let client = test_client(server.uri());
    let mut events = client
        .interactions()
        .get_stream("test-interactionsId", &Default::default())
        .await
        .expect("stream opens");
    let first = futures_util::StreamExt::next(&mut events)
        .await
        .expect("one event")
        .expect("event decodes");
    assert_eq!(
        serde_json::to_value(&first).expect("event serializes"),
        event
    );
}

#[tokio::test]
async fn interactions_cancel_sends_post_and_decodes_response() {
    let server = MockServer::start().await;
    let expected = fixture("interactions_cancel");
    let mock = Mock::given(method("POST"))
        .and(path("/v1beta/interactions/test-interactionsId/cancel"))
        .respond_with(ResponseTemplate::new(200).set_body_json(&expected));
    mock.expect(1).mount(&server).await;
    let client = test_client(server.uri());
    let response = client
        .interactions()
        .cancel("test-interactionsId")
        .await
        .expect("call succeeds");
    assert_eq!(
        serde_json::to_value(&response).expect("response serializes"),
        expected
    );
}

#[tokio::test]
async fn triggers_list_sends_get_and_decodes_response() {
    let server = MockServer::start().await;
    let expected = fixture("triggers_list");
    let mock = Mock::given(method("GET"))
        .and(path("/v1beta/triggers"))
        .respond_with(ResponseTemplate::new(200).set_body_json(&expected));
    mock.expect(1).mount(&server).await;
    let client = test_client(server.uri());
    let response = client
        .triggers()
        .list(&Default::default())
        .await
        .expect("call succeeds");
    assert_eq!(
        serde_json::to_value(&response).expect("response serializes"),
        expected
    );
}

#[tokio::test]
async fn triggers_create_sends_post_and_decodes_response() {
    let server = MockServer::start().await;
    let request_body = fixture("triggers_create_request");
    let expected = fixture("triggers_create");
    let mock = Mock::given(method("POST"))
        .and(path("/v1beta/triggers"))
        .and(body_json(request_body.clone()))
        .respond_with(ResponseTemplate::new(200).set_body_json(&expected));
    mock.expect(1).mount(&server).await;
    let client = test_client(server.uri());
    let response = client
        .triggers()
        .create(&serde_json::from_value(request_body.clone()).expect("request fixture decodes"))
        .await
        .expect("call succeeds");
    assert_eq!(
        serde_json::to_value(&response).expect("response serializes"),
        expected
    );
}

#[tokio::test]
async fn triggers_delete_sends_delete_and_decodes_response() {
    let server = MockServer::start().await;
    let expected = fixture("triggers_delete");
    let mock = Mock::given(method("DELETE"))
        .and(path("/v1beta/triggers/test-id"))
        .respond_with(ResponseTemplate::new(200).set_body_json(&expected));
    mock.expect(1).mount(&server).await;
    let client = test_client(server.uri());
    let response = client
        .triggers()
        .delete("test-id")
        .await
        .expect("call succeeds");
    assert_eq!(
        serde_json::to_value(&response).expect("response serializes"),
        expected
    );
}

#[tokio::test]
async fn triggers_get_sends_get_and_decodes_response() {
    let server = MockServer::start().await;
    let expected = fixture("triggers_get");
    let mock = Mock::given(method("GET"))
        .and(path("/v1beta/triggers/test-id"))
        .respond_with(ResponseTemplate::new(200).set_body_json(&expected));
    mock.expect(1).mount(&server).await;
    let client = test_client(server.uri());
    let response = client
        .triggers()
        .get("test-id")
        .await
        .expect("call succeeds");
    assert_eq!(
        serde_json::to_value(&response).expect("response serializes"),
        expected
    );
}

#[tokio::test]
async fn triggers_update_sends_patch_and_decodes_response() {
    let server = MockServer::start().await;
    let request_body = fixture("triggers_update_request");
    let expected = fixture("triggers_update");
    let mock = Mock::given(method("PATCH"))
        .and(path("/v1beta/triggers/test-id"))
        .and(body_json(request_body.clone()))
        .respond_with(ResponseTemplate::new(200).set_body_json(&expected));
    mock.expect(1).mount(&server).await;
    let client = test_client(server.uri());
    let response = client
        .triggers()
        .update(
            "test-id",
            &serde_json::from_value(request_body.clone()).expect("request fixture decodes"),
        )
        .await
        .expect("call succeeds");
    assert_eq!(
        serde_json::to_value(&response).expect("response serializes"),
        expected
    );
}

#[tokio::test]
async fn triggers_list_executions_sends_get_and_decodes_response() {
    let server = MockServer::start().await;
    let expected = fixture("triggers_list_executions");
    let mock = Mock::given(method("GET"))
        .and(path("/v1beta/triggers/test-triggerId/executions"))
        .respond_with(ResponseTemplate::new(200).set_body_json(&expected));
    mock.expect(1).mount(&server).await;
    let client = test_client(server.uri());
    let response = client
        .triggers()
        .list_executions("test-triggerId", &Default::default())
        .await
        .expect("call succeeds");
    assert_eq!(
        serde_json::to_value(&response).expect("response serializes"),
        expected
    );
}

#[tokio::test]
async fn triggers_run_sends_post_and_decodes_response() {
    let server = MockServer::start().await;
    let expected = fixture("triggers_run");
    let mock = Mock::given(method("POST"))
        .and(path("/v1beta/triggers/test-triggerId/executions"))
        .respond_with(ResponseTemplate::new(200).set_body_json(&expected));
    mock.expect(1).mount(&server).await;
    let client = test_client(server.uri());
    let response = client
        .triggers()
        .run("test-triggerId")
        .await
        .expect("call succeeds");
    assert_eq!(
        serde_json::to_value(&response).expect("response serializes"),
        expected
    );
}

#[tokio::test]
async fn voices_list_sends_get_and_decodes_response() {
    let server = MockServer::start().await;
    let expected = fixture("voices_list");
    let mock = Mock::given(method("GET"))
        .and(path("/v1beta/voices"))
        .respond_with(ResponseTemplate::new(200).set_body_json(&expected));
    mock.expect(1).mount(&server).await;
    let client = test_client(server.uri());
    let response = client
        .voices()
        .list(&Default::default())
        .await
        .expect("call succeeds");
    assert_eq!(
        serde_json::to_value(&response).expect("response serializes"),
        expected
    );
}

#[tokio::test]
async fn voices_create_sends_post_and_decodes_response() {
    let server = MockServer::start().await;
    let request_body = fixture("voices_create_request");
    let expected = fixture("voices_create");
    let mock = Mock::given(method("POST"))
        .and(path("/v1beta/voices"))
        .and(body_json(request_body.clone()))
        .respond_with(ResponseTemplate::new(200).set_body_json(&expected));
    mock.expect(1).mount(&server).await;
    let client = test_client(server.uri());
    let response = client
        .voices()
        .create(&serde_json::from_value(request_body.clone()).expect("request fixture decodes"))
        .await
        .expect("call succeeds");
    assert_eq!(
        serde_json::to_value(&response).expect("response serializes"),
        expected
    );
}

#[tokio::test]
async fn voices_delete_sends_delete_and_decodes_response() {
    let server = MockServer::start().await;
    let expected = fixture("voices_delete");
    let mock = Mock::given(method("DELETE"))
        .and(path("/v1beta/voices/test-voicesId"))
        .respond_with(ResponseTemplate::new(200).set_body_json(&expected));
    mock.expect(1).mount(&server).await;
    let client = test_client(server.uri());
    let response = client
        .voices()
        .delete("test-voicesId")
        .await
        .expect("call succeeds");
    assert_eq!(
        serde_json::to_value(&response).expect("response serializes"),
        expected
    );
}

#[tokio::test]
async fn voices_get_sends_get_and_decodes_response() {
    let server = MockServer::start().await;
    let expected = fixture("voices_get");
    let mock = Mock::given(method("GET"))
        .and(path("/v1beta/voices/test-voicesId"))
        .respond_with(ResponseTemplate::new(200).set_body_json(&expected));
    mock.expect(1).mount(&server).await;
    let client = test_client(server.uri());
    let response = client
        .voices()
        .get("test-voicesId")
        .await
        .expect("call succeeds");
    assert_eq!(
        serde_json::to_value(&response).expect("response serializes"),
        expected
    );
}

#[tokio::test]
async fn webhooks_list_sends_get_and_decodes_response() {
    let server = MockServer::start().await;
    let expected = fixture("webhooks_list");
    let mock = Mock::given(method("GET"))
        .and(path("/v1beta/webhooks"))
        .respond_with(ResponseTemplate::new(200).set_body_json(&expected));
    mock.expect(1).mount(&server).await;
    let client = test_client(server.uri());
    let response = client
        .webhooks()
        .list(&Default::default())
        .await
        .expect("call succeeds");
    assert_eq!(
        serde_json::to_value(&response).expect("response serializes"),
        expected
    );
}

#[tokio::test]
async fn webhooks_create_sends_post_and_decodes_response() {
    let server = MockServer::start().await;
    let request_body = fixture("webhooks_create_request");
    let expected = fixture("webhooks_create");
    let mock = Mock::given(method("POST"))
        .and(path("/v1beta/webhooks"))
        .and(body_json(request_body.clone()))
        .respond_with(ResponseTemplate::new(200).set_body_json(&expected));
    mock.expect(1).mount(&server).await;
    let client = test_client(server.uri());
    let response = client
        .webhooks()
        .create(&serde_json::from_value(request_body.clone()).expect("request fixture decodes"))
        .await
        .expect("call succeeds");
    assert_eq!(
        serde_json::to_value(&response).expect("response serializes"),
        expected
    );
}

#[tokio::test]
async fn webhooks_delete_sends_delete_and_decodes_response() {
    let server = MockServer::start().await;
    let expected = fixture("webhooks_delete");
    let mock = Mock::given(method("DELETE"))
        .and(path("/v1beta/webhooks/test-id"))
        .respond_with(ResponseTemplate::new(200).set_body_json(&expected));
    mock.expect(1).mount(&server).await;
    let client = test_client(server.uri());
    let response = client
        .webhooks()
        .delete("test-id")
        .await
        .expect("call succeeds");
    assert_eq!(
        serde_json::to_value(&response).expect("response serializes"),
        expected
    );
}

#[tokio::test]
async fn webhooks_get_sends_get_and_decodes_response() {
    let server = MockServer::start().await;
    let expected = fixture("webhooks_get");
    let mock = Mock::given(method("GET"))
        .and(path("/v1beta/webhooks/test-id"))
        .respond_with(ResponseTemplate::new(200).set_body_json(&expected));
    mock.expect(1).mount(&server).await;
    let client = test_client(server.uri());
    let response = client
        .webhooks()
        .get("test-id")
        .await
        .expect("call succeeds");
    assert_eq!(
        serde_json::to_value(&response).expect("response serializes"),
        expected
    );
}

#[tokio::test]
async fn webhooks_update_sends_patch_and_decodes_response() {
    let server = MockServer::start().await;
    let request_body = fixture("webhooks_update_request");
    let expected = fixture("webhooks_update");
    let mock = Mock::given(method("PATCH"))
        .and(path("/v1beta/webhooks/test-id"))
        .and(body_json(request_body.clone()))
        .respond_with(ResponseTemplate::new(200).set_body_json(&expected));
    mock.expect(1).mount(&server).await;
    let client = test_client(server.uri());
    let response = client
        .webhooks()
        .update(
            "test-id",
            Some(&serde_json::from_value(request_body.clone()).expect("request fixture decodes")),
            &Default::default(),
        )
        .await
        .expect("call succeeds");
    assert_eq!(
        serde_json::to_value(&response).expect("response serializes"),
        expected
    );
}

#[tokio::test]
async fn webhooks_ping_sends_post_and_decodes_response() {
    let server = MockServer::start().await;
    let expected = fixture("webhooks_ping");
    let mock = Mock::given(method("POST"))
        .and(path("/v1beta/webhooks/test-id:ping"))
        .respond_with(ResponseTemplate::new(200).set_body_json(&expected));
    mock.expect(1).mount(&server).await;
    let client = test_client(server.uri());
    let response = client
        .webhooks()
        .ping("test-id", None)
        .await
        .expect("call succeeds");
    assert_eq!(
        serde_json::to_value(&response).expect("response serializes"),
        expected
    );
}

#[tokio::test]
async fn webhooks_rotate_signing_secret_sends_post_and_decodes_response() {
    let server = MockServer::start().await;
    let request_body = fixture("webhooks_rotate_signing_secret_request");
    let expected = fixture("webhooks_rotate_signing_secret");
    let mock = Mock::given(method("POST"))
        .and(path("/v1beta/webhooks/test-id:rotateSigningSecret"))
        .and(body_json(request_body.clone()))
        .respond_with(ResponseTemplate::new(200).set_body_json(&expected));
    mock.expect(1).mount(&server).await;
    let client = test_client(server.uri());
    let response = client
        .webhooks()
        .rotate_signing_secret(
            "test-id",
            Some(&serde_json::from_value(request_body.clone()).expect("request fixture decodes")),
        )
        .await
        .expect("call succeeds");
    assert_eq!(
        serde_json::to_value(&response).expect("response serializes"),
        expected
    );
}
