//! Integration tests for the `_gaos` surface (Interactions, agents, environments,
//! triggers, webhooks, voices, credentials), driven through the crate's public API
//! against a wiremock server.
//!
//! `generated_ops` is generated by `tools/codegen/gen_gaos.py` (one test per
//! operation). Hand-written, ported upstream tests live in sibling modules.

#![allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::default_trait_access,
    clippy::too_many_lines,
    clippy::redundant_closure_for_method_calls,
    clippy::needless_pass_by_value,
    reason = "ported upstream tests: a failed setup or assertion should panic, and each test mirrors one long Python function and its `Default` arguments"
)]

#[path = "../common/mod.rs"]
mod common;
mod generated_ops;
mod open_unions;
mod recording;
mod test_credentials_lifecycle;
mod test_environments_lifecycle;
mod test_triggers_lifecycle;
mod test_voices_lifecycle;
